### ISSUE TITLE
External Storage, DFS (SMB/CIFS). smb4php fails to display content that is readable by smbclient

### ISSUE THREAD

**Issue by alexleake** [owncloud/core#12498]
### Steps to reproduce
1. Install ownCloud 7.0.1 (7.0.3 tested also)
2. Add external storage (SMB / CIFS), where the location is the root of a DFS namespace
3. Browse to a folder that only contains DFS links

### Expected behaviour
Show the same output as smbclient (i.e. the folder contents).

### Actual behaviour
The folder is empty, and the smb4php log says something like this:

{"app":"PHP","message":"url_stat(): path 'Public\\\\Applications\\\\MATLAB' not found at \/var\/www\/owncloud\/apps\/files_external\/3rdparty\/smb4php\/smb.php#260","level":3,"time":"2014-09-10T04:46:31+00:00"}

Despite being able to run this command successfully on the same server & same credentials:

smbclient -N -U 'USERNAME%PASSWORD' -O 'TCP_NODELAY IPTOS_LOWDELAY SO_KEEPALIVE SO_RCVBUF=8192 SO_SNDBUF=8192' -O 'TCP_NODELAY IPTOS_LOWDELAY SO_KEEPALIVE SO_RCVBUF=8192 SO_SNDBUF=8192' -d 0 '//domain.ac.uk/files' -c 'dir "Public\\\\Applications\\\\MATLAB"'

I've tried increasing the php "memory_lmit" to 1024 MB too (see the php errors below) to no avail.

### Server configuration
**Operating system**:
Ubuntu 14.04 LTS, x86_64

**Web server:**
Apache (2.4.7-1ubuntu4.1)

**Database:**
MySQL (5.5.40-0ubuntu0.14.04.1)

**PHP version:**
php5 (5.5.9+dfsg-1ubuntu4.5)

**ownCloud version:** (see ownCloud admin page)
ownCloud 7.0.1 (stable)

**Updated from an older ownCloud or fresh install:**
Fresh install.

**List of activated apps:**
- Files
- Activity
- External Storage

**The content of config/config.php:**

<?php
$CONFIG = array (
  'instanceid' => '',
  'passwordsalt' => '',
  'trusted_domains' => 
  array (
    0 => 'domain.ac.uk',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'dbtype' => 'mysql',
  'version' => '7.0.1.1',
  'dbname' => 'owncloud',
  'dbhost' => 'domain.ac.uk',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_bucsops',
  'dbpassword' => '',
  'installed' => true,
  'proxy' => 'proxy.domain.ac.uk:3128',
  'ldapIgnoreNamingRules' => false,
  'forcessl' => true,
  'enable_previews' => false,
  'preview_libreoffice_path' => '/usr/bin/libreoffice',
);

**Are you using external storage, if yes which one:** local/smb/sftp/...
Yes, smb.

**Are you using encryption:** yes/no
No.

### Client configuration
Chromium 40.0.2214.10 (tested others too...)

**Operating system:**
gentoo, kernel 3.16-5 x86_64

#### Web server error log

The webserver logs number in the gigabytes, however here are a few useful excerpts: 

[Fri Nov 28 04:47:03.798877 2014] [:error] [pid 11104] [client 138.38.44.114:35618] PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 72 bytes) in /var/www/owncloud/apps/files_external/3rdparty/smb4php/smb.php on line 277, referer: https://domain.ac.uk/index.php/apps/files/?dir=%2FX%20Drive
[Fri Nov 28 04:47:07.814591 2014] [core:notice] [pid 8725] AH00051: child pid 11104 exit signal Segmentation fault (11), possible coredump in /etc/apache2

#### ownCloud log (data/owncloud.log)

{"app":"PHP","message":"url_stat(): path 'Public\\Applications\\MATLAB' not found at \/var\/www\/owncloud\/apps\/files_external\/3rdparty\/smb4php\/smb.php#260","level":3,"time":"2014-09-10T04:46:31+00:00"}

**Comment by alexleake** [comment]
Hello all,

I'd like to thank @icewind1991 for his contributions, his branch smb-new along with the libsmbclient-php (https://github.com/eduardok/libsmbclient-php) have fixed this issue.

To clarify, the latest version of ownCloud (even the v8.0.1 alpha) are still affected - @icewind1991 's smb-new branch is not.


Kind Regards,
Alex.

**Comment by Xenopathic** [comment]
I've got a DFS setup working on Samba4 now, so I can do some testing of this. In 8.0 it is broken with the originally-posted error message. I'll try testing with master to see if the issue has gone.

**Comment by beemoon** [comment]
hello
I m looking for a step by step howto to connect OC8 with a DFS server. OC is on a Debian 8 server and authenticate userss with AD 2008

**Comment by icewind1991** [comment]
Try the rc1 of oc8.1 which comes with a new smb backend

**Comment by butonic** [comment]
@icewind1991 @Xenopathic Is this fixed in 8.1?

**Comment by Xenopathic** [comment]
With the (nearly) latest master, *without* libsmbclient-php, I get the following error when trying to view a DFS root:

    Icewind\\SMB\\Exception\\NotFoundException: "Invalid request for /public"

However, by specifying 'dfs/public' as the share to connect to, I can bypass this and get directly to the share, so that functionality works. I'll try with libsmbclient-php in just a moment...

**Comment by Xenopathic** [comment]
OK, with libsmbclient-php installed, both viewing the DFS root (and accessing DFS links under it) and directly connecting through a DFS share work. So there's still a problem with DFS links with the smbclient fallback.

**Comment by Xenopathic** [comment]
The problem is as follows:

ownCloud uses the `allinfo` command in smbclient to retrieve information about a file/folder. For normal directories and files this works fine, but for DFS links (or even files/folders under the link) will fail with an "NT_STATUS_OBJECT_PATH_NOT_FOUND: getting alt name for \path". There seems no easy workaround for this...

My suggestion is that use of DFS roots requires the PHP extension to be installed. It's likely that an environment using DFS at all will be able to use the PHP extension. However, there are other bugs with DFS links, with connections remaining open...

**Comment by PVince81** [comment]
Is there any hope to make the smbclient fallback work with DFS too ?
Ideal is to use libphp5-smbclient instead which uses the native library and has much better performance (and streaming).

@Xenopathic @icewind1991 

CC @jmaciasportela @cmonteroluque

**Comment by Xenopathic** [comment]
@PVince81 smbclient fallback works if the share is set within a DFS link itself, e.g. if `/dfs/share` is a DFS link, setting the share to `dfs/share` will work, however setting `dfs` as the share and trying to browse to `share` will *not* work. That behaviour is broken upstream, there's nothing we can do about it. In reality though, anyone using DFS is probably an enterprise customer and needs to use the PHP native extension :smile:

**Comment by PVince81** [comment]
Note, when using DFS the best is to have at least Samba 4.2 installed

**Comment by PVince81** [comment]
Best would be to install php5-libsmbclient which makes it possible to use native libsmbclient access that is more efficient and works properly with DFS.

**Comment by PVince81** [comment]
See previous comment.
