### ISSUE TITLE
 Integrity constraint violation when sync 50 20-MB files

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#13934]
### Steps to reproduce

1. Install owncloud 
2. create user1, user2, and user3
3. Install owncloud client on a different system
4. User1 creates a local folder /jrm/smashbox/results/test_shareFile/sharer/localShareDir and syncs to the sever

    ```
/usr/bin/owncloudcmd  --trust /jrm/smashbox/results/test_shareFile/sharer/ owncloud://user1:<pw>@x.x.x.x/owncloud/remote.php/webdav/
```

5. User1 shares the folder with user2 and user3

    ```
curl -u <un>:<pw> --data "path=localShareDir&shareType=0&shareWith=user2&permissions=31" http://<un>:<pw>@x.x.x.x/owncloud/ocs/v1.php/apps/files_sharing/api/v1/shares
curl -u <un>:<pw> --data "path=localShareDir&shareType=0&shareWith=user3&permissions=31" http://<un>:<pw>@x.x.x.x/owncloud/ocs/v1.php/apps/files_sharing/api/v1/shares
```

6. User2 and user3 each sync to validate the folder is present

    ```
/usr/bin/owncloudcmd  --trust /jrm/smashbox/results/test_shareFile/shareeOne/ owncloud://user2:<pw>@x.x.x.x/owncloud/remote.php/webdav/
/usr/bin/owncloudcmd  --trust /jrm/smashbox/results/test_shareFile/shareeTwo/ owncloud://user3:<pw>@x.x.x.x/owncloud/remote.php/webdav/
```

7. User2 creates 50 20MB files and then syncs to the server

    ```
/usr/bin/owncloudcmd --trust /root/jrm/smashbox/results/test_shareFile/shareeOne/ owncloud://user2:<pw>@x.x.x.x/owncloud/remote.php/webdav/
```

### Expected behaviour

The files should always sync successfully.

### Actual behaviour

1 out of every 5 runs, there is a db contraint violation

Server log file:

```
{"reqId":"06b7a7c9b52b48b0a12f9a40b5cc200d","remoteAddr":"172.18.5.120","app":"remote","message":"An exception occurred while executing 'INSERT INTO \"oc_filecache\" (\"mimepart\", \"mimetype\", \"mtime\", \"size\", \"etag\", \"storage_mtime\", \"permissions\", \"parent\", \"path_hash\", \"path\", \"name\", \"storage\") VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [\"3\", \"8\", 1423168184, 20000000, \"1a6d98fbce8407382fff0f51a464cd99\", 1423168184, 27, \"21\", \"3d7effc8270492700eb1c978f191421a\", \"files\\\/localShareDir\\\/TEST_FILE_NEW_USER_SHARE_17.dat\", \"TEST_FILE_NEW_USER_SHARE_17.dat\", \"3\"]:\n\nSQLSTATE[23000]: Integrity constraint violation: 19 columns storage, path_hash are not unique","level":4,"time":"2015-02-05T20:29:45+00:00"}
```

### Server Host info:

CentOS release 6.6 (Final)
PHP 5.4.36

### Server configuration

ownCloud 8.0 RC 2 (daily) Build:2015-02-05T04:18:39+00:00 defe41ee4e55f6336cf95479bc53d883be2b5d1b
sqllite DB

### Client Host info:

Ubuntu 14.04
PHP 5.5.9

### Client Configuration

owncloudcmd version 1.8.0

**Comment by PVince81** [comment]
Does it also happen with mysql ?

I believe that smashbox is able to trigger syncs at exactly the same time for two sync clients and increase the likeliness to run into those "Duplicate entry" issues.

Still, seems to be a way to reproduce the issue consistently and should hopefully make it easier to debug. Isn't it @icewind1991 ? I remember you had a related ticket ?

**Comment by PVince81** [comment]
Possibly related: https://github.com/owncloud/core/issues/2566

**Comment by PVince81** [comment]
@DeepDiver1975 you suggested to use "INSERT WHERE EXISTS" or something ?

**Comment by jnfrmarks** [comment]
@PVince81 

I modified the test so that only one sync is happening at a time.

I was focusing on sqllite; will now rerun with mysql.

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 you suggested to use "INSERT WHERE EXISTS" or something ?

https://github.com/owncloud/core/blob/master/lib/public/db.php#L67

insertIfNotExist() is the way to go .. it's implementation could be optimized as far as I can tell - but still valid

**Comment by jnfrmarks** [comment]
I ran this test 10 times against RC2 with mysql and did not see this error.

**Comment by dragotin** [comment]
I saw this problem as well while syncing a couple of hundred small files, with SQLite db.

**Comment by PVince81** [comment]
@icewind1991 did you get a chance to check this ? (https://github.com/owncloud/core/issues/2566)
SQLite seems to make it possible to reproduce the duplicate entry issues more easily.

**Comment by nickvergessen** [comment]
> > @DeepDiver1975 you suggested to use "INSERT WHERE EXISTS" or something ?
>
> https://github.com/owncloud/core/blob/master/lib/public/db.php#L67
> insertIfNotExist() is the way to go .. it's implementation could be optimized as far as I can tell - but still valid

I'm really sorry, but I think this will not work so easily here.
The doc block of the method you linked to is wrong (seems like it was only changed on the other methods).
https://github.com/owncloud/core/blob/fix-public-php/lib/private/db/adapter.php#L43
`array $input key->value pair, key has to be sanitized properly`

So we can not specify what our key is, instead it selects with all the values, so when mtime of the file, storage, size or etag changed, we will still try to insert the value and get the constraint error.

**Comment by PVince81** [comment]
@nickvergessen there are a few different "Duplicate entry" cases. Some one the mimetype table, but this one seems to be on the file cache:
```
{
  "reqId": "06b7a7c9b52b48b0a12f9a40b5cc200d",
  "remoteAddr": "172.18.5.120",
  "app": "remote",
  "message": "An exception occurred while executing 'INSERT INTO \"oc_filecache\" (\"mimepart\", \"mimetype\", \"mtime\", \"size\", \"etag\", \"storage_mtime\", \"permissions\", \"parent\", \"path_hash\", \"path\", \"name\", \"storage\") VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [\"3\", \"8\", 1423168184, 20000000, \"1a6d98fbce8407382fff0f51a464cd99\", 1423168184, 27, \"21\", \"3d7effc8270492700eb1c978f191421a\", \"files\\\\/localShareDir\\\\/TEST_FILE_NEW_USER_SHARE_17.dat\", \"TEST_FILE_NEW_USER_SHARE_17.dat\", \"3\"]:\n\nSQLSTATE[23000]: Integrity constraint violation: 19 columns storage, path_hash are not unique",
  "level": 4,
  "time": "2015-02-05T20:29:45+00:00"
}
```

**Comment by PVince81** [comment]
I think "insertIfNotExists" might just be a quick workaround. I'm pretty sure it would only hide the worse part of what could happen during such race conditions.
From what I understood it could happen that two scanners are running at exactly the same time for the same file. Ideally only a single scanner should run for a single file/folder to avoid unpredictable results (for which "Duplicate entry" is only one, who knows what else can go wrong...)

**Comment by nickvergessen** [comment]
@PVince81 the idea of my comment was to tell you that we can't use `insertIfNotExists()` here anyway.

**Comment by dragotin** [comment]
@jnfrmarks please validate with pull request https://github.com/owncloud/core/issues/14734
It fixes the problems for me.

**Comment by cdamken** [comment]
@jnfrmarks  https://github.com/owncloud/core/issues/13934#issuecomment-77584341

Could you please tell me if it fix the problem?

**Comment by jnfrmarks** [comment]
@cdamken 

PR #14734 did not resolve the issue for me.

**Comment by cdamken** [comment]
@jnfrmarks Thank you

**Comment by tilllt** [comment]
just upgraded from 7.0.4 to 8.0.2 ... thought i'd give the file cache a fresh start, truncated the oc_filecache from the database, ran su www-data -c 'php console.php files:scan --all', leading to this error: 

```
DB Error: "An exception occurred while executing 'INSERT INTO `oc_filecache` (`mimepart`,`mimetype`,`mtime`,`size`,`etag`,`storage_mtime`,`permissions`,`parent`,`path_hash`,`path`,`name`,`storage`) SELECT ?,?,?,?,?,?,?,?,?,?,?,? FROM `oc_filecache` WHERE `mimepart` = ? AND `mimetype` = ? AND `mtime` = ? AND `size` = ? AND `etag` = ? AND `storage_mtime` = ? AND `permissions` = ? AND `parent` = ? AND `path_hash` = ? AND `path` = ? AND `name` = ? AND `storage` = ? HAVING COUNT(*) = 0' with params ["1", "2", "1269790789", "-1", "55084e07cc127", "1269790789", "31", "3334", "ffdb8e91a21caa3b4ad7abf8cb8f03e7", "\u00b0unsortierte musik\/Slayer", "Slayer", "39", "1", "2", "1269790789", "-1", "55084e07cc127", "1269790789", "31", "3334", "ffdb8e91a21caa3b4ad7abf8cb8f03e7", "\u00b0unsortierte musik\/Slayer", "Slayer", "39"]: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '39-ffdb8e91a21caa3b4ad7abf8cb8f03e7' for key 'fs_storage_path_hash'"<br />Offending command was: INSERT INTO `*PREFIX*filecache` (`mimepart`,`mimetype`,`mtime`,`size`,`etag`,`storage_mtime`,`permissions`,`parent`,`path_hash`,`path`,`name`,`storage`) SELECT ?,?,?,?,?,?,?,?,?,?,?,? FROM `*PREFIX*filecache` WHERE `mimepart` = ? AND `mimetype` = ? AND `mtime` = ? AND `size` = ? AND `etag` = ? AND `storage_mtime` = ? AND `permissions` = ? AND `parent` = ? AND `path_hash` = ? AND `path` = ? AND `name` = ? AND `storage` = ? HAVING COUNT(*) = 0<br />
```

**Comment by nickvergessen** [comment]
@jnfrmarks can you run your tests against current master? and on the follow stable8 PR: https://github.com/owncloud/core/pull/14914 That would be very awesome

**Comment by PVince81** [comment]
@nickvergessen one of the tests has gotten worse with special characters, see https://github.com/owncloud/core/issues/14964#issue-62435398 (maybe an escaping issue)

**Comment by tilllt** [comment]
is the problem i experienced unrelated to this, if so, should i open another ticket for it?

**Comment by nickvergessen** [comment]
@tilllt it could be the same problem. If you know coding, you could try to add the fix https://github.com/owncloud/core/pull/14914/files to your installation and help testing it.

**Comment by tilllt** [comment]
FIY, this issue seems to have much deeper consequences than i first saw. Pretty much the whole "shared files" settings are lost or messed up, folder i never shared are suddenly shared, folders have weirdly wrong names, folder that were shared are not shared anymore...

![bildschirmfoto-2015-03-18-um-11 05 15](https://cloud.githubusercontent.com/assets/1854364/6706585/38013b78-cd5f-11e4-8d31-edc273cd514e.png)

**Comment by PVince81** [comment]
@tilllt "folder that wasn't shared is suddenly shared". You are using SQLite, aren't you ? This sounds like the "fileid" recycling issue: #14665 
Better restore your database. If possible, switch to MySQL or PostgreSQL.

**Comment by tilllt** [comment]
@PVince81: no, this is on mysql: 5.5.41-0+wheezy1 - (Debian), nginx 1.6.2, PHP 5.5.22-1~dotdeb.1

**Comment by PVince81** [comment]
By the way, you should never truncate "oc_filecache" (some blogs said so but were wrong, it breaks shares). If it's on mysql, I can't explain why files and shares would mix themselves up. As far as I know, MySQL's autoincrement shouldn't reuse older file ids.

**Comment by tilllt** [comment]
Could my problem be related to wrongly duplicating / backup of the database before installing a new version? I usually make a database copy in phpmyadmin before doing an upgrade using the default settings like this: 
![bildschirmfoto 2015-03-18 um 11 45 16](https://cloud.githubusercontent.com/assets/1854364/6707153/7766c13e-cd64-11e4-8056-dca047b9dc34.png)

**Comment by PVince81** [comment]
@tilllt not sure. But if the backup involves modifying the fileid (maybe that "AUTO_INCREMENT" option), then it will likely break the file-share relationships. Shares are linked to files using the fileid.

**Comment by tilllt** [comment]
@PVince81 from my research, NOT adding the auto_increment option would break the database copy... but maybe that info is wrong. So, if truncating the OC_FILECACHE is not the way to do it, what is the correct way to completely scratch the filecache and rebuild it? dropping / truncating the OC_filecache table is what is basically mentioned everywhere as the only working method.

**Comment by PVince81** [comment]
You should only run "./occ files:scan --all". It should automatically delete the outdates entries and add/update the correct ones based on whatever is actually on disk.

**Comment by tilllt** [comment]
i re-exported my OC7.0.4 database, left out the truncate OC_FILECHACHE step and converted the database scheme again to 8.0.2 ... seems to have been the culprit for all the weird things happening. so the cause of the problem seem to have been the bad advice i had been following of truncating the table. unfortunately this advice seems to be all over the internet so i guess a lot of people will do the same mistake.

**Comment by tilllt** [comment]
Nope, celebrating too early. Even without Truncating the OC_Filecache table, the error shows up, less frequent when rebuilding the entire filecache but still:
´´´
{"reqId":"xyz7","remoteAddr":"10.2.3.4","app":"core","message":"DB Error: \"An exception occurred while executing 'INSERT INTO `oc_filecache` (`mimepart`,`mimetype`,`mtime`,`size`,`etag`,`storage_mtime`,`permissions`,`path_hash`,`path`,`parent`,`name`,`storage`) SELECT ?,?,?,?,?,?,?,?,?,?,?,? FROM `oc_filecache` WHERE `mimepart` = ? AND `mimetype` = ? AND `mtime` = ? AND `size` = ? AND `etag` = ? AND `storage_mtime` = ? AND `permissions` = ? AND `path_hash` = ? AND `path` = ? AND `parent` = ? AND `name` = ? AND `storage` = ? HAVING COUNT(*) = 0' with params [\"1\", \"2\", \"1381960184\", \"-1\", \"5509a40570812\", \"1381960184\", \"31\", \"4cc87303abd3e803b18e8a4aaac3f3ac\", \"AL\\u00ffS SEVEN WALKS\", \"4556\", \"AL\\u00ffS SEVEN WALKS\", \"30\", \"1\", \"2\", \"1381960184\", \"-1\", \"5509a40570812\", \"1381960184\", \"31\", \"4cc87303abd3e803b18e8a4aaac3f3ac\", \"AL\\u00ffS SEVEN WALKS\", \"4556\", \"AL\\u00ffS SEVEN WALKS\", \"30\"]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '30-4cc87303abd3e803b18e8a4aaac3f3ac' for key 'fs_storage_path_hash'\"<br \/>Offending command was: INSERT INTO `*PREFIX*filecache` (`mimepart`,`mimetype`,`mtime`,`size`,`etag`,`storage_mtime`,`permissions`,`path_hash`,`path`,`parent`,`name`,`storage`) SELECT ?,?,?,?,?,?,?,?,?,?,?,? FROM `*PREFIX*filecache` WHERE `mimepart` = ? AND `mimetype` = ? AND `mtime` = ? AND `size` = ? AND `etag` = ? AND `storage_mtime` = ? AND `permissions` = ? AND `path_hash` = ? AND `path` = ? AND `parent` = ? AND `name` = ? AND `storage` = ? HAVING COUNT(*) = 0<br \/>","level":4,"time":"2015-03-18T16:13:36+00:00"}
{"reqId":"abdxed","remoteAddr":"10.2.3.4","app":"remote","message":"Datenbankfehler","level":4,"time":"2015-03-18T16:13:36+00:00"}
´´´

**Comment by jnfrmarks** [comment]
Running a flavor of the test (more users syncing and uploading), I'm seeing these errors in the server log file:

```

{"reqId":"SwLaXBm7GqvRG\/AwRbVx","remoteAddr":"x.x.x.x","app":"webdav","message":"Exception: {\"Message\":\"An exception occurred while executing 'INSERT INTO `filecache` (`mimepart`,`mimetype`,`mtime`,`size`,`etag`,`storage_mtime`,`permissions`,`path_hash`,`path`,`parent`,`name`,`storage`) SELECT ?,?,?,?,?,?,?,?,?,?,?,? FROM `filecache` WHERE `storage` = ? AND `path_hash` = ? HAVING COUNT(*) = 0' with params [\\\"1\\\", \\\"2\\\", 1427278981, -1, \\\"55128c858e363\\\", 1427278981, 23, \\\"d41d8cd98f00b204e9800998ecf8427e\\\", \\\"\\\", -1, \\\"\\\", \\\"131\\\", \\\"131\\\", \\\"d41d8cd98f00b204e9800998ecf8427e\\\"]:\\n\\nSQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(116): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(996): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'INSERT INTO `fi...', Array)\\n#2 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/db\\\/connection.php(132): Doctrine\\\\DBAL\\\\Connection->executeUpdate('INSERT INTO `fi...', Array, Array)\\n#3 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/db\\\/adapter.php(75): OC\\\\DB\\\\Connection->executeUpdate('INSERT INTO `*P...', Array)\\n#4 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/db\\\/connection.php(171): OC\\\\DB\\\\Adapter->insertIfNotExist('*PREFIX*filecac...', Array, Array)\\n#5 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/files\\\/cache\\\/cache.php(255): OC\\\\DB\\\\Connection->insertIfNotExist('*PREFIX*filecac...', Array, Array)\\n#6 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/files\\\/cache\\\/scanner.php(199): OC\\\\Files\\\\Cache\\\\Cache->put('', Array)\\n#7 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/files\\\/cache\\\/scanner.php(165): OC\\\\Files\\\\Cache\\\\Scanner->addToCache('', Array, -1)\\n#8 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/files\\\/cache\\\/scanner.php(235): OC\\\\Files\\\\Cache\\\\Scanner->scanFile('', 3)\\n#9 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/files\\\/cache\\\/updater.php(73): OC\\\\Files\\\\Cache\\\\Scanner->scan('', false)\\n#10 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php(970): OC\\\\Files\\\\Cache\\\\Updater->update('\\\/user9')\\n#11 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php(196): OC\\\\Files\\\\View->basicOperation('mkdir', '\\\/user9', Array)\\n#12 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/files\\\/node\\\/folder.php(188): OC\\\\Files\\\\View->mkdir('\\\/user9')\\n#13 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/server.php(420): OC\\\\Files\\\\Node\\\\Folder->newFolder('\\\/user9')\\n#14 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/util.php(139): OC\\\\Server->getUserFolder('user9')\\n#15 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/user.php(226): OC_Util::setupFS('user9')\\n#16 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(62): OC_User::login('user9', 'demo')\\n#17 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Backend\\\/AbstractBasic.php(74): OC\\\\Connector\\\\Sabre\\\\Auth->validateUserPass('user9', 'demo')\\n#18 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(126): Sabre\\\\DAV\\\\Auth\\\\Backend\\\\AbstractBasic->authenticate(Object(OC\\\\Connector\\\\Sabre\\\\Server), 'ownCloud')\\n#19 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(106): OC\\\\Connector\\\\Sabre\\\\Auth->auth(Object(OC\\\\Connector\\\\Sabre\\\\Server), 'ownCloud')\\n#20 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php(118): OC\\\\Connector\\\\Sabre\\\\Auth->authenticate(Object(OC\\\\Connector\\\\Sabre\\\\Server), 'ownCloud')\\n#21 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#22 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#23 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(456): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#24 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#25 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(71): Sabre\\\\DAV\\\\Server->exec()\\n#26 \\\/var\\\/www\\\/html\\\/owncloud\\\/remote.php(58): require_once('\\\/var\\\/www\\\/html\\\/o...')\\n#27 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractMySQLDriver.php\",\"Line\":115}","level":4,"time":"2015-03-25T10:23:01+00:00"}

```

Other issues from a different run:

(Note: do we want to remove the "go away" part of the error message?)

```

{"reqId":"2ETSi3j1EpTXi1H21sNR","remoteAddr":"x.x.x.x","app":"webdav","message":"Exception: {\"Message\":\"File entry exists when inserting and does not exist on select... go away\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/files_sharing\\\/lib\\\/cache.php(186): OC\\\\Files\\\\Cache\\\\Cache->put('files\\\/localShar...', Array)\\n#1 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/files\\\/cache\\\/scanner.php(199): OC\\\\Files\\\\Cache\\\\Shared_Cache->put('TEST_FILE_NEW_U...', Array)\\n#2 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/files\\\/cache\\\/scanner.php(165): OC\\\\Files\\\\Cache\\\\Scanner->addToCache('TEST_FILE_NEW_U...', Array, -1)\\n#3 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/files\\\/cache\\\/scanner.php(310): OC\\\\Files\\\\Cache\\\\Scanner->scanFile('TEST_FILE_NEW_U...', 3, 3022, NULL)\\n#4 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/files\\\/cache\\\/scanner.php(237): OC\\\\Files\\\\Cache\\\\Scanner->scanChildren('', false, 3, Array)\\n#5 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/files\\\/cache\\\/watcher.php(76): OC\\\\Files\\\\Cache\\\\Scanner->scan('', false)\\n#6 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/files_sharing\\\/lib\\\/watcher.php(37): OC\\\\Files\\\\Cache\\\\Watcher->checkUpdate('', Array)\\n#7 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php(1101): OC\\\\Files\\\\Cache\\\\Shared_Watcher->checkUpdate('', Array)\\n#8 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/files\\\/filesystem.php(795): OC\\\\Files\\\\View->getFileInfo('\\\/localShareDir', true)\\n#9 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/files_sharing\\\/lib\\\/helper.php(184): OC\\\\Files\\\\Filesystem::getFileInfo('\\\/localShareDir')\\n#10 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/files_sharing\\\/lib\\\/sharedstorage.php(304): OCA\\\\Files_Sharing\\\\Helper::getUidAndFilename('\\\/localShareDir')\\n#11 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/wrapper.php(246): OC\\\\Files\\\\Storage\\\\Shared->rename('TEST_FILE_NEW_U...', 'TEST_FILE_NEW_U...')\\n#12 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php(612): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->rename('TEST_FILE_NEW_U...', 'TEST_FILE_NEW_U...')\\n#13 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/file.php(285): OC\\\\Files\\\\View->rename('\\\/localShareDir\\\/...', '\\\/localShareDir\\\/...')\\n#14 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/file.php(74): OC\\\\Connector\\\\Sabre\\\\File->createFileChunked(Resource id #30)\\n#15 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/directory.php(92): OC\\\\Connector\\\\Sabre\\\\File->put(Resource id #30)\\n#16 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1053): OC\\\\Connector\\\\Sabre\\\\Directory->createFile('TEST_FILE_NEW_U...', Resource id #30)\\n#17 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(513): Sabre\\\\DAV\\\\Server->createFile('localShareDir\\\/T...', Resource id #30, NULL)\\n#18 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#19 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#20 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(469): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#21 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#22 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(71): Sabre\\\\DAV\\\\Server->exec()\\n#23 \\\/var\\\/www\\\/html\\\/owncloud\\\/remote.php(58): require_once('\\\/var\\\/www\\\/html\\\/o...')\\n#24 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/files\\\/cache\\\/cache.php\",\"Line\":264}","level":4,"time":"2015-03-25T09:48:40+00:00"}
{"reqId":"lM1oiUOVJSj\/iXrN5141","remoteAddr":"x.x.x.x","app":"webdav","message":"Exception: {\"Message\":\"File entry exists when inserting and does not exist on select... go away\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/files_sharing\\\/lib\\\/cache.php(186): OC\\\\Files\\\\Cache\\\\Cache->put('files\\\/localShar...', Array)\\n#1 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/files\\\/cache\\\/scanner.php(199): OC\\\\Files\\\\Cache\\\\Shared_Cache->put('TEST_FILE_NEW_U...', Array)\\n#2 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/files\\\/cache\\\/scanner.php(165): OC\\\\Files\\\\Cache\\\\Scanner->addToCache('TEST_FILE_NEW_U...', Array, -1)\\n#3 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/files\\\/cache\\\/scanner.php(310): OC\\\\Files\\\\Cache\\\\Scanner->scanFile('TEST_FILE_NEW_U...', 3, 3021, NULL)\\n#4 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/files\\\/cache\\\/scanner.php(237): OC\\\\Files\\\\Cache\\\\Scanner->scanChildren('', false, 3, Array)\\n#5 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/files\\\/cache\\\/watcher.php(76): OC\\\\Files\\\\Cache\\\\Scanner->scan('', false)\\n#6 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/files_sharing\\\/lib\\\/watcher.php(37): OC\\\\Files\\\\Cache\\\\Watcher->checkUpdate('', Array)\\n#7 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php(1101): OC\\\\Files\\\\Cache\\\\Shared_Watcher->checkUpdate('', Array)\\n#8 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/objecttree.php(123): OC\\\\Files\\\\View->getFileInfo('localShareDir')\\n#9 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Tree.php(103): OC\\\\Connector\\\\Sabre\\\\ObjectTree->getNodeForPath('localShareDir')\\n#10 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(494): Sabre\\\\DAV\\\\Tree->nodeExists('localShareDir\\\/T...')\\n#11 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#12 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#13 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(469): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#14 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#15 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(71): Sabre\\\\DAV\\\\Server->exec()\\n#16 \\\/var\\\/www\\\/html\\\/owncloud\\\/remote.php(58): require_once('\\\/var\\\/www\\\/html\\\/o...')\\n#17 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/files\\\/cache\\\/cache.php\",\"Line\":264}","level":4,"time":"2015-03-25T09:49:11+00:00"}

**Comment by stormsh** [comment]
Hi, I'm running oc 8.0.2 updated from 8.0 which was a fresh install on a new server, ubuntu linux 14.04 root with php 5.5.9, mysql db and plesk 12. OC is no plesk module (don't know if there is one).

I get some similar entries:
Only these two vary.
551436c5a526d
551436c5a52b0

The rest is the same.

<pre><code>
DB Error: "An exception occurred while executing 'INSERT INTO `oc_filecache` (`mimepart`,`mimetype`,`mtime`,`size`,`etag`,`storage_mtime`,`permissions`,`path_hash`,`path`,`parent`,`name`,`storage`) SELECT ?,?,?,?,?,?,?,?,?,?,?,? FROM `oc_filecache` WHERE `mimepart` = ? AND `mimetype` = ? AND `mtime` = ? AND `size` = ? AND `etag` = ? AND `storage_mtime` = ? AND `permissions` = ? AND `path_hash` = ? AND `path` = ? AND `parent` = ? AND `name` = ? AND `storage` = ? HAVING COUNT(*) = 0' with params ["1", "2", "1427388101", "-1", "551436c5a52b0", "1427388101", "31", "3b8779ba05b8f0aed49650f3ff8beb4b", "thumbnails", "6411", "thumbnails", "12", "1", "2", "1427388101", "-1", "551436c5a52b0", "1427388101", "31", "3b8779ba05b8f0aed49650f3ff8beb4b", "thumbnails", "6411", "thumbnails", "12"]: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '12-3b8779ba05b8f0aed49650f3ff8beb4b' for key 'fs_storage_path_hash'"<br />Offending command was: INSERT INTO `*PREFIX*filecache` (`mimepart`,`mimetype`,`mtime`,`size`,`etag`,`storage_mtime`,`permissions`,`path_hash`,`path`,`parent`,`name`,`storage`) SELECT ?,?,?,?,?,?,?,?,?,?,?,? FROM `*PREFIX*filecache` WHERE `mimepart` = ? AND `mimetype` = ? AND `mtime` = ? AND `size` = ? AND `etag` = ? AND `storage_mtime` = ? AND `permissions` = ? AND `path_hash` = ? AND `path` = ? AND `parent` = ? AND `name` = ? AND `storage` = ? HAVING COUNT(*) = 0<br /> 
DB Error: "An exception occurred while executing 'INSERT INTO `oc_filecache` (`mimepart`,`mimetype`,`mtime`,`size`,`etag`,`storage_mtime`,`permissions`,`path_hash`,`path`,`parent`,`name`,`storage`) SELECT ?,?,?,?,?,?,?,?,?,?,?,? FROM `oc_filecache` WHERE `mimepart` = ? AND `mimetype` = ? AND `mtime` = ? AND `size` = ? AND `etag` = ? AND `storage_mtime` = ? AND `permissions` = ? AND `path_hash` = ? AND `path` = ? AND `parent` = ? AND `name` = ? AND `storage` = ? HAVING COUNT(*) = 0' with params ["1", "2", "1427388101", "-1", "551436c5a526d", "1427388101", "31", "3b8779ba05b8f0aed49650f3ff8beb4b", "thumbnails", "6411", "thumbnails", "12", "1", "2", "1427388101", "-1", "551436c5a526d", "1427388101", "31", "3b8779ba05b8f0aed49650f3ff8beb4b", "thumbnails", "6411", "thumbnails", "12"]: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '12-3b8779ba05b8f0aed49650f3ff8beb4b' for key 'fs_storage_path_hash'"<br />Offending command was: INSERT INTO `*PREFIX*filecache` (`mimepart`,`mimetype`,`mtime`,`size`,`etag`,`storage_mtime`,`permissions`,`path_hash`,`path`,`parent`,`name`,`storage`) SELECT ?,?,?,?,?,?,?,?,?,?,?,? FROM `*PREFIX*filecache` WHERE `mimepart` = ? AND `mimetype` = ? AND `mtime` = ? AND `size` = ? AND `etag` = ? AND `storage_mtime` = ? AND `permissions` = ? AND `path_hash` = ? AND `path` = ? AND `parent` = ? AND `name` = ? AND `storage` = ? HAVING COUNT(*) = 0<br /></code></pre>

Does it have something to do with this?

st.

**Comment by cdamken** [comment]
@PVince81 I think the errors in https://github.com/owncloud/mirall/issues/2579 are the 

I saw in the log:
S3-ownCloud\Shared\owncloud\support\github-issues\mirall\2579\New Info\owncloud_20150424.log

```
{"app":"hook","message":"error while running hook (OC\\Preview::post_write): An exception occurred while executing 'INSERT INTO `oc_filecache` (`mimepart`, `mimetype`, `mtime`, `size`, `etag`, `storage_mtime`, `parent`, `path_hash`, `path`, `name`, `storage`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)':\n\nSQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '31-3e2773c9debcb282150e482962d87146' for key 'fs_storage_path_hash'","level":3,"time":"2015-04-24T15:54:37+09:00"}
```

**Comment by DeepDiver1975** [comment]
@cdamken what version is in place? Issue will be fixed with 8.0.3 and 8.1

**Comment by DeepDiver1975** [comment]
closing this issue as we fixed this in 8.0.3 and 8.1

**Comment by cdamken** [comment]
###  Thanks guys!

**Comment by christopheg** [comment]
I got this issue when running 8.0.2. Since last week, we are running 8.0.3 but the problems are not fixed:
An exception occurred while executing 'INSERT INTO `filecache` (`mimepart`,`mimetype`,`mtime`,`size`,`etag`,`storage_mtime`,`permissions`,`parent`,`path_hash`,`path`,`name`,`storage`) SELECT ?,?,?,?,?,?,?,?,?,?,?,? FROM `filecache` WHERE `storage` = ? AND `path_hash` = ? HAVING COUNT(*) = 0' with params ["5", "8", "1431281527", "2424", "2ccd51e54a69a231ca766656f95f22f1", "1431281527", "27", "584463", "a1f8aec10116fb6b1d69e33c406f364d", "files\/Documenten\/LOGOPEDIE\/prenten\/PCS kleur en zwart-wit\/PCS Nederlands\/Kleur\/w\/waar.WMF", "waar.WMF", "37", "37", "a1f8aec10116fb6b1d69e33c406f364d"]: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '37-a1f8aec10116fb6b1d69e33c406f364d' for key 'fs_storage_path_hash'	

Is this the same problem?

**Comment by nicknameforgithub** [comment]
This problem is still NOT solved even in the last 8.1 owncloud when using InnoDB
I solved this problem by changing engine type for oc_filecache table to MyISAM

**Comment by kevinkk525** [comment]
I still get this error in 8.1 (or maybe it is a different one?):
{"reqId":"VbthtVXW5hQAABmwVsQAAAAA","remoteAddr":"188.98.244.93","app":"webdav","message":"Exception: {\"Message\":\"An exception occurred while executing 'INSERT INTO `oc_filecache` (`mimepart`,`mimetype`,`mtime`,`size`,`etag`,`storage_mtime`,`permissions`,`encrypted`,`parent`,`path_hash`,`path`,`name`,`storage`) SELECT ?,?,?,?,?,?,?,?,?,?,?,?,? FROM `oc_filecache` WHERE `storage` = ? AND `path_hash` = ? HAVING COUNT(*) = 0' with params [\\\"5\\\", \\\"6\\\", 1438343607, 39431, \\\"654b38123a9f7eaef5bc5208496b434f\\\", 1438343607, 27, 1, \\\"32111\\\", \\\"e4ce47d9a73e49e9d74990d1c4a3a7fc\\\", \\\"files\\\\\\\/Sync\\\\\\\/photos\\\\\\\/nachdenken.jpg\\\", \\\"nachdenken.jpg\\\", \\\"1\\\", \\\"1\\\", \\\"e4ce47d9a73e49e9d74990d1c4a3a7fc\\\"]:\\n\\nSQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1-e4ce47d9a73e49e9d74990d1c4a3a7fc' for key 'fs_storage_path_hash'\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(116): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/var\\\/www\\\3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(996): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'INSERT INTO `oc...', Array)\\n#2 \\\/var\\\/www\\\/lib\\\/private\\\/db\\\/connection.php(151): Doctrine\\\\DBAL\\\\Connection->executeUpdate('INSERT INTO `oc...', Array, Array)\\n#3 \\\/var\\\/www\\\/lib\\\/private\\\/db\\\/adapter.php(93): OC\\\\DB\\\\Connection->executeUpdate('INSERT INTO `*P...', Array)\\n#4 \\\/var\\\/www/lib\\\/private\\\/db\\\/connection.php(190): OC\\\\DB\\\\Adapter->insertIfNotExist('*PREFIX*filecac...', Array, Array)\\n#5 \\\/var\\\/www\\\/lib\\\/private\\\/files\\\/cache\\\/cache.php(322): OC\\\\DB\\\\Connection->insertIfNotExist('*PREFIX*filecac...', Array, Array)\\n#6 \\\/var\\\/www\\\/lib\\\/private\\\/files\\\/cache\\\/scanner.php(225): OC\\\\Files\\\\Cache\\\\Cache->put('files\\\/Sync\\\/phot...', Array)\\n#7 \\\/var\\\/www\\\/lib\\\/private\\\/files\\\/cache\\\/scanner.php(188): OC\\\\Files\\\\Cache\\\\Scanner->addToCache('files\\\/Sync\\\/phot...', Array, -1)\\n#8 \\\/var\\\/www\\\/lib\\\/private\\\/connector\\\/sabre\\\/file.php(208): OC\\\\Files\\\\Cache\\\\Scanner->scanFile('files\\\/Sync\\\/phot...')\\n#9 \\\/var\\\/www\\\\/lib\\\/private\\\/connector\\\/sabre\\\/directory.php(113): OC\\\\Connector\\\\Sabre\\\\File->put(Resource id #42)\\n#10 \\\/var\\\/www\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1053): OC\\\\Connector\\\\Sabre\\\\Directory->createFile('nachdenken.jpg', Resource id #42)\\n#11 \\\/var\\\/www\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(513): Sabre\\\\DAV\\\\Server->createFile('Sync\\\/photos\\\/nac...', Resource id #42, NULL)\\n#12 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#13 \\\/var\\\/www\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#14 \\\/var\\\/www\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(469): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#15 \\\/var\\\/www\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#16 \\\/var\\\/www\\\/apps\\\/files\\\/appinfo\\\/remote.php(83): Sabre\\\\DAV\\\\Server->exec()\\n#17 \\\/var\\\/www\\\/remote.php(132): require_once('\\\/var\\\/www\\\/vhosts...')\\n#18 {main}\",\"File\":\"\\\/var\\\/www\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractMySQLDriver.php\",\"Line\":66}","level":4,"time":"2015-07-31T11:53:28+00:00"}

**Comment by obsidiannonparity** [comment]
I concur with kevinkk525 this issue is still ongoing. I have a fresh install and it is having the same error in the logs.

**Comment by nickvergessen** [comment]
Can you please check what your transaction isolation level is? It should be set to READ_COMMITED

**Comment by keithf4** [comment]
Having this issue regularly on OC 8.1.1 with PostgreSQL 9.4.4 backend (sanitized path name with "path_to_gitrepo"). 
`
error while running hook (OCA\Files_Versions\Hooks::write_hook): An exception occurred while executing 'INSERT INTO "oc_filecache" ("mimepart","mimetype","mtime","size","etag","storage_mtime","permissions","parent","path_hash","path","name","storage") SELECT ?,?,?,?,?,?,?,?,?,?,?,? FROM "oc_filecache" WHERE "storage" = ? AND "path_hash" = ? HAVING COUNT(*) = 0' with params [1, 2, 1441840501, -1, "55f0bd75f2e9b", 1441840501, 31, 29033, "ba4fb7ca27247c1444e7e74dd7f38486", "files_versions\/path_to_gitrepo\/.git\/logs", "logs", 1, 1, "ba4fb7ca27247c1444e7e74dd7f38486"]: SQLSTATE[23505]: Unique violation: 7 ERROR: duplicate key value violates unique constraint "fs_storage_path_hash" DETAIL: Key (storage, path_hash)=(1, ba4fb7ca27247c1444e7e74dd7f38486) already exists.
`

**Comment by RealRancor** [comment]
@nickvergessen 

Transaction isolation on InnoDB of MySQL is "REPEATABLE-READ" as a default:

https://dev.mysql.com/doc/refman/5.6/en/set-transaction.html

The same is valid for MariaDB 10.0.x packages from https://downloads.mariadb.org/:

```
MariaDB [(none)]> SELECT @@GLOBAL.tx_isolation, @@tx_isolation;
+-----------------------+-----------------+
| @@GLOBAL.tx_isolation | @@tx_isolation  |
+-----------------------+-----------------+
| REPEATABLE-READ       | REPEATABLE-READ |
+-----------------------+-----------------+
1 row in set (0.22 sec)
```

**Comment by aacebedo** [comment]
I am affected by the same bug with 8.1.3.

**Comment by pandur2000** [comment]
Same here with 8.1.3 -> 
@@GLOBAL.tx_isolation	@@tx_isolation = REPEATABLE-READ

**Comment by michalmiddleton** [comment]
Affected on a fresh install of 8.2.2
MariaDB (10.0.22) also set to REPEATABLE-READ

**Comment by keithf4** [comment]
Still seeing this on 8.2.2
```
keith=# select current_setting('transaction_isolation');
 current_setting 
-----------------
 read committed
```

**Comment by PVince81** [comment]
@michaelstingl @keithf4 please provide the full exception.

Since 8.2.2 there's transactional file locking enabled by default which should prevent such error to happen. If you still see it, the full exception might tell us whether it's exactly the same or whether it's happening in a different place.

**Comment by michaelstingl** [comment]
@PVince81 I have nothing to contribute in this issue.

**Comment by PVince81** [comment]
@michaelstingl sorry, autocomplete got you :frowning: 

I meant @michalmiddleton

**Comment by michalmiddleton** [comment]
@PVince81 I am almost certain that the issue went away after I enabled transnational file locking (via Redis).  Either way, I am running 9.0.1 and I am not seeing this log entry anymore. 
Thanks for the follow up!

**Comment by keithf4** [comment]
I've not seen this error in my logs since I last reset them which was for the 8.2.3 update in March. I am doing Redis caching as well.
I haven't done the 9.0 update yet but it's in my todo list for the near future.

**Comment by PVince81** [comment]
Closing then, thanks for the feedback
