### ISSUE TITLE
App icons on app manager is seen twice

### ISSUE THREAD

**Issue by vgezer** [owncloud/core#13955]
With the latest git-master, if you have appstore enabled and also have the same app in "apps" folder, the icons are seen twice. For example news app:

![image](https://cloud.githubusercontent.com/assets/231068/6067623/51fad2a4-ad76-11e4-9d8e-766ad65114f5.png)

Also see @cosenal's screenshot here: https://github.com/owncloud/news/issues/721#issuecomment-73270122

**Comment by karlitschek** [comment]
@jancborchardt

**Comment by DeepDiver1975** [comment]
Experienced this once as well having appstore enabled and news clones from git

**Comment by DeepDiver1975** [comment]
medium criticality because people either install from git or from appstore - still needs to be fixed

**Comment by cosenal** [comment]
There is more to it, actually. The two entries have the same id. One consequence is that I cannot enable (or disable) one app without enabling (disabling, respectively) the other one too.

**Comment by jancborchardt** [comment]
The double icon is definitely only a symptom here. Nothing I can do with design fixes.

**Comment by karlitschek** [comment]
@LukasReschke isn´t this fixed with the latest appstore fixes?

**Comment by cosenal** [comment]
@karlitschek are those appstore fixes already up? I can still reproduce this issue with latest core master

**Comment by LukasReschke** [comment]
That is an issue that is currently not fixed. But I second @DeepDiver1975 here, rather low severity for the moment.

**Comment by DeepDiver1975** [comment]
I consider this as won't fix for now - only happens in dev environments -> close
