### ISSUE TITLE
Add ability to disable HSTS completely

### ISSUE THREAD

**Issue by exploide** [owncloud/core#14073]
This is a duplicate of #11909 but since this issue is already closed, I need to open a new one.

I'm currently on ownCloud 8.0.0.7 and my apache is already delivering an HSTS header. Unfortunately ownCloud adds an additional max-age=0 property to the HSTS header. Even when SSL settings are disabled on ownCloud's administration page.

This leads to an invalid HSTS header like `Strict-Transport-Security:	max-age=31536000; includeSubDomains, max-age=0` and Firefox is complaining about it.

It would be nice if there were an option to tell ownCloud to not touch existing HSTS headers (or send them at all).

**Comment by MorrisJobke** [comment]
cc @LukasReschke

**Comment by Xenopathic** [comment]
Agreed - I've been hit by this issue as well. As a workaround, it is possible to set `forcessl` to true in `config.php`, but that still doesn't help with the compounded invalid headers, so you'll still need to disable the header sent by Apache.

**Comment by LukasReschke** [comment]
I'm not yet sure how to solve this best but I understand the reasoning behind this. I even thought about moving some security headers completely out of the code and deploy them via `.htaccess` and some hint in our documentation.

Let me think more about this.

**Comment by Sugaroverdose** [comment]
From my point of view, it's better to notice admin about HSTS header, but not force any form of it.

**Comment by GitHubGeek** [comment]
I can confirm that Firefox doesn't like HSTS headers from ownCloud 7.0.4 either.

IMHO there should be 2 levels of HSTS control, similar to the Cron config options: 

1. ownCloud generates HSTS headers (a la webcron)
  - Enforce = On
  - Enforce = Off
1. Web server takes care of things. ownCloud does not emit any HSTS header (a la system cron)

**Comment by Xenopathic** [comment]
I agree with @Sugaroverdose - ownCloud shouldn't write an HSTS header at all, that's the webserver's responsibility. A `.htaccess` would be a nice middleground, providing sensible defaults for the inexperienced but allowing easy modification.

**Comment by LukasReschke** [comment]
Convinced. – Let's tackle this.

**Comment by rockihack** [comment]
@Xenopathic +1 for it's the webserver's responsibility.

**Comment by tmo-github** [comment]
I was about to report the same issue, which I ran into in a different scenario: Owncloud (7.0.4 in my case) is running behind a reverse proxy which is taking care of handling HTTPS, and redirecting to the webserver (nginx) running on HTTP. I wanted to configure the handling of the 'Strict-Transport-Security' header at webserver level, but Owncloud messes things up, and the final HTTP header output was:
Strict-Transport-Security: max-age=0, max-age=31536000
I add my vote for a resolution of this issue, giving more flexibility to allow handling it at webserver level.

**Comment by LukasReschke** [comment]
Guys, you already convinced me and I added milestone to tackle this for 8.1 ;-)

**Comment by LukasReschke** [comment]
Please review https://github.com/owncloud/core/pull/13455 – that should do what you all want ;-)

**Comment by MorrisJobke** [comment]
Fixed with #14651

**Comment by fschwan** [comment]
This is still an issue for nginx.
In lib/private/response.php:
```
// Send fallback headers for installations that don't have the possibility to send
                // custom headers on the webserver side
                if(getenv('modHeadersAvailable') !== 'true') {
                        header('X-XSS-Protection: 1; mode=block'); // Enforce browser based XSS filters
                        header('X-Content-Type-Options: nosniff'); // Disable sniffing the content type for IE
                        header('X-Frame-Options: Sameorigin'); // Disallow iFraming from other domains
                        header('X-Robots-Tag: none'); // https://developers.google.com/webmasters/control-crawl-index/docs/robots_meta_tag
                }
```

modHeadersAvailable is false for nginx, but nginx is able to set those headers. Result: Headers are set twice and e.g. chromium is not able to parse a header like

```
X-XSS-Protection: 1; mode=block, 1; mode=block
```

though the XSS Protection is not applied.

Suggestion: Let the admin choose in the config if the webserver or nginx should set the headers.

**Comment by LukasReschke** [comment]
> modHeadersAvailable is false for nginx, but nginx is able to set those headers. Result: Headers are set twice and e.g. chromium is not able to parse a header like

https://doc.owncloud.org/server/8.1/admin_manual/installation/nginx_configuration.html

**Comment by LukasReschke** [comment]
Especially the `   fastcgi_param modHeadersAvailable true; #Avoid sending the security headers twice`.

**Comment by fschwan** [comment]
Thanks!
