### ISSUE TITLE
Can't update feeds - Error while running background job: Could not determine user

### ISSUE THREAD

**Issue by BlackLotus** [owncloud/core#14209]
I opened an issue about not being able to update my news feeds through the cron job here:
https://github.com/owncloud/news/issues/726

As this seems to be a core issue here again the error

```
 {"reqId":"xK0lTafpdUinjJQDpR80","remoteAddr":"","app":"no app in context","message":"Error while running background job: Could not determine user","level":3,"time":"2015-02-11T04:28:25+00:00","method":"--","url":"--"}
 {"reqId":"5YqxjlzYDXAlaJCzc4gk","remoteAddr":"","app":"no app in context","message":"Error while running background job: Could not determine user","level":3,"time":"2015-02-11T04:28:51+00:00","method":"--","url":"--"}
 {"reqId":"9oGGhYjaJMiC0LRBBlSx","remoteAddr":"92.51.203.86","app":"no app in context","message":"App is not enabled","level":0,"time":"2015-02-11T04:28:51+00:00","method":"GET","url":"\/index.php\/apps\/news\/feeds"}
 {"reqId":"tUGSG1Q85LqlJK5Z0ffG","remoteAddr":"92.51.203.86","app":"no app in context","message":"App is not enabled","level":0,"time":"2015-02-11T04:28:51+00:00","method":"GET","url":"\/index.php\/apps\/news\/folders"}
 {"reqId":"75kquKfwNPDELA3PYvTc","remoteAddr":"","app":"no app in context","message":"Error while running background job: Could not determine user","level":3,"time":"2015-02-11T04:29:11+00:00","method":"--","url":"--"}
```

**Comment by arjan-s** [comment]
I experienced this bug too, but it was solved by updating my News installation to the current master branch. So I think that means it'll be officially resolved with the next News app release.

**Comment by arjan-s** [comment]
Never mind... It worked just once after updating to master, but not anymore after that. :(

**Comment by TheReal1604** [comment]
Got this problem too.. additionally got this error:
 {"reqId":"a2b1ecf03ffb8bae9e78a6bf6b67d1c6","remoteAddr":"172.22.0.244","app":"index","message":"Exception: {\"Message\":\"Unable to generate a URL for the named route \\\"news.page.index\\\" as such     route does not exist.\",\"Code\":0,\"Trace\":\"#0     \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(282): Symfony\\\\Component\\\\Routing\\\\Generator\\\\UrlGenerator->generate('news.page.index', Array, false)\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/urlgenerator.php(42): OC\\\\Route\\\\Router->generate('news.page.index', Array)\\n#2 \\\/var\\\/www\\\/owncloud\\\/apps\\\/news\\\/config\\\/appconfig.php(109): OC\\\\URLGenerator->linkToRoute('news.page.index')\\n#3 \\\/var\\\/www\\\/owncloud\\\/apps\\\/news\\\/config\\\/appconfig.php(86): OCA\\\\News\\\\Config\\\\AppConfig->registerNavigation()\\n#4 \\\/var\\\/www\\\/owncloud\\\/apps\\\/news\\\/appinfo\\\/app.php(29): OCA\\\\News\\\\Config\\\\AppConfig->registerAll()\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/app.php(379): require('\\\/var\\\/www\\\/ownclo...')\\n#6 \\\/var\\\/www\\\/owncloud\\\/settings\\\/ajax\\\/navigationdetect.php(9): OC_App::getAppNavigationEntries('news')\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/route\\\/route.php(135) : runtime-created function(1): require_once('\\\/var\\\/www\\\/ownclo...')\\n#8 [internal function]: __lambda_func(Array)\\n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(250): call_user_func('\\\\x00lambda_65141', Array)\\n#10 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(763): OC\\\\Route\\\\Router->match('\\\/settings\\\/ajax\\\/...')\\n#11 \\\/var\\\/www\\\/owncloud\\\/index.php(36): OC::handleRequest()\\n#12 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/symfony\\\/routing\\\/Symfony\\\/Component\\\/Routing\\\/Generator\\\/UrlGenerator.php\",\"Line\":134}","level":4,"time":"2015-02-13T11:51:00+00:00","method":"GET","url":"\/owncloud\/index.php\/settings\/ajax\/navigationdetect.php?app=news"},{"reqId":"75a1bd9bdf7ab24d0c71af8c8e22f840","remoteAddr":"172.22.0.244","app":"news","message":"Configuration value \"simplePieCacheDuration\" does not exist. Ignored value.","level":2,"time":"2015-02-13T11:50:44+00:00","method":"GET","url":"\/owncloud\/index.php\/settings\/admin"}]

Opened an issue in owncloud/news too, but this issue is immediately closed..

Have reinstalled the news app.. copy the complete app + own cloud folder to my /var/www... nothing worked :(.

**Comment by arjan-s** [comment]
The first reported issue ("Error while running background job: Could not determine user") appears to be an issue with the combination of using the server-side encryption and the news app.
I've "fixed" that on my server by simply commenting the "throw" line in getUserFromPath() in apps/files_encryption/lib/helper.php, but that is a pretty bad way of doing it. I don't know if that has any other bad effects.

**Comment by TheReal1604** [comment]
Okay.. after restoring a snapshot from my old own cloud vm + mysql db and with a new update.. it now works better. the first error (route error) is now gone.. but the "Error while running background job: Could not determine user" still occurs. Hm.

**Comment by emtie** [comment]
Having the same issue

{"reqId":"8cd5020c8a15730b5c184e274ac431f3","remoteAddr":"","app":"no app in context","message":"Error while running background job: Could not determine user","level":3,"time":"2015-02-14T10:50:02+00:00"}

Installed owncloud again and addes latest news app. Then started the backgroundjob and it worked. After activating the encryption app the backgroundjob failed again....

**Comment by kosmoplovci** [comment]
arjan-s hack to apps/files_encryption/lib/helper.php indeed helps, when taht line is commented out feeds really update. is there anyone who knows what this really means and if this has some oter bad effects to files_encryption or something else in owncloud?

**Comment by TheReal1604** [comment]
Something new on this Issue? This issue is keeping me back from an upgrade to owncloud 8.0 :(. Little Showstopper.

**Comment by kosmoplovci** [comment]
it seems this issue is fixed in latest 8.0.0-7 version (official debian linux package), feeds are updating again.

**Comment by rauchc** [comment]
I don't see this issue fixed. Running on latest 8.0.0-9 version (official debian package), and I still get the error.

`Exception: {"Message":"Could not determine user","Code":10,"Trace":"#0 \/var\/www\/owncloud\/apps\/files_encryption\/lib\/helper.php(283): OCA\\Files_Encryption\\Helper::getUserFromPath('\/news\/config\/co...')`

**Comment by kosmoplovci** [comment]
hmm.. maybe i should stick with 8.0.0-7 for a while? ;)

**Comment by julienval** [comment]
I confirm I also encouter this issue with the up-to-date package 8.0.0-9 on Debian Wheezy.
Updates where running fine until I updated the News app yesterday (from a very old version...)

**Comment by kosmoplovci** [comment]
true, issue is not fixed yet, it was working for a few days while beeing on 8.0.0-7 but then it suddenly stopped, even before i upgraded to 8.0.0-9 (debian wheezy also). so feed updates definitelly not working normally yet...

**Comment by arjan-s** [comment]
Just tested: the hack is still needed on OC 8.0.2.

**Comment by hevtig** [comment]
Tested the hack on my OC 8.0.2 installation and it scrambled my notes and probably some of my files. I hope this issue will be fixed soon.

**Comment by plule** [comment]
I can confirm that disabling server side encryption allowed feeds to be updated here.

**Comment by TheReal1604** [comment]
Some news on this Bug? :/ 
Server side Encryption is necessary (for me..)

**Comment by pLum0** [comment]
Bug still existing in owncloud 8.0.3 :-(
Hack works, but don't really want to use it, when it's not sure what else it does.

**Comment by julienval** [comment]
After updating owncloud to 8.0.4, the updates still do not work. Even arjan-s' trick has no effect on this version.

**Comment by arjan-s** [comment]
Just confirmed that the bug still exists and my trick doesn't work anymore on ownCloud 8.0.4.
Please, can someone look at this issue?

**Comment by emtie** [comment]
Any news on this? I had to deactivate news app because encryption is absolutely necessary to me. The news app was one of the major things why I installed owncloud. Is there any more testing necessary or what is the problem here that this issue is open for 4 month now?

**Comment by julienval** [comment]
Not having any comments from someone part of the dev team is quite surprising.
I would also be happy to help in testing if this is needed. Unfortunately, I am not able to do more...

**Comment by Raydiation** [comment]
BTW: @emtie unless you are not using 3rdparty storage like amazon serverside encryption is useless. Everyone with access to your server can decrypt all of your files (see the encryption docs).

**Comment by arjan-s** [comment]
Has anyone tested this on ownCloud 8.1 yet? I'm still waiting with the upgrade until I have enough time to do a rollback if necessary.

**Comment by hevtig** [comment]
Seems to work for me now. It took some time and tries updating. After updating the first time I saw, that there is another encryption module now on owncloud 8.1. So I rolled back the update, decrypted all files, updated again, needed to download the current apps, encrypted again. After each activating the was an update process needed.
Seems to work now.
Still having errors in the logs, but they don't refer to the news app. Good luck.

**Comment by hevtig** [comment]
While the news app is running, the notes app isn't :(

**Comment by arjan-s** [comment]
Just wanted to confirm it works fine now after upgrading to ownCloud 8.1.1 and News 5.3.9. Didn't need to reencrypt everything, just doing the encryption migration was enough.

**Comment by PVince81** [comment]
Wasn't this fixed a while ago ? @schiesbn @BernhardPosselt

Please try again with 8.1.3

**Comment by PVince81** [comment]
I'm closing this now. If anyone is still having this issue with 8.1.4 or 8.2.0, feel free to reopen.
