### ISSUE TITLE
Debian package owncloud-apache-config creates duplicate config file

### ISSUE THREAD

**Issue by NHellFire** [owncloud/core#14610]
Every time I update owncloud, I get:
Setting up owncloud-config-apache (8.0.0-7) ...
 ```* Restarting web server apache2                                                                                                                                                 [Sat Feb 28 14:48:27 2015] [warn] The Alias directive in /etc/apache2/conf.d/owncloud.conf.old at line 1 will probably never match because it overlaps an earlier Alias.
 ... waiting ...........[Sat Feb 28 14:48:39 2015] [warn] The Alias directive in /etc/apache2/conf.d/owncloud.conf.old at line 1 will probably never match because it overlaps an earlier Alias.```

The problem is the [preinst script](https://build.opensuse.org/package/view_file/isv:ownCloud:community/owncloud/debian.owncloud-config-apache.preinst?expand=1).
This line:
```f=/etc/apache2/conf.d/owncloud.conf;         test -e $f && mv $f $f.old   || true```
Should be changed to:
```f=/etc/apache2/conf.d/owncloud.conf;         test -f $f && mv $f $f.old   || true```
So that it stops renaming the link and recreating it.

**Comment by LukasReschke** [comment]
@jnweiger

**Comment by fishcompany** [comment]
I second that. In addition no backup of the file /etc/apache2/conf-available/owncloud.conf is created even if local changes were made.

**Comment by SebastianS90** [comment]
@fishcompany local changes issue has been fixed, see https://github.com/owncloud/core/issues/14725#issuecomment-83166960

It remains to fix the preinst script (`test -f` instead of `test -e` such that an existing symlink is not moved)

**Comment by fishcompany** [comment]
Thank you @SebastianS90 for the information.
This bug still persists with version 8.0.2-5
@jnweiger please apply the fix mentioned in the bug description. Thanks.

**Comment by jnweiger** [comment]
Missed that one. 
Repackaged with fixed preinst. Look for version 8.0.2-8 or later...

**Comment by fishcompany** [comment]
I just installed v8.0.2-8. In my setup, the symlink in /etc/apache2/conf.d/ is still duplicated by the update:
Preparing to replace owncloud-config-apache 8.0.2-7 (using .../owncloud-config-apache_8.0.2-8_all.deb) ...
Leaving 'diversion of /etc/apache2/conf-available/owncloud.conf to /etc/apache2/conf-available/owncloud.conf.distrib by owncloud-config-apache'
Unpacking replacement owncloud-config-apache ...
Setting up owncloud-config-apache (8.0.2-8) ...
[....] Restarting web server: apache2[Thu Mar 26 07:37:50 2015] [warn] The Alias directive in /etc/apache2/conf.d/owncloud.conf.old at line 1 will probably never match because it overlaps an earlier Alias.
 ... waiting [Thu Mar 26 07:37:51 2015] [warn] The Alias directive in /etc/apache2/conf.d/owncloud.conf.old at line 1 will probably never match because it overlaps an earlier Alias.

**Comment by fishcompany** [comment]
Another way to check for a symbolic link that works on my system is to use
    test ! -L $f (instead of test ! -L $f)
I think the respective line should be (test for "exists an is no symbolic link")
    f=/etc/apache2/conf.d/owncloud.conf; test -e $f && test ! -L $f && mv $f $f.old || true

From the test manpage:
"Except for -h and  -L,  all  FILE-related  tests	 dereference  symbolic links."
Maybe this is the reason why the proposed fix does not work?

**Comment by NHellFire** [comment]
Actually, ! test and test ! are both correct. But you're correct that it
should be -L. I didn't realise -f would dereference

Another way to check for a symbolic link that works on my system is to use
test ! -L $f (instead of test ! -L $f)
I think the respective line should be (test for "exists an is no symbolic
link")
f=/etc/apache2/conf.d/owncloud.conf; test -e $f && test ! -L $f && mv $f
$f.old || true

From the test manpage:
"Except for -h and -L, all FILE-related tests dereference symbolic links."
Maybe this is the reason why the proposed fix does not work?

--
Reply to this email directly or view it on GitHub
<https://github.com/owncloud/core/issues/14610#issuecomment-86364764>.

**Comment by DavidPrevot** [comment]
FWIW: a2enconf is called twice in your version of debian/owncloud-config-apache.postinst

1. a2enconf owncloud || true
2. apache2_invoke enconf $CONF || exit $?

The verbatim copy from http://anonscm.debian.org/cgit/pkg-owncloud/owncloud.git/plain/debian/postinst already ensures to enable the configuration (and makes it work in both 2.2 or 2.4 version of apache2).

**Comment by ckujau** [comment]
Upgrading to 8.0.2-8 still has:

```
[...]
Setting up owncloud-config-apache (8.0.2-8) ...
Restarting web server: apache2[Mon Mar 30 07:39:52 2015] [warn] The Alias directive in /etc/apache2/conf.d/owncloud.conf.old at line 1 will probably never match because it overlaps an earlier Alias.
 ... waiting ....[Mon Mar 30 07:39:58 2015] [warn] The Alias directive in /etc/apache2/conf.d/owncloud.conf.old at line 1 will probably never match because it overlaps an earlier Alias.
.
Setting up owncloud (8.0.2-8) ...

$ ls -go /etc/apache2/conf.d/owncloud.conf*
lrwxrwxrwx. 1 31 Mar 30 07:39 /etc/apache2/conf.d/owncloud.conf -> ../conf-available/owncloud.conf
lrwxrwxrwx. 1 31 Mar 25 00:25 /etc/apache2/conf.d/owncloud.conf.old -> ../conf-available/owncloud.conf
```

**Comment by wolfgangkarall** [comment]
Hi,

this continues to be a nuisance, so I'd like to propose

a) move the file to /etc/owncloud/apache.conf as is custom with other packages and handle potential backups there (no "test for symlink" issues there, it's just a plain file), or rather, just make it a dpkg-handled config file there I guess

b) symlink that file to /etc/apache2/conf.d/owncloud.conf and /etc/apache2/conf-available/owncloud.conf (which is for the 2.4 packages, @ckujau, btw) depending on the existance of those directory, and use a2enconf if the latter exists.

Just take a look at e.g. phpmyadmin on Ubuntu trusty.
