### ISSUE TITLE
Setting a password using the OCS API makes shared links unusable.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#15777]
### Steps to reproduce

1. Share a folder by link.
2. Update the public share adding a password
    2.1. get the shares ids:

    ```
    curl -X GET http://USER:PASSWORD@OWNCLOUDPATH/ocs/v1.php/apps/files_sharing/api/v1/shares
    ```
   2.2. Add a password

   ```
   curl -v -X PUT -d password=sergio http://USER:PASSWORD@OWNCLOUDPATH/ocs/v1.php/apps/files_sharing/api/v1/shares/SHARE_ID
   ```

### Expected behaviour
A password is added to the shared link.

### Actual behaviour
Password is added, but you can't open the shared file/folder, the password is not recognized.

### Server configuration
**Operating system**:
Ubuntu 14.04 LTS

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"8.1.0.2","versionstring":"8.1 alpha 1","edition":""}

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**
None.

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** 
no

### Client configuration

**browser**
Chrome

**Comment by DeepDiver1975** [comment]
@rullzer isn't there some PR open by you in this area? Thanks a lot!

**Comment by rullzer** [comment]
Yes #14987 should have fixed this stuff.
Let me look into this later.

**Comment by PVince81** [comment]
Fixed by https://github.com/owncloud/core/pull/14987

**Comment by SergioBertolinSG** [comment]
Tested in 8.1alpha2, problem is still there. Password is not accepted.

**Comment by PVince81** [comment]
@SergioBertolinSG hmm is this the same problem ? The original problem was that changing the password would recreate a new link token.

From your comment it sounds like the token did not change (which is fixed) but now with the old token it doesn't accept the new password ?

**Comment by SergioBertolinSG** [comment]
@PVince81 Yes that is the current behaviour. The token problem was another issue.

**Comment by PVince81** [comment]
Thanks.
@rullzer can please you have a look ?

**Comment by rullzer** [comment]
Ah yes! Thanks for spotting!
I escaped to much apparently and extra ' are added. PR is on the way!

**Comment by rullzer** [comment]
PR in #15906
