### ISSUE TITLE
Anonymous access isn't allowed in the AD LDAP server, but wizard mark the configuration as ok

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#15982]
### Steps to reproduce
1. Setup a LDAP server without allowing anonymous access (checked with AD)
2. Configure the server tab of the LDAP wizard against the server with anonymous access (no username nor password, and the rest of the tab is ok)

### Expected behaviour
Since anonymous access isn't allowed in the server, the wizard should show an error, marking the configuration as wrong and preventing the user to keep configuring the server.

### Actual behaviour
Configuration is marked as ok and the user can keep configuring the server. Wizard will malfunction in this case.

The ldapsearch command shows the following output
```
ldapsearch -x -h <host> -b "cn=OC_User,cn=Users,DC=owncloud1,DC=com" "(&(objectClass=*))" dn
# extended LDIF
#
# LDAPv3
# base <cn=OC_User,cn=Users,DC=owncloud1,DC=com> with scope subtree
# filter: (&(objectClass=*))
# requesting: dn 
#

# search result
search: 2
result: 1 Operations error
text: 000004DC: LdapErr: DSID-0C0906E8, comment: In order to perform this ope
 ration a successful bind must be completed on the connection., data 0, v1db1

# numResponses: 1
```

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** OC 8.1 alpha 2

**Updated from an older ownCloud or fresh install:** fresh install

**Comment by jvillafanez** [comment]
@blizzz

**Comment by blizzz** [comment]
There several steps you could see and find out that something is wrong, but nothing gave you the right hint. This is now fixed in #16181

**Comment by rperezb** [comment]
as @jvillafanez commented, this is not fixed
https://github.com/owncloud/core/pull/16181#issuecomment-101160928
