### ISSUE TITLE
No way to differentiate between two files with the same name marked as favorites

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#16976]
### Steps to reproduce
1. Install 8.1 
2. Upload the same file in two different folders
3. Mark each file as a favorites
4. Go to the favorites page
### Expected behaviour

Should be able to see location of each file
### Actual behaviour

There is no way to tell where each favorite is stored

![p358](https://cloud.githubusercontent.com/assets/8480343/8190779/c1055110-1432-11e5-9636-04cd925c943e.PNG)
### Server Host info:

Ubuntu 14.04
PHP 5.5.9
### Server configuration:

ownCloud Enterprise Edition 8.1 beta 2 (daily) Build:2015-06-15T03:10:33+00:00 fe9b28a800514315eba17ac5da84b8b93abd9ffc

**Comment by PVince81** [comment]
This is more of a design issue. Tagging as such.

Might need adding a new column "Path" to show the original path.

@owncloud/designers

**Comment by stefan-niedermann** [comment]
What about adding the foldername in Brackets after the file-name in case of duplicate file-names? (light grey, just like extension)
pre_130.txt (Documents)
pre_130.txt (Another Folder)

**Comment by stefan-niedermann** [comment]
Or displaying the complete Path on Hover (Bad for mobile - but how often is this a problem that needs to be fixed directly on mobile?)

**Comment by jancborchardt** [comment]
On mobile we have little space anyway. I would say this is similar to the federated sharing tipsy tooltip – the full path should simply be shown on hover, above the filename like so:
`folder/subfolder/third-subfolder`
(no beginning slash, no end slash, and _do not_ duplicate the file name!)

**Comment by PVince81** [comment]
I thought we already had the tooltip, need to double check

**Comment by jancborchardt** [comment]
Only on the Favorites page though please. We don’t need it in the normal filelist.

**Comment by PVince81** [comment]
What about "Shared with you" and others ?

**Comment by jancborchardt** [comment]
Ah right, there too.

**Comment by jancborchardt** [comment]
But only in the root folder of course.

**Comment by cmonteroluque** [comment]
This issue will fall off 8.2 if not resolved by 6 Oct

**Comment by jancborchardt** [comment]
As far as I know this was solved by a tooltip? cc @PVince81 @owncloud/designers

**Comment by PVince81** [comment]
The tooltip wasn't implemented yet for other sections. Only the trashbin has one.

**Comment by SergioBertolinSG** [comment]
Hi, this is still a problem in 9.0.1. I think the full path of the file should appear somehow, another column, a button to open some hidden content with the path or whatever solution you came up with.

<img width="640" alt="screen shot 2016-04-05 at 09 44 18" src="https://cloud.githubusercontent.com/assets/9048796/14274787/b0bac830-fb13-11e5-8c07-b8585c22d146.png">

Also when downloading a file duplicated, the spinner button spins for both files, adding more confusion. The correct file is downloaded though.

**Comment by jancborchardt** [comment]
As said above, should happen via tooltip. No additional column as that will break layout.
