### ISSUE TITLE
Missing memcache class

### ISSUE THREAD

**Issue by sedrubal** [owncloud/core#17731]
### Steps to reproduce
1. install owncloud 8.1.0
2. install `redis-server`, `redis-client` and `php5-redis` / `php5-apcu`
3. configure memcache in owncloud config *(like I understood the documentation. See my config below.)*

**I think, I didn't really understand the documentation and so I miss configured the config.**

### Expected behaviour
Everything should work fine and owncloud should be as fast as never before ;)

### Actual behaviour
A blank page appears and there are errors in the error log

### Server configuration
**Operating system**: `Ubuntu 14.04.2`

**Web server:** `Apache/2.4.7 (Ubuntu)`

**Database:** `14.14 Distrib 5.5.43, for debian-linux-gnu (x86_64) using readline 6.3`

**PHP version:**

```
PHP 5.5.9-1ubuntu4.11 (cli) (built: Jul  2 2015 15:23:08) 
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies
```

**ownCloud version:** `8.1.0 (stable)`

**Updated from an older ownCloud or fresh install:** *manually updated*

**List of activated apps:**

```
Enabled:
 - activity: 2.0.1
 - files: 1.1.9
 - files_external: 0.2.3
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - files_videoviewer: 0.1.3
 - gallery: 0.6.0
 - templateeditor: 0.1
 - user_external: 0.4
Disabled:
 - encryption
 - external
 - files_locking
 - firstrunwizard
 - provisioning_api
 - updater
 - user_ldap
 - user_webdavauth
```

**The content of config/config.php:**

```php
  'asset-pipeline.enabled' => true,
  'activity_expire_days' => 365,
  //'memcache.local' => '\OC\Memcache\Redis',  // I also tried this -> same error
  'memcache.distributed' => '\OC\Memcache\Redis',  // I also tried apcu -> same error
  'memcache.locking' => '\OC\Memcache\Redis', // <- not sure, whether writing \ or \\. I found both.
  'redis' => array(
    'host' => '/var/run/redis/redis.sock', // can also be a unix domain socket: '/tmp/redis.sock'
    'timeout' => 0.0,
    'dbindex' => 0, // Optional, if undefined SELECT will not run and will use Redis Server's default DB Index.
  ),
 'memcached_servers' => array(
    // I don't understand this settings as I configured redis connection above
   // hostname, port and optional weight. Also see:
   // http://www.php.net/manual/en/memcached.addservers.php
    // http://www.php.net/manual/en/memcached.addserver.php
    array('localhost', 11211),
    //array('other.host.local', 11211),
  ),
```

**Are you using external storage, if yes which one:** dropbox

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** firefox

#### Web server error log
```
[<date>] [negotiation:error] [pid <id>] [client <ip>:<port>] AH00687: Negotiation: discovered file(s) matching request: <path>/owncloud/settings/admin (None could be negotiated)., referer: https://<url>/index.php/apps/files/
```

#### ownCloud log (data/owncloud.log)
```json
{"reqId":"<id>","remoteAddr":"<ip>","app":"PHP","message":"OC\\HintException: Missing memcache class \\OC\\Memcache\\Redis for distributed cache at <path>\/owncloud\/lib\/private\/memcache\/factory.php#81","level":3,"time":"2015-07-18T14:40:41+00:00"}
```

**Comment by sedrubal** [comment]
`lib/private/memcache/apcu.php` and `lib/private/memcache/redis.php` exist...

**Comment by RealRancor** [comment]
Hi,

php5-redis should fix that. Personally i think this is just an documentation issue which is already tracked here: https://github.com/owncloud/documentation/issues/1233

**Comment by sedrubal** [comment]
Thanks for the suggestion. I didn't have `php5-redis` installed, but now, after installing and enabling (`php5enmod redis`) it still doesn't work... (same errors).

**Comment by RealRancor** [comment]
See above:

> Redis 2.2.2 which also doesn't gets enabled

**Comment by brainlid** [comment]
I have the same issue. So what's the recommended solution/workaround? Install and use Memcached instead of Redis? Install and build newer redis and apcu from source?

**Comment by DeepDiver1975** [comment]
We require php Redis with min version 2.2.5 and APCu with min version 4.0.6 https://github.com/owncloud/core/blob/v8.1.0/lib/private/memcache/apcu.php#L35

If your distros don't serve these you might wana  try to upgrade or build from source.

**Comment by sedrubal** [comment]
Is it hard for you, to support the current redis version? Even ubuntu `14.04` uses redis `2.8.4`. And I think most run oc on ubuntu `14.04`

**Comment by henri-hulski** [comment]
@sedrubal: 2.8.4 > 2.2.5

**Comment by RealRancor** [comment]
@henri-hulski 
I thins thats probably just a typo as Ubuntu 14.04 is providing 2.4.8 and not 2.8.4: http://packages.ubuntu.com/trusty/php5-redis

@sedrubal 
I just had a look at the redis changelog and 2.2.5 fixes an crash:

https://raw.githubusercontent.com/antirez/redis/2.2/00-RELEASENOTES

so thats probably the reason why 2.2.4 is required. But maybe a developer can shed some light on this requirement.

**Comment by henri-hulski** [comment]
@RealRancor 
OK but 2.4.8 is also > 2.2.5

**Comment by henri-hulski** [comment]
Actually I have a similar proplem.
I want to enable Transactional File Locking, so I installed php-redis and redis-server on Debian Wheezy.

Versions:
PHP  5.4.41
Redis 2.8.17
Owncloud 8.1

Redis is enabled and I added to config/config.php:
``` php
  'filelocking.enabled' => 'true',
  'memcache.local' => '\OC\Memcache\Redis',
  'redis' => array(
    'host' => 'localhost', // can also be a unix domain socket: '/tmp/redis.sock'
    'port' => 6379,
    'timeout' => 0.0,
    'dbindex' => 0, // Optional, if undefined SELECT will not run and will use Redis Server's default DB Index.
  ),
```

When I try to launch owncloud I get:
```
File locking is enabled but the locking cache class was not found
Please check the "memcache.locking" setting and make sure the matching PHP module is installed and enabled
```

**Comment by RealRancor** [comment]
> OK but 2.4.8 is also > 2.2.5

Sorry, and now i had the typo. :see_no_evil: Its actually 2.2.4

> When I try to launch owncloud I get:

I think the message is telling you that you need to configure memcache.locking which seems to not be configured yet.

**Comment by henri-hulski** [comment]
Thanks.
Adding 
```php
'memcache.locking' => '\OC\Memcache\Redis',
```
fixed it.

I got the faulty code from https://doc.owncloud.org/server/8.1/admin_manual/configuration_files/files_locking_experimental.html.
In https://doc.owncloud.org/server/8.1/admin_manual/configuration_files/files_locking_transactional.html the code is fixed.

I think files_locking_experimental.htm should be fixed or removed from the web.

**Comment by RealRancor** [comment]
Ah, good to know. Have raised that in https://github.com/owncloud/documentation/issues/432. Unfortunately that happens quite often if a page gets renamed.

**Comment by roman2025** [comment]
http://anton.logvinenko.name/en/blog/how-to-install-redis-and-redis-php-client.html

If you are running ubuntu 14.04.X LTS - then the version of your PHP5-REDIS module installed from apt is 2.2.4.   The version of your REDIS server is like 2.8.4 but the issue is the PHP5 module.

So first you need to uninstall the PHP5-REDIS module:

php5dismod redis
apt-get remove php5-redis
-----
Then you can go here:
http://anton.logvinenko.name/en/blog/how-to-install-redis-and-redis-php-client.html

Scroll down the page until you find the section about building the PHP5 module from source. Section starts with:
"PhpRedis Installation
PhpRedis - PHP extension from Nicolas Favre-Felix, which allows to access to Redis from php...."

Follow the instructions for ubuntu. You might have to improvise a bit (my folder name was different).

Once you are done with that, you need to double check your owncloud config file. You should have the following:

'memcache.local' => '\\OC\\Memcache\\Redis',
'filelocking.enabled' => 'true',
'memcache.distributed' => '\\OC\\Memcache\\Redis',
'memcache.locking' => '\OC\Memcache\Redis',
'redis' => array(
       'host' => 'localhost',
       'port' => 6379,
       'timeout' => 0.0,
       'dbindex' => 0,
),


Restart apache and away you go... I am on Ubuntu 14.04.3 LTS and this was the only way I could get it working as you can't get a newer version of the PHP5-REDIS module without building from source.

**Comment by roman2025** [comment]
Also, you can create a php info file and use it to check which version of the redis module you are running. Once I was done with this, my version went from 2.2.4 --> 2.2.7

**Comment by roman2025** [comment]
I did a full write-up on how to get Redis cache + File locking working on Owncloud 8+ running on Ubuntu 14.04 here: http://www.kiloroot.com/a-guide-to-owncloud-8-ubuntu-14-04-and-caching-apcu-redis-cache-and-file-locking-oh-my/

Hopefully that is helpful for some folks as I included a lot more detail. I also wrote about how to setup APCu as that also can be a bit tricky on Ubuntu.

Cheers,

Roman

**Comment by Berndinox** [comment]
With HHVM latest + Ubuntu 14.04 it does not work:

i tried:
'''
'memcache.local' => '\OC\Memcache\Redis',
'filelocking.enabled' => 'true',
'memcache.distributed' => '\OC\Memcache\Redis',
'memcache.locking' => '\OC\Memcache\Redis',
'redis' => array(
'host' => 'localhost',
'port' => 6379,
'timeout' => 0.0,
'dbindex' => 0,
),
'''
blank screen!

and with:
// ''''memcache.local' => '\OC\Memcache\Redis',
'filelocking.enabled' => 'true',
// 'memcache.distributed' => '\OC\Memcache\Redis',
'memcache.locking' => '\OC\Memcache\Redis',
'redis' => array(
'host' => 'localhost',
'port' => 6379,
'timeout' => 0.0,
'dbindex' => 0,
),
'''
-> File locking is enabled but the locking cache class was not found

**Comment by RealRancor** [comment]
Hi,

this means you havn't enabled the PHP redis module or it is below the minimum requirement of 2.2.5 (This is the version of the PHP module, not of redis itself).

**Comment by Berndinox** [comment]
HHVM does load this Modul dynamicly. I habe an WordPress Blog Running in the same Stack, wehre redis object Cache does work probably. Br

**Comment by Berndinox** [comment]
UPDATE: Admin Panel says: "redis too old" but i have V 2.8.4 installed as you can See above.

**Comment by RealRancor** [comment]
@Berndinox See above: 

> or it is below the minimum requirement of 2.2.5 (This is the version of the PHP module, not of redis itself).

2.8.4 is the version of redis and not of the redis PHP module.

**Comment by psychok7** [comment]
this tutorial worked for me https://www.en0ch.se/how-to-configure-redis-cache-in-ubuntu-14-04-with-owncloud/

**Comment by laryllian** [comment]
Ok, but then at least please adjust the error message pointing out, that not the redis-server version is the problem, but the redis php module version.

It took me some time to figure out that the error message has that error. ;)

**Comment by RealRancor** [comment]
@laryllian https://github.com/owncloud/core/issues/new :-)

**Comment by danger89** [comment]
People with the same problem, check if you install redis-server and php5-redis. Be sure you are using php5-redis version 2.2.5 or newer:
```dpkg -s php5-redis```

When you are using PHP-fpm be sure you enabled redis. I'm using Debian 8 Jessie, so I looked here: /etc/php5/fpm/conf.d/20-redis.ini. It should say:
```
extension=redis.so     
```
When redis php module is installed & configured correctly, you need to restart php-fpm. service php5-fpm and I also restarted nginx to be sure. service nginx restart.

**Comment by laryllian** [comment]
@RealRancor https://github.com/owncloud/core/issues/21054
;)

**Comment by pierrejochem** [comment]
@psychok7 :+1:
