### ISSUE TITLE
How to manage ownCloud apps programaticaly - discussion

### ISSUE THREAD

**Issue by pierreozoux** [owncloud/core#17823]
What is the best way to maintain apps? Because I manage dozens of owncloud instance as an IndieHosters and this is a pain.

When I do upgrades, it deactivates apps from the users. Then they reactivate them, but they are broken, I need to find the latest version.

This is not scalable :/

Why isn't there any package management? Why not using composer? Do you have an idea to solve this issue? Actually, yesterday, speaking with a friend we though about git. Is master always 'bug free' not like a development branch I mean. Or maybe I can/should use the tags.

I'm just curious how to deal with that, if you have hints, I'd be glad!

Thanks!

**Comment by DeepDiver1975** [comment]
master is the development branch - released versions are available in stable branches like stable8 or stable8.1

**Comment by pierreozoux** [comment]
@DeepDiver1975 thanks for the quick reply, I guess this is the same for apps like contacts.

So maybe the best option is to rely on git + tags. but it needs my manual intervention to say ok, this tag works with this oC version.

**Comment by oparoz** [comment]
> master is the development branch - released versions are available in stable branches like stable8 or stable8.1

That's only true for core apps. The repository of each app should be checked.

@pierreozoux - Why should you update apps for your users? They are available in the app store now and admins can upgrade whenever they want. The latest version compatible with their ownCloud version will be pulled and installed.

**Comment by pierreozoux** [comment]
@oparoz compare, in term of UX, between ownCloud and Google.

On google:
 - If I want to use calendar, it is working. Do I need to update? What is an update?

On ownCloud:
 - I want calendar
 - hum, there is no calendar
 - ah, I have to activate it, good, it is now done!
 - ah? my nice hoster updated oC to the latest version (I don't understand why, but well...)
  - oh wtf? My calendar is now deactivated??
  - can I reactivate it? He is telling me to check the version number?? I'm lost?

Sorry for the dummy presentation, I'm sure you are already aware of that.
In the FLOSS community, if we want to compete with google, we have to at least offer a similar user experience. And people will choose us, not just because we are FLOSS, but because, that we offer key advantage that proprietary software in the cloud can't offer (privacy, integration between owncloud and wordpress for instance...).

I'm not saying oC is bad. Like framasoft is saying, "the road is long but the way is free :)". I'm just trying to understand how I can make the life as easy as possible for my users.

As an IndieHoster, the best would be:
 - ask `occ`: 'can I upgrade?' - occ will check every apps if it exists the compatible version with the core upgrade intended version
  - if no - ok, I'm fine, I keep that version of oC
  - if yes, I upgrade core, and after occ will download every new app version, compatible with the current core version, and of course re-enable them

I'm sure this is also your goal :)

In the mean time, if there is a nice way to deal with that, I'd be glad to know it :)

@oparoz: you are telling me that on the web ui, admins can upgrade their apps to the latest version? I tried to find it on the manual, I found nothing. I tried to look on the web ui, I found nothing. Maybe it will appear when a new version will be available? If you tell so, I trust you, and then in this case, I'll let users upgrade to the latest version (waiting `occ` be able to so by itself :)).

**Comment by oparoz** [comment]
I have the same problem. All apps are disabled and nothing will work until all apps are re-enabled, so it takes extra time to get everything back to normal. The way I see it, you either offer ownCloud fully managed, have full control over the upgrade process and don't leave your users stranded with disabled apps or you let users update at their own pace and let them manually re-install dozens of apps.
Things are improving though, but from what I remember, mainly for people who use the updater. If you use a 3rd party apps management tool, you probably won't get any information about the upgrade process.

If you've read http://morrisjobke.de/2015/07/23/Verbose-ownCloud-upgrade/ then you know that we can already upgrade ownCloud itself via the command line, so maybe you could create an issue asking specifically for 
* `occ apps:upgradeready`
* `occ apps:upgrade`

cc @MorrisJobke 

And about your 2nd point, yes, you can currently go to the apps section of your ownCloud and upgrade apps. One will only be shown if it's compatible with your version of ownCloud.
Regarding simply re-enabling apps, I would pick the apps from the various categories instead of using the ones in the "not enabled" category as you may have some older version in there.

**Comment by PVince81** [comment]
@Gomez did you also have similar trouble ?

**Comment by cdamken** [comment]
> occ apps:upgradeready
> occ apps:upgrade

I like this ;)

**Comment by Xenopathic** [comment]
See `./occ upgrade --no-app-disable` (#16473)

**Comment by oparoz** [comment]
Brilliant :)

**Comment by Gomez** [comment]
I depend on git + tags for core and all apps (if necessary i use bugfix commits). 
To get rid of the 3rdparty app disable i implemented ```./occ upgrade --no-app-disable```. Works perfect since than :)

**Comment by pierreozoux** [comment]
Ok, thanks for all your input!

I still get apps disabled (last update was calendar and contact), I found this way:
https://github.com/indiehosters/ownCloud/issues/3

I'll test further and let you know :)

**Comment by PVince81** [comment]
In the future, please discuss on the mailing list or forums http://owncloud.org/support

I'm closing this because this is neither a bug report not enhancement request.

There is already a ticket about apps getting disabled on updates: https://github.com/owncloud/core/issues/18312
