### ISSUE TITLE
Web Post Update 8.1.0 to 8.1.3 on Centos 7 fail

### ISSUE THREAD

**Issue by dariolesca** [owncloud/core#19588]
Updating ownCloud to version 8.1.3, this may take a while.

Turned on maintenance mode
Checked database schema update
Checked database schema update for apps
Updated database
Updated "files" to 1.1.10
Updated "activity" to 2.0.2

Symfony\Component\Routing\Exception\RouteNotFoundException: Unable to generate a URL for the named route "calendar_index" as such route does not exist.
The update was unsuccessful. Please report this issue to the ownCloud community.

From log "Fatal Update":
Exception: {"Exception":"Symfony\\Component\\Routing\\Exception\\RouteNotFoundException","Message":"Unable to generate a URL for the named route \"calendar_index\" as such route does not exist.","Code":0,"Trace":"#0 \/var\/www\/clients\/client1\/web1\/web\/lib\/private\/route\/router.php(306): Symfony\\Component\\Routing\\Generator\\UrlGenerator->generate('calendar_index', Array, false)\n#1 \/var\/www\/clients\/client1\/web1\/web\/lib\/private\/route\/cachingrouter.php(53): OC\\Route\\Router->generate('calendar_index', Array, false)\n#2 \/var\/www\/clients\/client1\/web1\/web\/lib\/private\/urlgenerator.php(65): OC\\Route\\CachingRouter->generate('calendar_index', Array)\n#3 \/var\/www\/clients\/client1\/web1\/web\/lib\/private\/helper.php(139): OC\\URLGenerator->linkToRoute('calendar_index', Array)\n#4 \/var\/www\/clients\/client1\/web1\/web\/lib\/public\/util.php(306): OC_Helper::linkToRoute('calendar_index', Array)\n#5 \/var\/www\/clients\/client1\/web1\/web\/apps\/calendar\/appinfo\/app.php(30): OCP\\Util::linkToRoute('calendar_index')\n#6 \/var\/www\/clients\/client1\/web1\/web\/lib\/private\/app.php(139): require_once('\/var\/www\/client...')\n#7 \/var\/www\/clients\/client1\/web1\/web\/lib\/private\/app.php(120): OC_App::requireAppFile('calendar')\n#8 \/var\/www\/clients\/client1\/web1\/web\/lib\/private\/app.php(1173): OC_App::loadApp('calendar', false)\n#9 \/var\/www\/clients\/client1\/web1\/web\/lib\/private\/installer.php(218): OC_App::updateApp('calendar')\n#10 \/var\/www\/clients\/client1\/web1\/web\/lib\/private\/installer.php(248): OC_Installer::updateApp(Array)\n#11 \/var\/www\/clients\/client1\/web1\/web\/lib\/private\/updater.php(487): OC_Installer::updateAppByOCSId('168707')\n#12 \/var\/www\/clients\/client1\/web1\/web\/lib\/private\/updater.php(308): OC\\Updater->upgradeAppStoreApps(Array)\n#13 \/var\/www\/clients\/client1\/web1\/web\/lib\/private\/updater.php(195): OC\\Updater->doUpgrade('8.1.3.0', '8.1.0.8')\n#14 \/var\/www\/clients\/client1\/web1\/web\/core\/ajax\/update.php(87): OC\\Updater->upgrade()\n#15 {main}","File":"\/var\/www\/clients\/client1\/web1\/web\/3rdparty\/symfony\/routing\/Symfony\/Component\/Routing\/Generator\/UrlGenerator.php","Line":134} 
From Log "Fatal 	index":
Exception: {"Exception":"OC\\NeedsUpdateException","Message":"","Code":0,"Trace":"#0 \/var\/www\/clients\/client1\/web1\/web\/lib\/private\/app.php(98): OC_App::loadApp('files')\n#1 \/var\/www\/clients\/client1\/web1\/web\/lib\/private\/util.php(127): OC_App::loadApps(Array)\n#2 \/var\/www\/clients\/client1\/web1\/web\/lib\/base.php(873): OC_Util::setupFS()\n#3 \/var\/www\/clients\/client1\/web1\/web\/index.php(40): OC::handleRequest()\n#4 {main}","File":"\/var\/www\/clients\/client1\/web1\/web\/lib\/private\/app.php","Line":118} 

I have update the page and redo update and update was end successful.

**Comment by Kawohl** [comment]
Please deactivate all apps before updating, then it should work flawlessly.

Anyways thanks for contributing! Can we kindly ask you to use the  issue template?
https://raw.githubusercontent.com/owncloud/core/master/issue_template.md

It makes it easier to track the problem and you will more likely receive help in a shorter period of time.

**Comment by RealRancor** [comment]
Dup of https://github.com/owncloud/core/issues/18317, https://github.com/owncloud/core/issues/18329, https://github.com/owncloud/core/issues/18296, https://github.com/owncloud/core/issues/18224 and many more...

Should be fixed with the next oC version according to: https://github.com/owncloud/core/issues/18224

**Comment by MorrisJobke** [comment]
> Should be fixed with the next oC version according to: #18224

#18839 was backported to 8.1.2. Weird that this is still an issue. @Xenopathic Any idea?

**Comment by RealRancor** [comment]
@MorrisJobke Ah, sorry. Mixed the issues. There is a still open issue here:

https://github.com/owncloud/core/issues/19145

where this was also happening during the update to 8.1.3.

**Comment by MorrisJobke** [comment]
Then it's a dup of #19145 -> closing
