### ISSUE TITLE
File name and sharee user name are overlapped

### ISSUE THREAD

**Issue by rperezb** [owncloud/core#19790]
### Steps to reproduce
1. Create a file whose name is quite long
   2.- Share it with a user whose user id is long too, "useruser@owncloud.com"
   3.- Access as "useruser@owncloud.com"
   4.- Click on share
### Expected behaviour

The file name is cut
### Actual behaviour

The file name and the user name is overlapped, see attached image
### Server configuration

**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"8.2.0.9","versionstring":"8.2 RC1","edition":"Enterprise"}

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**
Default in enterprise edition.

![screen shot 2015-10-13 at 11 28 17](https://cloud.githubusercontent.com/assets/1846927/10488590/a367f5e8-7299-11e5-9985-f125aada4aaf.png)

**Comment by rperezb** [comment]
cc @jancborchardt

**Comment by jancborchardt** [comment]
We have specific cut-offs of the filename width at certain screen-widths. I’d say the best solution here is to ellipsize the username when it gets too long since making it flexible would create more problems for longer usernames or narrower screens.

**Comment by edwardcrompton** [comment]
Hi there, I'm new to the ownCloud issue queue but I thought I'd see if I could help out with this.

I've created a PR here https://github.com/owncloud/core/pull/19873

As well as ellipsizing the username when it gets long, I think the filename cut off needs to be reduced slightly at at a range of screen widths. This I've done for a single screen size. Please let me know if I'm on the right track. If so, I can submit an updated pull request with the widths for other screen sizes. I can also test it on other browsers.

**Comment by ChristophWurst** [comment]
Fixed by https://github.com/owncloud/core/pull/21872

**Comment by SergioBertolinSG** [comment]
Still happening on current master.

![screen shot 2016-11-25 at 14 52 00](https://cloud.githubusercontent.com/assets/9048796/20627666/c79e3b2e-b321-11e6-8c8a-8dd9a4003af0.png)

**Comment by PVince81** [comment]
moved to general design / UX / styling issues group ticket: https://github.com/owncloud/core/issues/27578
