### ISSUE TITLE
LDAP 'UserMapper was not assigned to this Access instance'

### ISSUE THREAD

**Issue by Xenopathic** [owncloud/core#20151]
With the latest (29/10/2015) master, I'm seeing an error when ~~editing the raw LDAP filter on the Login Attributes section and~~ trying to verify a user on the Login Attributes panel: 'UserMapper was not assigned to this Access instance'. The following appears in the log:

```
{"reqId":"486hGY\/e1\/nKOpD7ry0+","remoteAddr":"10.248.41.23","app":"PHP","message":"Undefined index: displayname at \/srv\/git@robin\/owncloud\/core\/apps\/user_ldap\/lib\/access.php#696","level":3,"time":"2015-10-29T13:44:12+00:00"}
```

LDAP configuration:

```
+-------------------------------+--------------------------------------------+
| Configuration                 | s01                                        |
+-------------------------------+--------------------------------------------+
| hasMemberOfFilterSupport      |                                            |
| hasPagedResultSupport         |                                            |
| homeFolderNamingRule          |                                            |
| lastJpegPhotoLookup           | 0                                          |
| ldapAgentName                 |                                            |
| ldapAgentPassword             | ***                                        |
| ldapAttributesForGroupSearch  |                                            |
| ldapAttributesForUserSearch   |                                            |
| ldapBackupHost                |                                            |
| ldapBackupPort                |                                            |
| ldapBase                      | dc=mccorkell,dc=me,dc=uk                   |
| ldapBaseGroups                | ou=groups,dc=mccorkell,dc=me,dc=uk         |
| ldapBaseUsers                 | ou=users,dc=mccorkell,dc=me,dc=uk          |
| ldapCacheTTL                  | 600                                        |
| ldapConfigurationActive       | 1                                          |
| ldapEmailAttribute            |                                            |
| ldapExperiencedAdmin          | 0                                          |
| ldapExpertUUIDGroupAttr       | cn                                         |
| ldapExpertUUIDUserAttr        | uid                                        |
| ldapExpertUsernameAttr        |                                            |
| ldapGroupDisplayName          | cn                                         |
| ldapGroupFilter               | (&(|(objectclass=posixGroup)))             |
| ldapGroupFilterGroups         |                                            |
| ldapGroupFilterMode           | 0                                          |
| ldapGroupFilterObjectclass    | posixGroup                                 |
| ldapGroupMemberAssocAttr      | memberUid                                  |
| ldapHost                      | zeus.lan.mccorkell.me.uk                   |
| ldapIgnoreNamingRules         |                                            |
| ldapLoginFilter               | (&(|(objectClass=posixAccount))(uid=%uid)) |
| ldapLoginFilterAttributes     |                                            |
| ldapLoginFilterEmail          | 0                                          |
| ldapLoginFilterMode           | 1                                          |
| ldapLoginFilterUsername       | 1                                          |
| ldapNestedGroups              | 0                                          |
| ldapOverrideMainServer        |                                            |
| ldapPagingSize                | 500                                        |
| ldapPort                      | 389                                        |
| ldapQuotaAttribute            |                                            |
| ldapQuotaDefault              |                                            |
| ldapTLS                       | 0                                          |
| ldapUserDisplayName           | displayName                                |
| ldapUserFilter                | (|(objectclass=posixAccount))              |
| ldapUserFilterGroups          |                                            |
| ldapUserFilterMode            | 0                                          |
| ldapUserFilterObjectclass     | posixAccount                               |
| ldapUuidGroupAttribute        | auto                                       |
| ldapUuidUserAttribute         | auto                                       |
| turnOffCertCheck              | 0                                          |
| useMemberOfToDetectMembership | 1                                          |
+-------------------------------+--------------------------------------------+
```

cc @blizzz

**Comment by Xenopathic** [comment]
In addition, I don't know how relevant this is, but the wizard isn't picking up my users. The settings are correct, and it picks up groups just fine, but no users.

**Comment by blizzz** [comment]
Should be fixed with https://github.com/owncloud/core/pull/20124, confirm?

**Comment by blizzz** [comment]
Ah, i should read completely. The undefined index warning should be fixed with #20124. The error however…

**Comment by Xenopathic** [comment]
Well as you suspected, the log warning is gone with #20124, but the error remains...

**Comment by Xenopathic** [comment]
@blizzz I discovered why my users aren't being shown, for some reason the search query has `displayName=*` appended to it, even though it isn't configured anywhere (*and* the user display name attribute is set to `cn`, not `displayName`). Since my users don't have a `displayName`, ownCloud isn't seeing my users. Sounds like another bug?

**Comment by blizzz** [comment]
The benefit is that system accounts will be excluded, because they usually do not have a displayname while they share common objectclasses with human users.

What I believe happened with you is that: we do try to detect the display name **once**. We check for displayname first, then cn attribute. They somehow something happened that mixed it up. Would be interesting to know how/what exactly.

But you still have the error appearing? About the not-set user mapper?

**Comment by Xenopathic** [comment]
Yes, I'm still getting the error with the UserMapper.

**Comment by blizzz** [comment]
Reproduced and I think I know what's happening. When testing for the loginname, users are being fetched (obviously) and since we would read other attributes the result is always send to batchApplyUserAttributes which requires mapping, which we don't have (and need) while setting up the configuration.

I am thinking either to check in fetchListOfUsers() whether a mapper is set  before calling that method, or catching the Exception. But later requires to change the Exception away from a generic, code-less one, to really go after the missing mapper only. However, with the exception we don't get the result. Since we only need to work with the number of results, it's more sufficient to only count them, thus adding countUsersByLoginName() would solve the issue totally as not attribute procession is done, and it might be faster, though not really noticeable.

**Comment by dpeleg** [comment]
Hi
I'm getting the same error,
The users have all been imported from ldap, but instead of a username i get a weird hash.

![screen shot 2015-12-11 at 2 09 40 pm](https://cloud.githubusercontent.com/assets/7985437/11743531/f06b129a-a010-11e5-99ed-c56b5fbf9e88.png)

I've made sure that the User Display Name Field is the same as in my ldap (CN) and i also tried to use uid for the Display Name
to no avail...

**Comment by blizzz** [comment]
@dpeleg please read the manual
