### ISSUE TITLE
PHP Warning:  Declaration of OC\Files\Stream\Encryption::wrapSource

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/core#20648]
@rullzer 

````
10:17:20 PHP Warning:  Declaration of OC\Files\Stream\Encryption::wrapSource($source, $mode, $context, $protocol, $class) should be compatible with Icewind\Streams\Wrapper::wrapSource($source, $context, $protocol, $class) in /ssd/jenkins/workspace/server-master-linux-php7-ci@3/database/sqlite/label/SLAVE/lib/private/files/stream/encryption.php on line 30
10:17:20 PHP Fatal error:  Class OC\Files\Stream\Encryption contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Icewind\Streams\Directory::dir_opendir) in /ssd/jenkins/workspace/server-master-linux-php7-ci@3/database/sqlite/label/SLAVE/lib/private/files/stream/encryption.php on line 30

**Comment by DeepDiver1975** [comment]
seen here https://ci.owncloud.org/job/server-master-linux-php7-ci/15330/database=sqlite,label=SLAVE/console

**Comment by rullzer** [comment]
I think that was caused by an incomplete rebase on my side.. (my sharing PR)... but not sure since jenkins now gives a 404

**Comment by PVince81** [comment]
@rullzer bisect ?

**Comment by rullzer** [comment]
Was indeed caused by a bad rebase. Fixed now so closing this.

**Comment by DeepDiver1975** [comment]
still present on master

https://ci.owncloud.org/job/server-master-linux/database=sqlite,label=SLAVE/2839/console

**Comment by rullzer** [comment]
Ah mm yes.

Caused by https://github.com/owncloud/core/blob/master/lib/private/files/stream/encryption.php#L184 and the new definition in https://github.com/owncloud/3rdparty/blob/master/icewind/streams/src/Wrapper.php#L28

The difference I see is that the one from @icewind1991 takes no $mode parameter but the one from @schiesbn does.

It also seems that this mode parameter is required in https://github.com/owncloud/core/blob/master/lib/private/files/storage/wrapper/encryption.php#L415

@icewind1991 @schiesbn can you comment if it would be safe to remove the $mode? Since the default always just opens it 'r+'.

**Comment by schiesbn** [comment]
hm, not sure if it is a good idea to always open a stream in 'r+' mode? IMHO a stream wrapper should support all possible modes. Also in other places we distinguish between different modes, 'r+'. So I don't feel really comfortable to remove the $mode completely.

**Comment by rullzer** [comment]
Possible fix in https://github.com/owncloud/core/pull/20705
