### ISSUE TITLE
Shared folder doesn't display all files

### ISSUE THREAD

**Issue by yannick67** [owncloud/core#21203]
Step
1 : upload 25 files in a folder via web
2 : share the folder with external link
3 : click on the link and open it in IE11

No exceptions in log

Actual behaviour

only a few (depend of the resolution) files appear and the scrool bar don't work, this append only on ie11, with Filezilla or another navigator it is ok.

Server configuration

Operating system:
Ubuntu
VMX file image on the owncloud site, new install

ownCloud version: (see ownCloud admin page)
 oc 8.2.1. update recently

the solution found (scrollcontainer: $('#content-wrapper')) didn't work for me with IE 11.

**Comment by RealRancor** [comment]
Hi,

when reporting issues please take your time and use the issue template as asked in the gudelines for contributing (linked in the yellow box when creating a new issue).

**Comment by yannick67** [comment]
i found a workaround but it is not professionnal ...
in the styles.css a put a value (7000px) for content.height ang content-wrapper.height and then all files is list in IE.

**Comment by PVince81** [comment]
@Henni didn't we fix that recently ? I can't find any commit between v8.2.1 and stable8.2 so maybe it's yet another issue with the public template ?

**Comment by yannick67** [comment]
i found this commit with the same bug
https://github.com/owncloud/core/issues/19886
but this change nothing with IE 11

**Comment by PVince81** [comment]
@yannick67 okay, then maybe IE11 needs a more specific fix. What would we do without IE's usual pickiness ?

@yannick67 so other browsers work fine ?

**Comment by yannick67** [comment]
yes other browsers work fine thanks

**Comment by PVince81** [comment]
@Henni can you have a look ? Thanks.

**Comment by Henni** [comment]
@PVince81 yes we fixed this. But it seems like I broke it again in https://github.com/owncloud/files_pdfviewer/pull/87

Thus this bug should only occur if the pdfviewer app is enabled. Can you please confirm this @yannick67?

**Comment by yannick67** [comment]
@Henni I test with pdfviewer app disable and the bug persist.

**Comment by Henni** [comment]
I'm currently not able to test on IE11.
Could someone else take over @owncloud/designers ?

**Comment by yannick67** [comment]
By changing the value in  /owncloud/core/css/styles.css for "content.height: auto;" all files are list in the windows

**Comment by Henni** [comment]
Setting the height of content to auto actually solves the issue.
This is because IE11 doesn't recognize the property `initial`.

@yannick67 would you like to create a pull-request for this?

**Comment by yannick67** [comment]
If it can help other users yes.

Yannick Eckert

Service Informatique
Mairie de Bischwiller
9 Place de la Mairie - BP 10035
67241 BISCHWILLER Cedex
Ligne directe : 03.88.53.75.20
Fax : 03.88.63.52.12
E-mail : yannick.eckert@bischwiller.com<mailto:yannick.eckert@bischwiller.com>

http://www.bischwiller.com
http://www.cc-bischwiller.fr

Le 15 déc. 2015 à 14:56, Hendrik Leppelsack <notifications@github.com<mailto:notifications@github.com>> a écrit :


Setting the height of content to auto actually solves the issue.
This is because IE11 doesn't recognize the property initial.

@yannick67<https://github.com/yannick67> would you like to create a pull-request for this?

**Comment by tsfuchs** [comment]
I have the same problems here with 8.2.1 and 8.2.2, too.

### Steps to reproduce
1. Upload 20 Files to a owncloud folder
2. Create a public share link
3. Use the link and enter password
4. Can only see some of the files in IE11, Chrome, Firefox and Edge | Download all as zip file works.
5. Deactivate files_pdfviewer 0.7
6. All files are shown in Chrome, Firefox and Edge but NOT in IE11

### Server configuration
**Operating system**:
Debian 8

**Web server:**
Apache 2

**PHP version:**
PHP 5.6.14-0+deb8u1

**ownCloud version:** (see ownCloud admin page)
8.2.2

**Updated from an older ownCloud or fresh install:**
Updated from 7 or so on to the actual version

**List of activated apps:**
Enabled:
  - activity: 2.1.3
  - files: 1.2.0
  - files_external: 0.3.0
  - files_pdfviewer: 0.7
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - files_videoviewer: 0.1.3
  - firstrunwizard: 1.1
  - gallery: 14.2.0
  - updater: 0.6
  - user_ldap: 0.7.1

Disabled:
  - encryption
  - external
  - notifications
  - provisioning_api
  - templateeditor
  - user_external

**The content of config/config.php:**
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            ***REMOVED SENSITIVE VALUE***
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "8.2.2.2",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": true,
        "ldapIgnoreNamingRules": false,
        "loglevel": 3,
        "enable_previews": true,
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown"
        ],
        "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
        "preview_office_cl_parameters": " --headless --nologo --nofirststartwizard --invisible --norestore -convert-to pdf -outdir ",
        "enable_avatars": true,
        "allow_user_to_change_display_name": false,
        "skeletondirectory": "",
        "trashbin_retention_obligation": "30, auto",
        "theme": "",
        "maintenance": false,
        "ldapUserCleanupInterval": 51,
        "asset-pipeline.enabled": true,
        "appstoreenabled": false,
        "appstoreurl": "https:\/\/api.owncloud.com\/v1",
        "appstore.experimental.enabled": false,
        "appcodechecker": true,
        "minimum.supported.desktop.version": "1.8.3",
        "memcache.local": ""
    }
}

**Are you using encryption:** 
no

**Are you using an external user-backend, if yes which one:** 
ActiveDirectory


### Client configuration
**Browser:**
Chrome 47.0.2526.106
Firefox ESR 38.2.1
IE 11.20.10586.0

**Operating systems:**
Windows 7 / Windows 10

**Comment by PVince81** [comment]
Setting to 8.2.3 @cmonteroluque

**Comment by PVince81** [comment]
@Henni @yannick67 any update on the PR ?

**Comment by Resquer** [comment]
I have a same issue. Recently upgraded to 8.2.2
It is unable to see all objects in the shared folder when PDF Viewer  0.7 is enabled.
Not only IE, Chrome, Firefox are affected, but mobile browsers from android smartphone also.
When I have disabled PDF Viewer, it almost solve the problem, but IE11 still doesn't show all objects, it is unable to scroll.

**Comment by RealRancor** [comment]
@Resquer If there is an additional issue with PDF Viewer 0.7 you might want to create a new report at https://github.com/owncloud/files_pdfviewer/issues

**Comment by Resquer** [comment]
I don't know. PDF viewer works normally, but if it is enabled, the problem I explained yesterday is occurs.
PDF viewer is not important for me, so I simply disabled it.

**Comment by RealRancor** [comment]
@Resquer I think thats a different issue so thats why i'm suggesting to open a new issue. This one in here is about the issue with IE which you (as far as i understand) still get when disabling the PDF viewer.

**Comment by tsfuchs** [comment]
okay, opened a new issue ***#21373*** for the problem depending pdfviewer 0.7

**Comment by hsm-berlin** [comment]
I have the same problem with Firefox 42.0 and IE 11. My workaround is to edit /apps/files_sharing/css/public.css as follows:
>#content {
>	height: initial;
>	min-height: calc(100vh - 120px);
>}
>footer .info {
>	display: none;
>}

The problem is
> 	overflow: hidden;

for #content

**Comment by SergioBertolinSG** [comment]
This works correctly in master.
Reproduced on stable8.2

**Comment by jancborchardt** [comment]
@SergioBertolinSG @yannick67 @tsfuchs please review the backport of the fix for files_pdfviewer at https://github.com/owncloud/files_pdfviewer/pull/92 !

**Comment by jancborchardt** [comment]
Will be fixed in the next maintenance release cause https://github.com/owncloud/files_pdfviewer/pull/92 has been merged. :)

**Comment by rcaia** [comment]
Modified hsm-berlin's fix to ::

**#body-public** #content {
height: initial;
min-height: calc(100vh - 120px);
**overflow: visible;**
}
footer .info {
display: none;
}

Otherwise body-user pages end up with double scroll bars...

**Comment by jancborchardt** [comment]
@rcaia this was fixed meanwhile in 8.2. Or does this still happen for you? If so, please open a pull request with your fix. :)

**Comment by RealRancor** [comment]
@jancborchardt https://github.com/owncloud/core/issues/20044 is open and still happens for IE

**Comment by rcaia** [comment]
I’ve added my comment below to item #20044<https://github.com/owncloud/core/issues/20044>
---
I have no scroll bars for file lists on public links : ownCloud version 8.2.2, IE, Firefox, Chrome. I have my own theme so I edited styles.css in my theme folder...
Modified hsm-berlin's fix from item #21203 to ::
#body-public #content {
height: initial;
min-height: calc(100vh - 120px);
overflow: visible;
}
footer .info {
display: none;
}
Otherwise body-user pages end up with double scroll bars...
--

**Comment by rcaia** [comment]
I’ve added my comment below to item #20044<https://github.com/owncloud/core/issues/20044>
---
I have no scroll bars for file lists on public links : ownCloud version 8.2.2, IE, Firefox, Chrome. I have my own theme so I edited styles.css in my theme folder...
Modified hsm-berlin's fix from item #21203 to ::
#body-public #content {
height: initial;
min-height: calc(100vh - 120px);
overflow: visible;
}
footer .info {
display: none;
}
Otherwise body-user pages end up with double scroll bars...
--
