### ISSUE TITLE
Shared folders don't show all files in a directory when pdfviewer 0.7 is active

### ISSUE THREAD

**Issue by tsfuchs** [owncloud/core#21373]
### Steps to reproduce
1. Upload 20 Files to a owncloud folder
2. Create a public share link
3. Use the link and enter password
4. Can only see some of the files depending on the size of the window in IE11, Chrome, Firefox and Edge | Download all as zip file works.
5. Deactivate files_pdfviewer 0.7
6. All files are shown in Chrome, Firefox and Edge.

### Server configuration
**Operating system**:
Debian 8

**Web server:**
Apache 2

**PHP version:**
PHP 5.6.14-0+deb8u1

**ownCloud version:** (see ownCloud admin page)
8.2.2

**Updated from an older ownCloud or fresh install:**
Updated from 7 or so on to the actual version

**List of activated apps:**
Enabled:
  - activity: 2.1.3
  - files: 1.2.0
  - files_external: 0.3.0
  - files_pdfviewer: 0.7
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - files_videoviewer: 0.1.3
  - firstrunwizard: 1.1
  - gallery: 14.2.0
  - updater: 0.6
  - user_ldap: 0.7.1

Disabled:
  - encryption
  - external
  - notifications
  - provisioning_api
  - templateeditor
  - user_external

**The content of config/config.php:**
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            ***REMOVED SENSITIVE VALUE***
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "8.2.2.2",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": true,
        "ldapIgnoreNamingRules": false,
        "loglevel": 3,
        "enable_previews": true,
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown"
        ],
        "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
        "preview_office_cl_parameters": " --headless --nologo --nofirststartwizard --invisible --norestore -convert-to pdf -outdir ",
        "enable_avatars": true,
        "allow_user_to_change_display_name": false,
        "skeletondirectory": "",
        "trashbin_retention_obligation": "30, auto",
        "theme": "",
        "maintenance": false,
        "ldapUserCleanupInterval": 51,
        "asset-pipeline.enabled": true,
        "appstoreenabled": false,
        "appstoreurl": "https:\/\/api.owncloud.com\/v1",
        "appstore.experimental.enabled": false,
        "appcodechecker": true,
        "minimum.supported.desktop.version": "1.8.3",
        "memcache.local": ""
    }
}

**Are you using encryption:** 
no

**Are you using an external user-backend, if yes which one:** 
ActiveDirectory

### Client configuration
**Browser:**
Chrome 47.0.2526.106
Firefox ESR 38.2.1
IE 11.20.10586.0

**Operating systems:**
Windows 7 / Windows 10

**Comment by karlitschek** [comment]
@schiesbn any idea?

**Comment by CNeutron** [comment]
I can confirm that issue

**Comment by Nivatius** [comment]
can confirm with a clean install. images see https://github.com/owncloud/core/issues/21416

**Comment by MeCias** [comment]
I can confirm this behaviour as well. Without pdf viewer it is working as it used to be.

**Comment by Henni** [comment]
This should be fixed by owncloud/files_pdfviewer#91. Please review!

**Comment by jancborchardt** [comment]
Will be fixed in the next maintenance release cause https://github.com/owncloud/files_pdfviewer/pull/92 has been merged. :)

**Comment by PaulAnnekov** [comment]
@LukasReschke 8.2.3 is out, but this bug is still not fixed. Milestone is set to 8.2.3.

**Comment by koenr** [comment]
It works for me. Just tested on 8.2.5
