### ISSUE TITLE
LDAP Users not shown in sharing dropdown if sharing restriction to own group applies

### ISSUE THREAD

**Issue by tigre-bleu** [owncloud/core#22182]
The previous bug https://github.com/owncloud/core/issues/6946?_pjax=%23js-repo-pjax-container seems to have reappeared.

I am facing the exact same issue in 8.2.2

It is probably a good idea to reopen the original bug, but I do not have the access rights to do that.

**Comment by LukasReschke** [comment]
@blizzz

**Comment by PVince81** [comment]
CC @rullzer

**Comment by PVince81** [comment]
I suppose a bisect should be possible.

**Comment by rullzer** [comment]
I just checked... on 9.0 this is working correctly it seems.

**Comment by rullzer** [comment]
@MorrisJobke  @blizzz can you verify that it is also working for you... 

I'll test on 8.2 now

**Comment by rullzer** [comment]
Also works for me on a clean current 8.2

**Comment by rullzer** [comment]
Even on a clean 8.2.2 all works fine....

@tigre-bleu could you try a clean install and see if you still observe the problem?

**Comment by f-s** [comment]
Almost identical problem, 8.2.2 install:

https://github.com/owncloud/core/issues/22821

more info for you :D

**Comment by blizzz** [comment]
Trying with current stable8.2, it also works for me.

**Comment by blizzz** [comment]
Anything in your logs? @tigre-bleu @f-s ?

**Comment by f-s** [comment]
@blizzz  There is nothing "new" in the logs, the ajax query simply returns a "success" for the look-up of the possible names in the shared group, but an empty result set :-(

**Comment by blizzz** [comment]
> But also when sharing without groups, I get the wrong, empty result set, every few searches, no errors logged.

Then it might be an issue with caching, fixed in 8.2.3. Maybe you could try the RC? https://mailman.owncloud.org/pipermail/devel/2016-March/002202.html

**Comment by f-s** [comment]
> Then it might be an issue with caching, fixed in 8.2.3.

Looks like it. I can find the user always first time. Not second time with same user, searching for another user works. 

With the "search-limited-to-same-group" setting on, it is still not working. 

Info: The 389-ldap does not have **memberOf **enabled. Is this mechansim required? I can see something like this in the logs:

`initializing paged search for Filter (&(|(objectclass=sambaSAMAccount))(|(uid=gg*)(cn=gg*)(sn=gg*))) base Array ( [0] => ou=Users,dc=test,dc=org ) attr Array ( [0] => dn [1] => uid [2] => samaccountname [3] => memberof [4] => [5] => mail [6] => cn [7] => uid ) limit 20000 offset 0`

**Comment by blizzz** [comment]
> Info: The 389-ldap does not have memberOf enabled. Is this mechanism required?

No, it is not. It will be read and used if present, but this is not a requirement.

**Comment by PVince81** [comment]
Not sure how to move forward with this @owncloud/ldap ?

**Comment by f-s** [comment]
issue does not exist in 9.0.2

**Comment by PVince81** [comment]
I'm closing this then, thanks for the feedback.
