### ISSUE TITLE
Settings Admin page reloads every second on HTTPS

### ISSUE THREAD

**Issue by enoch85** [owncloud/core#22977]
### Steps to reproduce
1. Download [this VM](https://en0ch.se/index.php/s/MUl79ovm7Ifo4kG)
2. Run the setup script (not needed but just to get the same experience)
*user: ocadmin / pass: owncloud*
3. Go to https://192.168.X.X (no errors via HTTP)
4. Go to Admin Settings

### Expected behaviour
No constant reloading of page

### Actual behaviour
on HTTPS the Setup & Security check make the page reload every second. When I go to "Log" (or below the check) the site stops reloading. I can also see with the inspect tool that I get a new requesttoken on every reload.

### Server configuration
**Operating system**:
Ubuntu 14.04
**Web server:**
Apache 2.4
**Database:**
MySQL 5.6
**PHP version:**
7.0 deb sury
**ownCloud version:** (see ownCloud admin page)
9.0.0 stable
**Updated from an older ownCloud or fresh install:**
Fresh
**Where did you install ownCloud from:**
Ubuntu Packages (ownCloud)
**Signing status (ownCloud 9.0 and above):**

```
No errors
```

**List of activated apps:**

```
Enabled:
  - activity: 2.2.1
  - calendar: 1.0
  - comments: 0.2
  - contacts: 1.0.0.0
  - dav: 0.1.5
  - documents: 0.13.0
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - encryption
  - external
  - files_external
  - user_external
  - user_ldap
```

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'passwordsalt' => 'c3tGRprER7g6IfQQ7dhachqCAuJTna',
  'secret' => '/6azgCGShxxMb5RT+bFcf8XcXZAvUxOAu87HHJvyMsjsCHSz',
  'trusted_domains' => 
  array (
    0 => 'localhost',
    1 => '192.168.1.172',
    2 => 'owncloud',
    3 => 'owncloud',
  ),
  'datadirectory' => '/var/www/html/owncloud/data',
  'overwrite.cli.url' => 'https://192.168.1.172/owncloud',
  'dbtype' => 'mysql',
  'version' => '9.0.0.18',
  'dbname' => 'owncloud_db',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_ocadmin',
  'dbpassword' => 'KCEW6SgP16Gu1AdMW4+M+526UHhoMi',
  'logtimezone' => 'UTC',
  'installed' => true,
  'instanceid' => 'ocndm5hudxhe',
  'appstore.experimental.enabled' => 'true',
  'preview_libreoffice_path' => '/usr/bin/libreoffice',
  'memcache.local' => '\\OC\\Memcache\\Redis',
  'filelocking.enabled' => 'true',
  'memcache.distributed' => '\\OC\\Memcache\\Redis',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' => 
  array (
    'host' => 'localhost',
    'port' => 6379,
    'timeout' => 0,
    'dbindex' => 0,
  ),
  'maintenance' => false,
);
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
No

### Client configuration
**Browser:**
Chrome 49
**Operating system:**
Deepin 15 (Debian) & Windows (tested both)
#### Web server error log
```
No errors
```

#### ownCloud log (data/owncloud.log)
```
No errors
```

### SSL Config
**Virtual Host** 

https://github.com/enoch85/ownCloud-VM/blob/master/beta/owncloud_install.sh#L180-L208

**Comment by nickvergessen** [comment]
Your trusted domains look strange?

**Comment by enoch85** [comment]
@nickvergessen To be sure that it gets all the domain and hosts @jnweiger developed a update-config.php script that is used to update the trusted domains. Used in VM we developed last year as well: https://github.com/owncloud/vm/tree/master/vagrant/oc8ce

**Comment by nickvergessen** [comment]
At least those two entries:
```
    2 => 'owncloud',
    3 => 'owncloud',
```

should at most be one. Not sure the trusted_domain causes your problem, but might be related.

**Comment by enoch85** [comment]
I changed it, and it had no effect. Thanks for noticing!

**Comment by nickvergessen** [comment]
cc @LukasReschke

**Comment by enoch85** [comment]
How can I debug this? @LukasReschke

**Comment by enoch85** [comment]
Just noticed, it happens on some VMs and other not. Just tested to download and mount it again and the error was gone. Will keep investigating.

**Comment by esphen** [comment]
Just chiming in to say I am also seeing this. My personal owncloud is in a docker container behind an apache proxy which terminates TLS. Admin panel is unusable, unfortunately. Everything else seems to work fine

**Comment by enoch85** [comment]
@espenaf Thanks for confirming! Have you found the cause of the error?

**Comment by esphen** [comment]
@enoch85 

No, sorry. Checking the logs I am getting an infinite loop of these messages:

> {"reqId":"yF8rJtnMi3W7DV6mT6nI","remoteAddr":"172.17.0.1","app":"PHP","message":"Undefined index: newVersionString at \/var\/www\/html\/apps\/updatenotification\/templates\/admin.php#8","level":3,"time":"2016-03-13T18:56:30+00:00"}
{"reqId":"xi6mF6f90pb26\/H3kdDY","remoteAddr":"172.17.0.1","app":"PHP","message":"Undefined index: newVersionString at \/var\/www\/html\/apps\/updatenotification\/templates\/admin.php#8","level":3,"time":"2016-03-13T18:56:30+00:00"}
{"reqId":"0gbzGAm5ODglkqXaCRtG","remoteAddr":"172.17.0.1","app":"PHP","message":"unlink(): No such file or directory at \/var\/www\/html\/lib\/private\/helper.php#227","level":3,"time":"2016-03-13T18:56:31+00:00"}
{"reqId":"0gbzGAm5ODglkqXaCRtG","remoteAddr":"172.17.0.1","app":"PHP","message":"rmdir(\/tmp\/oc_tmp_eZjYFp-folder\/news\/vendor\/bin): Directory not empty at \/var\/www\/html\/lib\/private\/helper.php#225","level":3,"time":"2016-03-13T18:56:31+00:00"}
{"reqId":"0gbzGAm5ODglkqXaCRtG","remoteAddr":"172.17.0.1","app":"PHP","message":"rmdir(\/tmp\/oc_tmp_eZjYFp-folder\/news\/vendor): Directory not empty at \/var\/www\/html\/lib\/private\/helper.php#225","level":3,"time":"2016-03-13T18:56:31+00:00"}
{"reqId":"0gbzGAm5ODglkqXaCRtG","remoteAddr":"172.17.0.1","app":"PHP","message":"rmdir(\/tmp\/oc_tmp_eZjYFp-folder\/news): Directory not empty at \/var\/www\/html\/lib\/private\/helper.php#225","level":3,"time":"2016-03-13T18:56:31+00:00"}
{"reqId":"0gbzGAm5ODglkqXaCRtG","remoteAddr":"172.17.0.1","app":"PHP","message":"rmdir(\/tmp\/oc_tmp_eZjYFp-folder): Directory not empty at \/var\/www\/html\/lib\/private\/helper.php#231","level":3,"time":"2016-03-13T18:56:31+00:00"}

Not what's going on here. _"Undefined index: newVersionString at \/var\/www\/html\/apps\/updatenotification\/templates\/admin.php#8"_, seems to happen in between every batch of requests (different reqId), so that's suspicious. Could that be triggering the reloads?

**Comment by enoch85** [comment]
@esphen That's unrelated, here is a fix: https://github.com/owncloud/core/issues/22917

**Comment by PVince81** [comment]
> on HTTPS the Setup & Security check make the page reload every second

Can you check the browser JS console and also network console ?
The setup check is using a lot of JS code, maybe some error is triggered there and reloads the page as a side-effect.

**Comment by enoch85** [comment]
@esphen As I don't seem to be able to reproduce this anymore, could you please help us debug this?

**Comment by esphen** [comment]
@enoch85 

Sure,

I've had a look at the logs in both FF and Chrome, which both are looping, and this is what I'm seeing:

Both browsers are looping while logging `Mixed Content: The page at 'https://xxx/settings/admin' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://xxx/apps/files/'. This request has been blocked; the content must be served over HTTPS.`
`Navigated to https://xxx/settings/admin`

I am seeing two interesting things:

* `data/.ocdata` is returning 302 Found and has a Location header with `http://xxx/apps/files/`, which is **http**, not https. This may be the mixed content issue. And as I am using HSTS that URL should be unreachable on http.
* In FF network log `settings/ajax/checksetup` is never returning a response. When I open that URL in a new tab I am seeing 412 Precondition failed on the request and a page that says `Access denied. CSRF check failed`. Don't think you intend people to be opening that URL directly, so not sure if that is an issue.

Does that help you at all? Tell me if you need anything else

**Comment by enoch85** [comment]
Ok, I got it again. Here are some error outputs from inspect tool in Chrome:

```
Failed to load resource: the server responded with a status of 401 (Unauthorized)
/owncloud/core/vendor/jquery/jquery.min.js?v=3cfb16a3083af0d67aaa62f9761b22ee:6 GET https://192.168.1.167/index.php/apps/files/ 401 (Unauthorized)send @ /owncloud/core/vendor/jquery/jquery.min.js?v=3cfb16a3083af0d67aaa62f9761b22ee:6x.extend.ajax @ /owncloud/core/vendor/jquery/jquery.min.js?v=3cfb16a3083af0d67aaa62f9761b22ee:6OC.SetupChecks.checkDataProtected @ /owncloud/core/js/setupchecks.js?v=3cfb16a3083af0d67aaa62f9761b22ee:209(anonymous function) @ /owncloud/settings/js/admin.js?v=3cfb16a3083af0d67aaa62f9761b22ee:175c @ /owncloud/core/vendor/jquery/jquery.min.js?v=3cfb16a3083af0d67aaa62f9761b22ee:4p.fireWith @ /owncloud/core/vendor/jquery/jquery.min.js?v=3cfb16a3083af0d67aaa62f9761b22ee:4x.extend.ready @ /owncloud/core/vendor/jquery/jquery.min.js?v=3cfb16a3083af0d67aaa62f9761b22ee:4q @ /owncloud/core/vendor/jquery/jquery.min.js?v=3cfb16a3083af0d67aaa62f9761b22ee:4
/owncloud/core/vendor/jquery/jquery.min.js?v=3cfb16a3083af0d67aaa62f9761b22ee:6 GET https://192.168.1.167/index.php/apps/files/ 401 (Unauthorized)send @ /owncloud/core/vendor/jquery/jquery.min.js?v=3cfb16a3083af0d67aaa62f9761b22ee:6x.extend.ajax @ /owncloud/core/vendor/jquery/jquery.min.js?v=3cfb16a3083af0d67aaa62f9761b22ee:6OC.SetupChecks.checkDataProtected @ /owncloud/core/js/setupchecks.js?v=3cfb16a3083af0d67aaa62f9761b22ee:209(anonymous function) @ /owncloud/settings/js/admin.js?v=3cfb16a3083af0d67aaa62f9761b22ee:175c @ /owncloud/core/vendor/jquery/jquery.min.js?v=3cfb16a3083af0d67aaa62f9761b22ee:4p.fireWith @ /owncloud/core/vendor/jquery/jquery.min.js?v=3cfb16a3083af0d67aaa62f9761b22ee:4x.extend.ready @ /owncloud/core/vendor/jquery/jquery.min.js?v=3cfb16a3083af0d67aaa62f9761b22ee:4q @ /owncloud/core/vendor/jquery/jquery.min.js?v=3cfb16a3083af0d67aaa62f9761b22ee:4
/owncloud/core/vendor/jquery/jquery.min.js?v=3cfb16a3083af0d67aaa62f9761b22ee:6 GET https://192.168.1.167/index.php/apps/files/ 401 (Unauthorized)send @ /owncloud/core/vendor/jquery/jquery.min.js?v=3cfb16a3083af0d67aaa62f9761b22ee:6x.extend.ajax @ /owncloud/core/vendor/jquery/jquery.min.js?v=3cfb16a3083af0d67aaa62f9761b22ee:6OC.SetupChecks.checkDataProtected @ /owncloud/core/js/setupchecks.js?v=3cfb16a3083af0d67aaa62f9761b22ee:209(anonymous function) @ /owncloud/settings/js/admin.js?v=3cfb16a3083af0d67aaa62f9761b22ee:175c @ /owncloud/core/vendor/jquery/jquery.min.js?v=3cfb16a3083af0d67aaa62f9761b22ee:4p.fireWith @ /owncloud/core/vendor/jquery/jquery.min.js?v=3cfb16a3083af0d67aaa62f9761b22ee:4x.extend.ready @ /owncloud/core/vendor/jquery/jquery.min.js?v=3cfb16a3083af0d67aaa62f9761b22ee:4q @ /owncloud/core/vendor/jquery/jquery.min.js?v=3cfb16a3083af0d67aaa62f9761b22ee:4
/owncloud/core/vendor/jquery/jquery.min.js?v=3cfb16a3083af0d67aaa62f9761b22ee:6 GET https://192.168.1.167/index.php/apps/files/ 401 (Unauthorized)send @ /owncloud/core/vendor/jquery/jquery.min.js?v=3cfb16a3083af0d67aaa62f9761b22ee:6x.extend.ajax @ /owncloud/core/vendor/jquery/jquery.min.js?v=3cfb16a3083af0d67aaa62f9761b22ee:6OC.SetupChecks.checkDataProtected @ /owncloud/core/js/setupchecks.js?v=3cfb16a3083af0d67aaa62f9761b22ee:209(anonymous function) @ /owncloud/settings/js/admin.js?v=3cfb16a3083af0d67aaa62f9761b22ee:175c @ /owncloud/core/vendor/jquery/jquery.min.js?v=3cfb16a3083af0d67aaa62f9761b22ee:4p.fireWith @ /owncloud/core/vendor/jquery/jquery.min.js?v=3cfb16a3083af0d67aaa62f9761b22ee:4x.extend.ready @ /owncloud/core/vendor/jquery/jquery.min.js?v=3cfb16a3083af0d67aaa62f9761b22ee:4q @ /owncloud/core/vendor/jquery/jquery.min.js?v=3cfb16a3083af0d67aaa62f9761b22ee:4
/owncloud/core/vendor/jquery/jquery.min.js?v=3cfb16a3083af0d67aaa62f9761b22ee:6 GET https://192.168.1.167/index.php/apps/files/ 401 (Unauthorized)send @ /owncloud/core/vendor/jquery/jquery.min.js?v=3cfb16a3083af0d67aaa62f9761b22ee:6x.extend.ajax @ /owncloud/core/vendor/jquery/jquery.min.js?v=3cfb16a3083af0d67aaa62f9761b22ee:6OC.SetupChecks.checkDataProtected @ /owncloud/core/js/setupchecks.js?v=3cfb16a3083af0d67aaa62f9761b22ee:209(anonymous function) @ /owncloud/settings/js/admin.js?v=3cfb16a3083af0d67aaa62f9761b22ee:175c @ /owncloud/core/vendor/jquery/jquery.min.js?v=3cfb16a3083af0d67aaa62f9761b22ee:4p.fireWith @ /owncloud/core/vendor/jquery/jquery.min.js?v=3cfb16a3083af0d67aaa62f9761b22ee:4x.extend.ready @ /owncloud/core/vendor/jquery/jquery.min.js?v=3cfb16a3083af0d67aaa62f9761b22ee:4q @ /owncloud/core/vendor/jquery/jquery.min.js?v=3cfb16a3083af0d67aaa62f9761b22ee:4
/owncloud/core/vendor/jquery/jquery.min.js?v=3cfb16a3083af0d67aaa62f9761b22ee:6 GET https://192.168.1.167/index.php/apps/files/ 401 (Unauthorized)send @ /owncloud/core/vendor/jquery/jquery.min.js?v=3cfb16a3083af0d67aaa62f9761b22ee:6x.extend.ajax @ /owncloud/core/vendor/jquery/jquery.min.js?v=3cfb16a3083af0d67aaa62f9761b22ee:6OC.SetupChecks.checkDataProtected @ /owncloud/core/js/setupchecks.js?v=3cfb16a3083af0d67aaa62f9761b22ee:209(anonymous function) @ /owncloud/settings/js/admin.js?v=3cfb16a3083af0d67aaa62f9761b22ee:175c @ /owncloud/core/vendor/jquery/jquery.min.js?v=3cfb16a3083af0d67aaa62f9761b22ee:4p.fireWith @ /owncloud/core/vendor/jquery/jquery.min.js?v=3cfb16a3083af0d67aaa62f9761b22ee:4x.extend.ready @ /owncloud/core/vendor/jquery/jquery.min.js?v=3cfb16a3083af0d67aaa62f9761b22ee:4q @ /owncloud/core/vendor/jquery/jquery.min.js?v=3cfb16a3083af0d67aaa62f9761b22ee:4
jquery.min.js?v=3cfb16a…:6 GET https://192.168.1.167/index.php/apps/files/ 401 (Unauthorized)send @ jquery.min.js?v=3cfb16a…:6x.extend.ajax @ jquery.min.js?v=3cfb16a…:6OC.SetupChecks.checkDataProtected @ setupchecks.js?v=3cfb16a…:209(anonymous function) @ admin.js?v=3cfb16a…:175c @ jquery.min.js?v=3cfb16a…:4p.fireWith @ jquery.min.js?v=3cfb16a…:4x.extend.ready @ jquery.min.js?v=3cfb16a…:4q @ jquery.min.js?v=3cfb16a…:4
Navigated to https://192.168.1.167/owncloud/index.php/settings/admin
jquery.min.js?v=3cfb16a…:6 GET https://192.168.1.167/index.php/apps/files/ 401 (Unauthorized)send @ jquery.min.js?v=3cfb16a…:6x.extend.ajax @ jquery.min.js?v=3cfb16a…:6OC.SetupChecks.checkDataProtected @ setupchecks.js?v=3cfb16a…:209(anonymous function) @ admin.js?v=3cfb16a…:175c @ jquery.min.js?v=3cfb16a…:4p.fireWith @ jquery.min.js?v=3cfb16a…:4x.extend.ready @ jquery.min.js?v=3cfb16a…:4q @ jquery.min.js?v=3cfb16a…:4
Navigated to https://192.168.1.167/owncloud/index.php/settings/admin
jquery.min.js?v=3cfb16a…:6 GET https://192.168.1.167/index.php/apps/files/ 401 (Unauthorized)send @ jquery.min.js?v=3cfb16a…:6x.extend.ajax @ jquery.min.js?v=3cfb16a…:6OC.SetupChecks.checkDataProtected @ setupchecks.js?v=3cfb16a…:209(anonymous function) @ admin.js?v=3cfb16a…:175c @ jquery.min.js?v=3cfb16a…:4p.fireWith @ jquery.min.js?v=3cfb16a…:4x.extend.ready @ jquery.min.js?v=3cfb16a…:4q @ jquery.min.js?v=3cfb16a…:4
Navigated to https://192.168.1.167/owncloud/index.php/settings/admin
jquery.min.js?v=3cfb16a…:6 GET https://192.168.1.167/index.php/apps/files/ 401 (Unauthorized)send @ jquery.min.js?v=3cfb16a…:6x.extend.ajax @ jquery.min.js?v=3cfb16a…:6OC.SetupChecks.checkDataProtected @ setupchecks.js?v=3cfb16a…:209(anonymous function) @ admin.js?v=3cfb16a…:175c @ jquery.min.js?v=3cfb16a…:4p.fireWith @ jquery.min.js?v=3cfb16a…:4x.extend.ready @ jquery.min.js?v=3cfb16a…:4q @ jquery.min.js?v=3cfb16a…:4
Navigated to https://192.168.1.167/owncloud/index.php/settings/admin
jquery.min.js?v=3cfb16a…:6 GET https://192.168.1.167/index.php/apps/files/ 401 (Unauthorized)send @ jquery.min.js?v=3cfb16a…:6x.extend.ajax @ jquery.min.js?v=3cfb16a…:6OC.SetupChecks.checkDataProtected @ setupchecks.js?v=3cfb16a…:209(anonymous function) @ admin.js?v=3cfb16a…:175c @ jquery.min.js?v=3cfb16a…:4p.fireWith @ jquery.min.js?v=3cfb16a…:4x.extend.ready @ jquery.min.js?v=3cfb16a…:4q @ jquery.min.js?v=3cfb16a…:4
Navigated to https://192.168.1.167/owncloud/index.php/settings/admin
jquery.min.js?v=3cfb16a…:6 GET https://192.168.1.167/index.php/apps/files/ 401 (Unauthorized)send @ jquery.min.js?v=3cfb16a…:6x.extend.ajax @ jquery.min.js?v=3cfb16a…:6OC.SetupChecks.checkDataProtected @ setupchecks.js?v=3cfb16a…:209(anonymous function) @ admin.js?v=3cfb16a…:175c @ jquery.min.js?v=3cfb16a…:4p.fireWith @ jquery.min.js?v=3cfb16a…:4x.extend.ready @ jquery.min.js?v=3cfb16a…:4q @ jquery.min.js?v=3cfb16a…:4
Navigated to https://192.168.1.167/owncloud/index.php/settings/admin
jquery.min.js?v=3cfb16a…:6 GET https://192.168.1.167/index.php/apps/files/ 401 (Unauthorized)send @ jquery.min.js?v=3cfb16a…:6x.extend.ajax @ jquery.min.js?v=3cfb16a…:6OC.SetupChecks.checkDataProtected @ setupchecks.js?v=3cfb16a…:209(anonymous function) @ admin.js?v=3cfb16a…:175c @ jquery.min.js?v=3cfb16a…:4p.fireWith @ jquery.min.js?v=3cfb16a…:4x.extend.ready @ jquery.min.js?v=3cfb16a…:4q @ jquery.min.js?v=3cfb16a…:4
Navigated to https://192.168.1.167/owncloud/index.php/settings/admin
```

**Comment by PVince81** [comment]
Ok, so `OC.SetupChecks.checkDataProtected` is receiving a 401 on the data folder. Usually that should be a 403.

Can you try this:
`curl -D - http://localhost/owncloud/data/`
and then with an authenticated user:
`curl -D - http://admin:admin@localhost/owncloud/data/`

Both should return 403.

I suspect that something in your setup is blocking the data folder using a different approach.

CC @LukasReschke

**Comment by enoch85** [comment]
@PVince81 Sorry, can't test right now. But regarding the permissions I use ownClouds recommended script: https://github.com/enoch85/ownCloud-VM/blob/master/production/setup_secure_permissions_owncloud.sh 

I get a lot of emails regarding this so it would be super if @LukasReschke could help us out here.

**Comment by nickvergessen** [comment]
Could this be related to https://github.com/owncloud/core/issues/23482#issuecomment-199881984 ?

**Comment by PVince81** [comment]
Slightly related. But the setup check has a flag "allowAuthErrors" to prevent the global handler to do anything.

Let me do a test to confirm.

**Comment by PVince81** [comment]
Works for me. If I hack Webdav to return 401, the global handler properly ignores the error, no reload.

@enoch85 you can try commenting out this line https://github.com/owncloud/core/blob/v9.0.0/core/js/js.js#L749 and see if the reloading still happens.

**Comment by PVince81** [comment]
Tested in Firefox 44.0.2 and Chromium 48.0.2564.116

**Comment by enoch85** [comment]
@PVince81

>@enoch85 you can try commenting out this line https://github.com/owncloud/core/blob/v9.0.0/core/js/js.js#L749 and see if the reloading still happens.

That fixed it. Will this be addressed in 9.0.1?

**Comment by enoch85** [comment]
This also effects unshared links: https://en0ch.se/index.php/s/nEZEzFJqOCmcKjW

PHP 5.5
MySQL 5.5
Ubuntu Server 14.04

**Comment by LukasReschke** [comment]
> This also effects unshared links: https://en0ch.se/index.php/s/nEZEzFJqOCmcKjW

@oparoz This is caused by a request to "https://en0ch.se/index.php/apps/gallery/config?extramediatypes=1" which 401's.

**Comment by enoch85** [comment]
@PVince81 
> @enoch85 you can try commenting out this line https://github.com/owncloud/core/blob/v9.0.0/core/js/js.js#L749 and see if the reloading still happens.

Will this be fixed in 9.0.1?

**Comment by oparoz** [comment]
>@oparoz This is caused by a request to "https://en0ch.se/index.php/apps/gallery/config?extramediatypes=1" which 401's.

@LukasReschke - It's because of the template used to show that message. We're on a public page, using a public link URL, which should contain a token, but another template is being used, so the script thinks it's on a regular page, not a public page and makes a request to the private route.

**Comment by enoch85** [comment]
When I comment out #`Alias /owncloud "/var/www/owncloud/"` in my Apache virtualhost (placed in sites-enabled)  the error disappears. 

@LukasReschke Any thoughs?

**Comment by enoch85** [comment]
Been doing some more tests now, it seems to be gone in RC1. This errors is so strange. Did you merge anything to fix this?

Problem now is that .htaccess does not seem to work. Get a setup warning. Double checked everything and everything seems correct.

- .htaccess exists in /data
- .htaccess in /owncloud exists and are untouched
- Permissions are correct (used recommended settings from the documentation)
- No htaccesstest.txt in /data
- Using the Apache Vhost from above ---^

I know this may be a config issue, but help would be much appreciated!

**Comment by enoch85** [comment]
I think I fixed it (.htaccess issue) by moving the datadir outside webroot. No more errors, and no reloading. Don't know what caused it still...

Closing this. I'll reopen if it remains.

**Comment by bigeagle** [comment]
Hi, I'm using `9.0.1-apache` with docker and this issue still exists.
