### ISSUE TITLE
After upgrading from 8.2.2 to 9.0.0 all apache configurations for owncloud are missing

### ISSUE THREAD

**Issue by tps800** [owncloud/core#23289]
### Steps to reproduce
1. upgrade working owncloud install from 8.2.2 to 9.0.0
2. restart your apache
3. point a client to http://<server>/owncloud -> URL /owncloud not found on server

### Expected behaviour
Owncloud should switch to maintenance mode and stay reachable

### Actual behaviour
Owncloud switches to maintanance mode, but it is not reachable any more

### Client configuration
**Operating system:** Ubuntu 14.04.5 LTS

**OwnCloud Client:** nightly

**Operating system:** Windows 7 Pro

**OwnCloud Client:** nightly

**Operating system:** Windows 10 Pro

**OwnCloud Client:** nightly

### Server configuration
**Operating system:** Oracle Linux 6.7

**Web server:** Apache 2.2.15-47.0.1

**Database:** PostgreSQL 9.5.0-1

**PHP version:** PHP 5.6.18-1

**redis version:** redis-2.4.10-1

**ownCloud version before upgrade:** owncloud-8.2.2-1.1

**ownCloud version after upgrade:** owncloud-9.0.0-1.1

**Updated from an older ownCloud or fresh install:** Upgrade from 6.5

**Where did you install ownCloud from:** stable repos at http://download.owncloud.org/download/repositories/stable/CentOS_6

**Signing status (ownCloud 9.0 and above):** ?

**List of activated apps:**
* Enabled:
 - activity
 - files
 - files_pdfviewer
 - files_sharing
 - files_trashbin
 - files_texteditor
 - files_versions
 - gallery
 - imprint
 - ocusagecharts
 - password_policy
 - user_ldap

* Disabled:
 - external
 - files_encryption
 - files_external
 - files_locking
 - files_videoviewer
 - firstrunwizard
 - provisioning_api
 - templateeditor
 - updater
 - user_external
 - user_webdavauth

**The content of config/config.php:** 

```
<?php
$CONFIG = array (
  'instanceid' => 'oc692ddacb52',
  'passwordsalt' => '',
  'trusted_domains' =>
  array (
    0 => '<server1>.<local1>.<domain1>',
    1 => '<server2>.<local2>.<domain2>',
  ),
  'datadirectory' => '/data/owncloud/data',
  'dbtype' => 'pgsql',
  'version' => '7.0.1.1',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncld',
  'dbpassword' => '',
  'installed' => true,
  'ldapIgnoreNamingRules' => false,
  'theme' => '',
  'maintenance' => false,
  'loglevel' => '0',
  'mail_smtpmode' => 'php',
  'mail_smtpname' => 'admin',
  'mail_smtppassword' => '',
  'overwritewebroot' => '/owncloud',
  'overwrite.cli.url' => '/owncloud',
  'secret' => '',
  'redis' => array (
    'host' => 'localhost',
    'port' => 6379,
    'timeout' => 0,
    'dbindex' => 0,
  ),
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'memcache.distributed' => '\\OC\\Memcache\\Redis',
  'proxy' => 'proxy-lb:8080',
);

```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

### Client configuration
**Browser:**
* Windows XP/7/8:
 * Chrome (stable, beta, snapshot)
 * Chromium (stable, continuous)
 * Firefox (stable, nightly)
 * Opera (stable)
 * lynx (from cygwin)
 * w3m (from cygwin)
* Linux (Debian, Ubuntu 12.04/14.04/14.10, Fedora 19/20/21, Oracle Linux 6.5/7.0)
 * Chrome (stable, beta, snapshot)
 * Chromium (stable, continuous)
 * Firefox (stable, nightly)
 * Opera (last available)
 * Konqueror (stable)
 * lynx (stable)
 * w3m (stable)

#### Web server error log
```
195.37.205.30 - - [16/Mar/2016:09:30:40 +0100] "GET /owncloud/status.php HTTP/1.1" 404 297
195.37.205.30 - - [16/Mar/2016:09:30:40 +0100] "GET /owncloud/owncloud/status.php HTTP/1.1" 404 306
10.160.0.85 - - [16/Mar/2016:09:30:46 +0100] "GET /owncloud/status.php HTTP/1.1" 404 297
10.160.0.85 - - [16/Mar/2016:09:30:46 +0100] "GET /owncloud/owncloud/status.php HTTP/1.1" 404 306
10.160.0.14 - - [16/Mar/2016:09:30:52 +0100] "GET /owncloud/status.php HTTP/1.1" 404 297
10.160.2.12 - - [16/Mar/2016:09:30:57 +0100] "GET /owncloud/status.php HTTP/1.1" 404 297
10.160.2.12 - - [16/Mar/2016:09:30:57 +0100] "GET /owncloud/owncloud/status.php HTTP/1.1" 404 306
141.52.49.56 - - [16/Mar/2016:09:31:02 +0100] "GET /owncloud/status.php HTTP/1.1" 404 297
141.52.49.56 - - [16/Mar/2016:09:31:02 +0100] "GET /owncloud/owncloud/status.php HTTP/1.1" 404 306
10.160.0.23 - - [16/Mar/2016:09:31:12 +0100] "GET /owncloud/status.php HTTP/1.1" 404 297
10.160.0.23 - - [16/Mar/2016:09:31:12 +0100] "GET /owncloud/owncloud/status.php HTTP/1.1" 404 306
195.37.205.30 - - [16/Mar/2016:09:31:12 +0100] "GET /owncloud/status.php HTTP/1.1" 404 297
195.37.205.30 - - [16/Mar/2016:09:31:12 +0100] "GET /owncloud/owncloud/status.php HTTP/1.1" 404 306
10.160.0.85 - - [16/Mar/2016:09:31:18 +0100] "GET /owncloud/status.php HTTP/1.1" 404 297
10.160.0.85 - - [16/Mar/2016:09:31:18 +0100] "GET /owncloud/owncloud/status.php HTTP/1.1" 404 306
10.160.0.14 - - [16/Mar/2016:09:31:22 +0100] "GET /owncloud/status.php HTTP/1.1" 404 297
10.160.2.12 - - [16/Mar/2016:09:31:29 +0100] "GET /owncloud/status.php HTTP/1.1" 404 297
10.160.2.12 - - [16/Mar/2016:09:31:29 +0100] "GET /owncloud/owncloud/status.php HTTP/1.1" 404 306
141.52.49.56 - - [16/Mar/2016:09:31:34 +0100] "GET /owncloud/status.php HTTP/1.1" 404 297
141.52.49.56 - - [16/Mar/2016:09:31:34 +0100] "GET /owncloud/owncloud/status.php HTTP/1.1" 404 306
10.160.0.23 - - [16/Mar/2016:09:31:44 +0100] "GET /owncloud/status.php HTTP/1.1" 404 297
10.160.0.23 - - [16/Mar/2016:09:31:44 +0100] "GET /owncloud/owncloud/status.php HTTP/1.1" 404 306
195.37.205.30 - - [16/Mar/2016:09:31:44 +0100] "GET /owncloud/status.php HTTP/1.1" 404 297
195.37.205.30 - - [16/Mar/2016:09:31:44 +0100] "GET /owncloud/owncloud/status.php HTTP/1.1" 404 306
10.160.0.85 - - [16/Mar/2016:09:31:50 +0100] "GET /owncloud/status.php HTTP/1.1" 404 297
10.160.0.85 - - [16/Mar/2016:09:31:50 +0100] "GET /owncloud/owncloud/status.php HTTP/1.1" 404 306
10.160.0.14 - - [16/Mar/2016:09:31:52 +0100] "GET /owncloud/status.php HTTP/1.1" 404 297
10.160.2.12 - - [16/Mar/2016:09:32:01 +0100] "GET /owncloud/status.php HTTP/1.1" 404 297
10.160.2.12 - - [16/Mar/2016:09:32:01 +0100] "GET /owncloud/owncloud/status.php HTTP/1.1" 404 306
141.52.49.56 - - [16/Mar/2016:09:32:06 +0100] "GET /owncloud/status.php HTTP/1.1" 404 297
141.52.49.56 - - [16/Mar/2016:09:32:06 +0100] "GET /owncloud/owncloud/status.php HTTP/1.1" 404 306
10.160.0.23 - - [16/Mar/2016:09:32:16 +0100] "GET /owncloud/status.php HTTP/1.1" 404 297
10.160.0.23 - - [16/Mar/2016:09:32:16 +0100] "GET /owncloud/owncloud/status.php HTTP/1.1" 404 306
195.37.205.30 - - [16/Mar/2016:09:32:16 +0100] "GET /owncloud/status.php HTTP/1.1" 404 297
195.37.205.30 - - [16/Mar/2016:09:32:16 +0100] "GET /owncloud/owncloud/status.php HTTP/1.1" 404 306
10.160.0.14 - - [16/Mar/2016:09:32:22 +0100] "GET /owncloud/status.php HTTP/1.1" 404 297
10.160.0.85 - - [16/Mar/2016:09:32:22 +0100] "GET /owncloud/status.php HTTP/1.1" 404 297
10.160.0.85 - - [16/Mar/2016:09:32:22 +0100] "GET /owncloud/owncloud/status.php HTTP/1.1" 404 306
10.160.2.12 - - [16/Mar/2016:09:32:33 +0100] "GET /owncloud/status.php HTTP/1.1" 404 297
10.160.2.12 - - [16/Mar/2016:09:32:33 +0100] "GET /owncloud/owncloud/status.php HTTP/1.1" 404 306

```

#### ownCloud log (data/owncloud.log)
```
since no access, because "/owncloud not found", only messages from owncloud before upgrade ...
```

#### Browser log
```
Browser log
```

**Comment by tps800** [comment]
On CentOS 6 owncloud installs to /var/www/html/owncloud -- since this is within the server root the URL "http://<server>/owncloud" should be found in all cases without further configuration.

**Comment by LukasReschke** [comment]
> On CentOS 6 owncloud installs to /var/www/html/owncloud -- since this is within the server root the URL "http:///owncloud" should be found in all cases without further configuration.

This should be fixed with https://github.com/owncloud/core/pull/23065. You can get a daily containing these patches already at https://download.owncloud.org/community/owncloud-daily-stable9.tar.bz2

**Comment by tps800** [comment]
I've upgraded as adviced. It is NOT fixed!

BTW: owncloud occ now reports:
```
$ ./occ status
  - installed: true
  - version: 9.1.0.0
  - versionstring: 9.1.0 pre alpha
  - edition:
```
