### ISSUE TITLE
Code integrity check after changing maximum upload size via GUI

### ISSUE THREAD

**Issue by florianbeer** [owncloud/core#23321]
### Steps to reproduce
Following steps at [Uploading big files > 512MB](https://doc.owncloud.org/server/9.0/admin_manual/configuration_files/big_file_upload_configuration.html?highlight=upload%20big%20files#configuring-upload-limits-within-the-gui)
1. Ensure correct permisisons for `.htaccess` and `.user.ini`
2. Set Maximum upload size using the File handling input box within the administrative backend of ownCloud.

### Expected behaviour
Should not trigger code integrity check.

### Actual behaviour
ownCloud displays "Some files have not passed the integrity check" and lists `.htaccess` and `.user.ini` under INVALID_HASH.

### Server configuration
**Operating system**: Ubuntu 14.04 LTS

**Web server:** Apache

**Database:** MySQL

**PHP version:** 5.5

**ownCloud version:** 9.0.0

**Updated from an older ownCloud or fresh install:** Upgraded from 8.2.2

**Where did you install ownCloud from:** via apt-get from `https://download.owncloud.org/download/repositories/stable/xUbuntu_14.04/`

**Signing status (ownCloud 9.0 and above):** 

```
Results
=======
- core
	- INVALID_HASH
		- .htaccess
		- .user.ini

Raw output
==========
Array
(
    [core] => Array
        (
            [INVALID_HASH] => Array
                (
                    [.htaccess] => Array
                        (
                            [expected] => f40e7ca19cd76ff922ccd164e38f4d73806f66170cafa202fb470be225c813b4b242f4321da8a01bef1329e300acf3d137dbcbff058c501f166a2619031fc651
                            [current] => 811f46e2730e2f478a359192c518df0a90beed70ee3236ae281da00a3615f5c001a1aa464bc9d0b9112262e756a053e25fa7e479e119bbc44ea8d6ea9312187d
                        )

                    [.user.ini] => Array
                        (
                            [expected] => 0a557e3cdca4c2e3675deed761d79d109011dcdebbd9c7f6429f1d3476938ec95729543d7384651d1d0c48e26c5024cc5f517445920915a704ea748bdb903c5f
                            [current] => f90f406d920eb46f586ef705ff885f690c0546f6f22eba02ab24a2a91ce1c2cb1c48a504927f85a81fc7416bb89d47727d36d8fd75a13d81beb529f73941753b
                        )

                )

        )

)
```

**List of activated apps:**

```
Enabled:
  - activity: 2.2.1
  - comments: 0.2
  - dav: 0.1.5
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_external: 0.5.2
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - encryption
  - external
  - user_external
  - user_ldap
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "ocvzdlzxx1fp",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "version": "9.0.0.19",
        "dbtype": "mysql",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "ksl",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": "true",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379,
            "timeout": 0,
            "dbindex": 0
        },
        "secret": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "http:\/\/localhost",
        "mail_smtpmode": "sendmail",
        "asset-pipeline.enabled": true,
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "cloud",
        "log_type": "owncloud",
        "logtimezone": "EDT",
        "log_authfailip": true,
        "logfile": "\/var\/log\/owncloud.log",
        "loglevel": "2",
        "updatechecker": false,
        "maintenance": false
    }
}
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration

**Browser:** Safari Version 9.0.3 (11601.4.4)

**Operating system:** OS X 10.11.3 (15D21)

**Comment by MorrisJobke** [comment]
Fixed by https://github.com/owncloud/core/pull/23250 in 9.0.1 and 9.1.0

**Comment by ccoenen** [comment]
I just upgraded to 9.0.1, I still get this error. Are you sure this actually landed in 9.0.1?

**Comment by MorrisJobke** [comment]
cc @LukasReschke

**Comment by bcutter** [comment]
Still on OC v9.0.4. This whole integrity check stuff is really annoying by the way.
There is a fundamental need for manually touching files. E. g. https://github.com/owncloud/core/pull/18921#issuecomment-239785157

Or storing extra files which should be reachable - what would be the solution for this? I really like to adjust the .json file, but I guess that´s like playing with fire...
