### ISSUE TITLE
Can't set avatar picture

### ISSUE THREAD

**Issue by adrianvg** [owncloud/core#23602]
### Steps to reproduce
1. Login to OC9 web-gui. 
2. Go to Personal menu.
3. Click Select from Files (after first having checked the pic is a jpeg and below 20 MB).
4. Choose a pic and click Choose.
5. Click Choose as profile picture.

### Expected behaviour
The chosen pic should stick and be visible after clicking Choose as profile picture.

### Actual behaviour
Avatar image reverts to an alphabetical letter in a circle.

### Server configuration
**Operating system**: CentOS 6.7 x65

**Web server:** Httpd

**Database:** MySQL

**PHP version:** 5.5

**ownCloud version:** 9.0.0 (Stable)

**Updated from an older ownCloud or fresh install:** Yes

**Where did you install ownCloud from:** Via distros yum-system on the CLI.

**Signing status (ownCloud 9.0 and above):** "All checks passed"

```
"No errors have been found."
```

**List of activated apps:**

```
Enabled:
  - dav: 0.1.5
  - federatedfilesharing: 0.1.0
  - files: 1.4.4
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - updatenotification: 0.1.0
Disabled:
  - activity
  - comments
  - encryption
  - external
  - federation
  - files_external
  - files_videoplayer
  - firstrunwizard
  - gallery
  - notifications
  - provisioning_api
  - systemtags
  - templateeditor
  - user_external
  - user_ldap
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "ocfdfc96a2a2",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "company.com",
            "www.company.com",
            "192.168.0.9"
        ],
        "datadirectory": "\/home\/owncloud\/data",
        "dbtype": "mysql",
        "version": "9.0.0.19",
        "installed": true,
        "maxZipInputSize": 5261334937.6,
        "allowZipDownload": true,
        "forcessl": false,
        "theme": "",
        "maintenance": false,
        "mail_smtpmode": "php",
        "loglevel": 3,
        "secret": "***REMOVED SENSITIVE VALUE***",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "webmaster",
        "mail_domain": "company.com",
        "has_internet_connection": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "trashbin_retention_obligation": "15, auto",
        "updatechecker": false
    }
}

```

**Are you using external storage, if yes which one:** No

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** No

```

### Client configuration
**Browser:** Google Chrome

**Operating system:** CentOS 6.7 x86

#### ownCloud log (data/owncloud.log)
```
Error core
Exception: {"Exception":"OCP\\Files\\NotPermittedException","Message":"","Code":0,"Trace":"#0 \/var\/www\/html\/owncloud\/lib\/private\/avatar.php(121): OC\\Files\\Node\\Folder->newFile('avatar.png')\n#1 \/var\/www\/html\/owncloud\/core\/controller\/avatarcontroller.php(315): OC\\Avatar->set(Object(OC_Image))\n#2 [internal function]: OC\\Core\\Controller\\AvatarController->postCroppedAvatar(Array)\n#3 \/var\/www\/html\/owncloud\/lib\/private\/appframework\/http\/dispatcher.php(159): call_user_func_array(Array, Array)\n#4 \/var\/www\/html\/owncloud\/lib\/private\/appframework\/http\/dispatcher.php(89): OC\\AppFramework\\Http\\Dispatcher->executeController(Object(OC\\Core\\Controller\\AvatarController), 'postCroppedAvat...')\n#5 \/var\/www\/html\/owncloud\/lib\/private\/appframework\/app.php(110): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OC\\Core\\Controller\\AvatarController), 'postCroppedAvat...')\n#6 \/var\/www\/html\/owncloud\/lib\/private\/appframework\/routing\/routeactionhandler.php(45): OC\\AppFramework\\App::main('AvatarControlle...', 'postCroppedAvat...', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#7 [internal function]: OC\\AppFramework\\routing\\RouteActionHandler->__invoke(Array)\n#8 \/var\/www\/html\/owncloud\/lib\/private\/route\/router.php(273): call_user_func(Object(OC\\AppFramework\\routing\\RouteActionHandler), Array)\n#9 \/var\/www\/html\/owncloud\/lib\/base.php(873): OC\\Route\\Router->match('\/avatar\/cropped')\n#10 \/var\/www\/html\/owncloud\/index.php(39): OC::handleRequest()\n#11 {main}","File":"\/var\/www\/html\/owncloud\/lib\/private\/files\/node\/folder.php","Line":171}
```

**Comment by PVince81** [comment]
"NotPermittedException", possibly a permission issue, please double check your data folder and subfolder's permissions. The web server needs to be able to write there.

CC @icewind1991 @rullzer @blizzz

**Comment by adrianvg** [comment]
@PVince81: 
The permissions are set to apache:apache, 770.
This is okay I'm assuming, right?

**Comment by rullzer** [comment]
Should be fixed with https://github.com/owncloud/core/issues/23154

This is most likely the same as https://github.com/owncloud/core/issues/22978

**Comment by blizzz** [comment]
I agree, most likely the same as #22978, but the real issues are permissions as written in the filecache table. Those are not fixed by #23154. For now, for a manual fix see https://github.com/owncloud/core/issues/22978#issuecomment-195354190

**Comment by adrianvg** [comment]
Okay, thanks. Waiting for the fix in OC 9.0.2 then. :-)

**Comment by adrianvg** [comment]
Managed to fix it manually. This is for the records.
I copied the below files usign CLI, from another Owncloud 9-server that I run with no avatar-problem, to the one with the problem.
Octal permissions on the files are 644, 644 and 750 respectively.
The OC9-server with the avatar-problem immediately picked up the avatar at the subseqent webgui-login.

```
/home/owncloud/data/admin
-rw-r--r--     1 apache apache  1147 Mar 31 13:34 avatar.28.jpg
-rw-r--r--     1 apache apache  1170 Mar 31 13:34 avatar.32.jpg
-rwxr-x---     1 apache apache  6961 Mar 31 13:34 avatar.jpg
```
