### ISSUE TITLE
BackgroundScanner logs File not found

### ISSUE THREAD

**Issue by ms270169** [owncloud/core#25759]
I am working with Owncloud version: 9.1.0.15.

From time to time I find a strange log record in owncloud.log:
_{"reqId":"sTj8mJhpjolmbqlN51lG","remoteAddr":"","app":"files_antivirus","message":"OCA\Files_Antivirus\BackgroundScanner::run, exception: File with id \"4\" has not been found.","level":3,"time":"2016-08-10T12:54:23+00:00","method":"--","url":"--","user":"--"}_

A check of the oc_filecache table and oc_storages shows, that file with fileid 4 is a valid file.
This file is also also available via Web-Client. But why this strange log record?

Debugging shows some strange things in source code:

**File /var/www/owncloud/apps/files_antivirus/lib/backgroundscanner.php**
function run() is called making a database query to get all files which should be scanned.
In my case the result of this query is 4,6,7,8 and 9 (query limit 5 is used). Afterwards a view is created for the result. In the following try/catch the function getPath() in view.php is called with the first fileid 4.

**File /var/www/owncloud/lib/private/Files/View.php**
function getPath() is called with $id (=4).
Now it checks all mounts (probably taken from table oc_mounts) to get the correct path. But the needed path is not available in this mount array (why I don't know).
As result an exception is thrown

**File /var/www/owncloud/apps/files_antivirus/lib/backgroundscanner.php**
Back to function run() the exception breaks down the complete scan loop.

So my questions:
1) why does getPath() use mounts [] to find the correct path?
2) why is mounts [] not complete?
3) why should an exception for one fileid break down the complete scan?

I think, there are some code improvements needed, especially not to break down the scan if the path of one file is not locateable.

My recommendation is to add an inner try/catch.

**Comment by RealRancor** [comment]
@ms270169 I think this is the known and already reported bug in the files_antivirus app here:

https://github.com/owncloud/files_antivirus/issues/109

**Comment by ms270169** [comment]
[owncloud/files_antivirus#109](https://github.com/owncloud/files_antivirus/issues/109) is not the same bug, but it's an issue concerning the same functionality. In #109 file setup failed and as a result no files are found and scanned. In #25759 file setup works, files will be found, but the path building for one file fails and prevents background scan for all other following files. This is obviously a bug and at least the behavior to break down the scanning procedure for following files can be fixed where easily (additional inner try/catch).

**Comment by PVince81** [comment]
@VicDeo

**Comment by ms270169** [comment]
I have found some additional facts, concerning this bug. The problem occurs on each file of LDAP users (in contrast to normal users, their files will be scanned by antivirus as expected).

The problem is caused by the [getPath()](https://github.com/owncloud/core/blob/5a058f6c0ef64ff0272fcdb58478f9c6611d6819/lib/private/Files/View.php#L1676) function (in _lib/private/Files/View.php_)
There the functions [find()](https://github.com/owncloud/core/blob/5a058f6c0ef64ff0272fcdb58478f9c6611d6819//lib/private/Files/Mount/Manager.php#L70) and [findIn()](https://github.com/owncloud/core/blob/5a058f6c0ef64ff0272fcdb58478f9c6611d6819//lib/private/Files/Mount/Manager.php#L98) (in _lib/private/Files/Mount/Manager.php_) do not return the used mounts of a LDAP-user. As result of this malfunction the file cannot be found and an exception is thrown.

Maybe the problem is caused by the fact that I use the _"User Home Folder Naming Rule"_ in LDAP configuration (_LDAP->Advanced->SpecialAttributes_). That means, the home directory of ldap users is named with the LDAP-UID instead of the owncloud user ID. But in the table _oc_mounts_ alle records have a path starting with the owncloud user ID.

At the moment I insert a workarround. If _getPath()_ throws an exception, I build the path direct with database queries (_oc_filecache_, _oc_storages_, _oc_preferences_). That works, but could not be a final solution, because the bug may affect some other functions too.

**Comment by ms270169** [comment]
I think, a have found the cause for this bug, and it's a principal problem which should be fixed as soon as possible.

The list of files (for antivirus scanning) is created by a database query in [OCA\Files_Antivirus\BackgroundScannerr.run()](https://github.com/owncloud/files_antivirus/blob/master/lib/backgroundscanner.php#L49)  with a limit of 5 files), and it concerns files from **any** user.
This query determines the fileids of the files where antivirus scanning is required.
The function [OC\Files\View.getPath()](https://github.com/owncloud/core/blob/master/lib/private/Files/View.php#L1676)  is used to resolve the complete filename from fileid. This function uses the _MountManger_ in class [_OC\Files\Filesystem_.](https://github.com/owncloud/core/blob/master/lib/private/Files/Filesystem.php)
But the _MountManager_ only knows the mounts of **one** user. Therefore the resolving will fail if the fileid concerns a file in a mountpoint of another user.

**Conclusion:**
I am not sure if _owncloud/core_ is the right location to address this bug.
Because maybe it is only the result of wrong function usage in [class OCA\Files_Antivirus\BackgroundScannerr](https://github.com/owncloud/files_antivirus/blob/master/lib/backgroundscanner.php#L49).

Under normal circumstances it makes sense that only the mount points of the active user are available. In case of virus scanning each mount point would be needed to get the file path. Maybe it is better to avoid using mount points and to get the path in another way. If using mount points, it must be made sure, that the moint points of all users are created and available in Filesystem.

An additional problem is to abort the scan process, if something goes wrong with one file.
In my point of view it would be better to get all needed files out from database (without limit 5). Scan the list file for file until 5 files are successfully scanned.
If a file fails, report it in log as error and continue scanning the next file.

**Now the analysis in detail:**

1) At the beginning Antivirus Backgroundscanner is initialized and the function [OCA\Files_Antivirus\BackgroundScannerr.run()](https://github.com/owncloud/files_antivirus/blob/master/lib/backgroundscanner.php#L49) is called

2) [OCA\Files_Antivirus\BackgroundScannerr.initFS()](https://github.com/owncloud/files_antivirus/blob/master/lib/backgroundscanner.php#L118) is called
Here with line _$results = $this->userManager->search('', 2, 0);_ two users are determined from each backend (in my case owncloud user and ldap). For all found users (4 in my case, 2 owncloud and 2 ldap), the mount points are created and added in Filesystem. (Here are also some improvements possible; why continuing  searching ldap users when 2 owncloud users are already found?).
Only one user is taken (_$anyuser_) and line _\OC_Util::tearDownFS()_ is called. Here the mountpoints - added before - are removed (call of [OC\Files\Filesystem.clearMounts()](https://github.com/owncloud/core/blob/master/lib/private/Files/Filesystem.php#L487) ).
Now the function _\OC_Util::setupFS(...)_ with the one taken user is called, and the list of mounts in [OC\Files\Filesystem](https://github.com/owncloud/core/blob/master/lib/private/Files/Filesystem.php) now contains the root mountpoint and the mountpoint of the one taken user.

3) Back in run() the database query is done. The following SQL statement is executed:
```
SELECT fc."fileid" FROM "oc_filecache" fc 
  LEFT JOIN "oc_files_antivirus" fa ON fa."fileid" = fc."fileid"
  INNER JOIN "oc_storages" ss ON (fc."storage" = ss."numeric_id") AND ((ss."id" LIKE 'local::%') OR (ss."id" LIKE 'home::%'))
  WHERE (fc."mimetype" <> '2') AND ((fa."fileid" IS NULL) OR (fc."mtime" > fa."check_time")) AND (fc."path" LIKE 'files/%') AND (fc."size" <> "0")
  LIMIT 5";
```
It returns 0 to 5 fileids of files where antivirus scan is required.

4) A $view ( [OC\Files\View](https://github.com/owncloud/core/blob/master/lib/private/Files/View.php) ) with $root='' is created.

5) for each found fileid the _$view->getPath()_ function is called. If something goes wrong (and an exception is thrown) the while loop is left and background scan ends.
In [getPath()](https://github.com/owncloud/core/blob/master/lib/private/Files/View.php#L1676)  a call of [Filesystem::getMountManager()](https://github.com/owncloud/core/blob/master/lib/private/Files/Filesystem.php#L258) is done to get the MountManager (which only hold 2 mountpoints, see point 2 above).
For each mountpoint the storage/cache is taken and a call to _$cache->getPathById($id)_ trys to find the internal path of the fileid.
If it's the proper mount point the internal path is found, it will be combined with the mount point to _$fullpath_, transformed to a relative path and returned.
If it's a wrong mount point, no internal path is found and the next mount point is taken in the loop.

If no mount point fits (which is very probable, because only 2 mount points are known at the moment) a NotFoundException is thrown.

6) If the path of the file is returned, a file item is created. If the file doesn't exist, an exception is thrown.

7) The scanner is executed for the file item, created before.
If the file size exceeds the maximum streaming limit of clamav-daemon, another problem could occur.
See [https://github.com/owncloud/files_antivirus/issues/125](https://github.com/owncloud/files_antivirus/issues/125)

**Comment by PVince81** [comment]
@VicDeo please have a look.

I think in general the code is missing a call to `initMountPoints($targetUser)` before calling `View::getPath()`. This should solve the problem with the LDAP id not mapped properly.

**Comment by ms270169** [comment]
[\OC\Files\Filesystem::initMountPoints('')](https://github.com/owncloud/core/blob/master/lib/private/Files/Filesystem.php#L389) does not solve the problem, because it trys to mount only the logged in user. If no user is logged in an exception is thrown.

But the following lines before [$view = new \OC\Files\View('');](https://github.com/owncloud/files_antivirus/blob/master/lib/backgroundscanner.php#L96) solves the problem:
```
$users = \OC_User::getUsers();
foreach ($users as $user) {
  \OC\Files\Filesystem::initMountPoints($user);	
}
```

Disadvantage of this solution, a call to [\OC_User::getUsers()](https://github.com/owncloud/core/blob/master/lib/private/legacy/user.php#L487) may need a lot of time if a lot of ldap users are queried from ldap server. In my testcase it needs arround 30 seconds to get 120 users. After _getUsers()_ there are a lot of mountpoints available, but not every one. Without the foreach loop most of the fileids were found, but some lead to the _file not found exception_. After inserting the foreach loop every fileid was found properly.

Who can be addressed to fix this problem?

**Comment by PVince81** [comment]
You're right that iterating over all users can be quite heavy. However many background jobs do this already.

Best would be if @VicDeo could drop a line here as he knows more about the antivirus app and its background job.

**Comment by VicDeo** [comment]
@ms270169 mind testing https://github.com/owncloud/files_antivirus/pull/118 ?

**Comment by ms270169** [comment]
I have tested [https://github.com/owncloud/files_antivirus/pull/118](https://github.com/owncloud/files_antivirus/pull/118).
See [https://github.com/owncloud/files_antivirus/pull/118#issuecomment-240321672](https://github.com/owncloud/files_antivirus/pull/118#issuecomment-240321672)

**Comment by VicDeo** [comment]
Closing as fixed in 9.2/9.1.1/9.0.6
