### ISSUE TITLE
Official Repository's not updated (again)

### ISSUE THREAD

**Issue by bitking** [owncloud/core#26636]
Hi there,

The ubuntu repository is not updated with the latest owncloud 9.1.2.

This is getting a recurring theme, can anyone elaborate on this and fix it asap?

Thanks.

**Comment by codesmaker** [comment]
The Debian repository isn't updated too.

**Comment by DeepDiver1975** [comment]
Please provide links to the repositories you are using.  Thx

**Comment by bitking** [comment]
The repository's published on owncloud.org. (https://owncloud.org/install/#edition)

So:

https://download.owncloud.org/download/repositories/stable/owncloud/

**Comment by Kawohl** [comment]
@crrodriguez

**Comment by fjbeteiligung** [comment]
Actually *none* of the repositories in the stable channel has been updated. All seven of them sit happily on 9.1.1.

**Comment by bitking** [comment]
Yes, its all repository's.

**Comment by bitking** [comment]
Any ETA?

**Comment by PVince81** [comment]
Weird, but I managed to update my instance to 9.1.2 many days ago.

Apparently they landed in the "testing" repo instead of "stable" ?? https://download.owncloud.org/download/repositories/testing/openSUSE_Leap_42.1/noarch/

**Comment by crrodriguez** [comment]
I do not understand.. as far as I understood it last week we published all packages ...*sigh*

**Comment by chrone81** [comment]
Yes, http://download.owncloud.org/download/repositories/stable/Ubuntu_16.04/all/ last modified still showing 2016-09-27.

**Comment by RealRancor** [comment]
> This only affects 9.1.2 right ?

Nope, Its also 9.0.6, 8.2.9, 8.1.11 and 8.0.16. So the complete releases got missed:

https://download.owncloud.org/download/repositories/9.0/Ubuntu_16.04/all/
https://download.owncloud.org/download/repositories/8.2/Ubuntu_16.04/all/
http://download.opensuse.org/repositories/isv:/ownCloud:/community:/8.1/xUbuntu_16.04/
http://download.opensuse.org/repositories/isv:/ownCloud:/community:/8.0/xUbuntu_16.04/

**Comment by crrodriguez** [comment]
Whoa. got what the problem was. I fixed it.

**Comment by RealRancor** [comment]
And the releases are already there. 👍

**Comment by PVince81** [comment]
Thanks @crrodriguez
