### ISSUE TITLE
[Mac + iOS client] Connection Closed, web interface works fine

### ISSUE THREAD

**Issue by ortonomy** [owncloud/core#26883]
### Steps to reproduce
1. Download Mac or iOS client
2. Try to connect to my owncloud instance at https://cloud.geligelu.com using client

### Expected behaviour
I should be able to log in and sync to the owncloud instance using the desktop or phone client.

### Actual behaviour
Clients simply respond 'connection closed'. No error message, no feedback. Simply won't log in.

### Server configuration
**Operating system**:
cloud linux

**Web server:**
Apache 2.2.31

**Database:**
My SQL

**PHP version:**
Php 5.6

**ownCloud version:** (see ownCloud admin page)
9.1.3

**Updated from an older ownCloud or fresh install:**
Updated

**Where did you install ownCloud from:**
Sever package uploaded to server. Downloaded from owncloud.com

**Signing status (ownCloud 9.0 and above):**

```
No errors have been found..
```

**List of activated apps:**

```
Enabled:
  - activity: 2.3.2
  - comments: 0.3.0
  - dav: 0.2.7
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.10.0
  - files_texteditor: 2.1
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - notifications: 0.3.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.1
  - updatenotification: 0.2.1
Disabled:
  - encryption
  - external
  - files_antivirus
  - files_external
  - user_external
  - user_ldap
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "oc4rpucjji05",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.geligelu.com",
            "geligelu.com"
        ],
        "datadirectory": "\/home\/techfact\/public_html\/cloud\/data",
        "overwrite.cli.url": "http:\/\/cloud.geligelu.com",
        "dbtype": "mysql",
        "version": "9.1.3.1",
        "dbname": "techfact_owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "theme": "",
        "loglevel": 0,
        "maintenance": false,
        "mail_from_address": "cloud",
        "mail_smtpmode": "php",
        "mail_domain": "geligelu.com",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "trashbin_retention_obligation": "auto",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** 
no

**Are you using an external user-backend, if yes which one:** 
no

```

```

### Client configuration
**Browser:**
Chrome 55

**Operating system:**
macOS Sierra 10.12.2
#### Web server error log
```
[Wed Dec 28 23:50:13.205958 2016] [core:crit] [pid 860267:tid 140353772377856] (13)Permission denied: [client 192.240.127.83:12728] AH00529: /home/techfact/public_html/cloud/data/.htaccess pcfg_openfile: unable to check htaccess file, ensure it is readable and that '/home/techfact/public_html/cloud/data/' is executable
[Wed Dec 28 23:43:07.181696 2016] [core:crit] [pid 860269:tid 140354051647232] (13)Permission denied: [client 192.240.127.83:9436] AH00529: /home/techfact/public_html/cloud/data/.htaccess pcfg_openfile: unable to check htaccess file, ensure it is readable and that '/home/techfact/public_html/cloud/data/' is executable
[Wed Dec 28 23:37:48.050282 2016] [core:crit] [pid 860263:tid 140353772377856] (13)Permission denied: [client 192.240.127.83:7729] AH00529: /home/techfact/public_html/cloud/data/.htaccess pcfg_openfile: unable to check htaccess file, ensure it is readable and that '/home/techfact/public_html/cloud/data/' is executable
[Wed Dec 28 23:37:28.740046 2016] [core:crit] [pid 860272:tid 140353940215552] (13)Permission denied: [client 192.240.127.83:1806] AH00529: /home/techfact/public_html/cloud/data/.htaccess pcfg_openfile: unable to check htaccess file, ensure it is readable and that '/home/techfact/public_html/cloud/data/' is executable
[Wed Dec 28 23:26:20.794645 2016] [core:crit] [pid 860270:tid 140353803847424] (13)Permission denied: [client 192.240.127.83:17043] AH00529: /home/techfact/public_html/cloud/data/.htaccess pcfg_openfile: unable to check htaccess file, ensure it is readable and that '/home/techfact/public_html/cloud/data/' is executable
[Wed Dec 28 23:21:23.041641 2016] [core:crit] [pid 860270:tid 140353898256128] (13)Permission denied: [client 192.240.127.83:14088] AH00529: /home/techfact/public_html/cloud/data/.htaccess pcfg_openfile: unable to check htaccess file, ensure it is readable and that '/home/techfact/public_html/cloud/data/' is executable
[Wed Dec 28 23:19:36.225311 2016] [core:crit] [pid 860264:tid 140353761888000] (13)Permission denied: [client 192.240.127.83:25222] AH00529: /home/techfact/public_html/cloud/data/.htaccess pcfg_openfile: unable to check htaccess file, ensure it is readable and that '/home/techfact/public_html/cloud/data/' is executable
[Wed Dec 28 22:40:18.114814 2016] [core:crit] [pid 860269:tid 140353866786560] (13)Permission denied: [client 192.240.127.83:30142] AH00529: /home/techfact/public_html/cloud/data/.htaccess pcfg_openfile: unable to check htaccess file, ensure it is readable and that '/home/techfact/public_html/cloud/data/' is executable
 Owncloud\Updater\Controller\IndexController->dispatch() at /home/techfact/public_html/cloud/updater/index.php:29
 Owncloud\Updater\Controller\IndexController->ajaxAction() at /home/techfact/public_html/cloud/updater/src/Controller/IndexController.php:88
 Symfony\Component\Console\Application->run() at /home/techfact/public_html/cloud/updater/src/Controller/IndexController.php:150
 Owncloud\Updater\Console\Application->doRun() at /home/techfact/public_html/cloud/updater/vendor/symfony/console/Application.php:120
 Owncloud\Updater\Utils\ConfigReader->init() at /home/techfact/public_html/cloud/updater/src/Console/Application.php:154
 Owncloud\Updater\Utils\ConfigReader->load() at /home/techfact/public_html/cloud/updater/src/Utils/ConfigReader.php:50
 Owncloud\Updater\Utils\OccRunner->runJson() at /home/techfact/public_html/cloud/updater/src/Utils/ConfigReader.php:106
 Owncloud\Updater\Utils\OccRunner->run() at /home/techfact/public_html/cloud/updater/src/Utils/OccRunner.php:77
 Owncloud\Updater\Utils\OccRunner->runAsRequest() at /home/techfact/public_html/cloud/updater/src/Utils/OccRunner.php:70
 GuzzleHttp\Client->send() at /home/techfact/public_html/cloud/updater/src/Utils/OccRunner.php:103
 GuzzleHttp\RequestFsm->__invoke() at /home/techfact/public_html/cloud/updater/vendor/guzzlehttp/guzzle/src/Client.php:165
 GuzzleHttp\Ring\Client\Middleware::GuzzleHttp\Ring\Client\{closure}() at /home/techfact/public_html/cloud/updater/vendor/guzzlehttp/guzzle/src/RequestFsm.php:129
 GuzzleHttp\Ring\Client\Middleware::GuzzleHttp\Ring\Client\{closure}() at /home/techfact/public_html/cloud/updater/vendor/guzzlehttp/ringphp/src/Client/Middleware.php:30
 GuzzleHttp\Ring\Client\CurlHandler->__invoke() at /home/techfact/public_html/cloud/updater/vendor/guzzlehttp/ringphp/src/Client/Middleware.php:54
 GuzzleHttp\Ring\Client\CurlHandler->_invokeAsArray() at /home/techfact/public_html/cloud/updater/vendor/guzzlehttp/ringphp/src/Client/CurlHandler.php:68
 GuzzleHttp\Ring\Client\CurlFactory::createResponse() at /home/techfact/public_html/cloud/updater/vendor/guzzlehttp/ringphp/src/Client/CurlHandler.php:96
 GuzzleHttp\Ring\Client\CurlFactory::createErrorResponse() at /home/techfact/public_html/cloud/updater/vendor/guzzlehttp/ringphp/src/Client/CurlFactory.php:91
 () at /home/techfact/public_html/cloud/updater/vendor/guzzlehttp/ringphp/src/Client/CurlFactory.php:127
 Owncloud\Updater\Controller\IndexController->dispatch() at /home/techfact/public_html/cloud/updater/index.php:29
 Owncloud\Updater\Controller\IndexController->ajaxAction() at /home/techfact/public_html/cloud/updater/src/Controller/IndexController.php:88
 Symfony\Component\Console\Application->run() at /home/techfact/public_html/cloud/updater/src/Controller/IndexController.php:150
 Owncloud\Updater\Console\Application->doRun() at /home/techfact/public_html/cloud/updater/vendor/symfony/console/Application.php:120
 Owncloud\Updater\Utils\ConfigReader->init() at /home/techfact/public_html/cloud/updater/src/Console/Application.php:154
 Owncloud\Updater\Utils\ConfigReader->load() at /home/techfact/public_html/cloud/updater/src/Utils/ConfigReader.php:50
 Owncloud\Updater\Utils\OccRunner->runJson() at /home/techfact/public_html/cloud/updater/src/Utils/ConfigReader.php:106
 Owncloud\Updater\Utils\OccRunner->run() at /home/techfact/public_html/cloud/updater/src/Utils/OccRunner.php:77
 Owncloud\Updater\Utils\OccRunner->runAsRequest() at /home/techfact/public_html/cloud/updater/src/Utils/OccRunner.php:70
 GuzzleHttp\Client->send() at /home/techfact/public_html/cloud/updater/src/Utils/OccRunner.php:103
 GuzzleHttp\RequestFsm->__invoke() at /home/techfact/public_html/cloud/updater/vendor/guzzlehttp/guzzle/src/Client.php:165
 GuzzleHttp\Message\FutureResponse::proxy() at /home/techfact/public_html/cloud/updater/vendor/guzzlehttp/guzzle/src/RequestFsm.php:135
 GuzzleHttp\Ring\Future\CompletedFutureValue->then() at /home/techfact/public_html/cloud/updater/vendor/guzzlehttp/guzzle/src/Message/FutureResponse.php:43
 React\Promise\FulfilledPromise->then() at /home/techfact/public_html/cloud/updater/vendor/guzzlehttp/ringphp/src/Future/CompletedFutureValue.php:55
 GuzzleHttp\RequestFsm->GuzzleHttp\{closure}() at /home/techfact/public_html/cloud/updater/vendor/react/promise/src/FulfilledPromise.php:25
 GuzzleHttp\RequestFsm->__invoke() at /home/techfact/public_html/cloud/updater/vendor/guzzlehttp/guzzle/src/RequestFsm.php:132
 GuzzleHttp\Exception\RequestException::wrapException() at /home/techfact/public_html/cloud/updater/vendor/guzzlehttp/guzzle/src/RequestFsm.php:104
 () at /home/techfact/public_html/cloud/updater/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:51
 Owncloud\Updater\Controller\IndexController->dispatch() at /home/techfact/public_html/cloud/updater/index.php:29
 Owncloud\Updater\Controller\IndexController->ajaxAction() at /home/techfact/public_html/cloud/updater/src/Controller/IndexController.php:88
 Symfony\Component\Console\Application->run() at /home/techfact/public_html/cloud/updater/src/Controller/IndexController.php:150
 Owncloud\Updater\Console\Application->doRun() at /home/techfact/public_html/cloud/updater/vendor/symfony/console/Application.php:120
 Owncloud\Updater\Utils\ConfigReader->init() at /home/techfact/public_html/cloud/updater/src/Console/Application.php:154
 Owncloud\Updater\Utils\ConfigReader->load() at /home/techfact/public_html/cloud/updater/src/Utils/ConfigReader.php:50
 Owncloud\Updater\Utils\OccRunner->runJson() at /home/techfact/public_html/cloud/updater/src/Utils/ConfigReader.php:106
 Owncloud\Updater\Utils\OccRunner->run() at /home/techfact/public_html/cloud/updater/src/Utils/OccRunner.php:77
 Owncloud\Updater\Utils\OccRunner->runAsRequest() at /home/techfact/public_html/cloud/updater/src/Utils/OccRunner.php:70
 GuzzleHttp\Client->send() at /home/techfact/public_html/cloud/updater/src/Utils/OccRunner.php:103
 GuzzleHttp\RequestFsm->__invoke() at /home/techfact/public_html/cloud/updater/vendor/guzzlehttp/guzzle/src/Client.php:165
 GuzzleHttp\Ring\Client\Middleware::GuzzleHttp\Ring\Client\{closure}() at /home/techfact/public_html/cloud/updater/vendor/guzzlehttp/guzzle/src/RequestFsm.php:129
 GuzzleHttp\Ring\Client\Middleware::GuzzleHttp\Ring\Client\{closure}() at /home/techfact/public_html/cloud/updater/vendor/guzzlehttp/ringphp/src/Client/Middleware.php:30
 GuzzleHttp\Ring\Client\CurlHandler->__invoke() at /home/techfact/public_html/cloud/updater/vendor/guzzlehttp/ringphp/src/Client/Middleware.php:54
 GuzzleHttp\Ring\Client\CurlHandler->_invokeAsArray() at /home/techfact/public_html/cloud/updater/vendor/guzzlehttp/ringphp/src/Client/CurlHandler.php:68
 GuzzleHttp\Ring\Client\CurlFactory::createResponse() at /home/techfact/public_html/cloud/updater/vendor/guzzlehttp/ringphp/src/Client/CurlHandler.php:96
 GuzzleHttp\Ring\Client\CurlFactory::createErrorResponse() at /home/techfact/public_html/cloud/updater/vendor/guzzlehttp/ringphp/src/Client/CurlFactory.php:91
 () at /home/techfact/public_html/cloud/updater/vendor/guzzlehttp/ringphp/src/Client/CurlFactory.php:127
 Owncloud\Updater\Controller\IndexController->dispatch() at /home/techfact/public_html/cloud/updater/index.php:29
 Owncloud\Updater\Controller\IndexController->ajaxAction() at /home/techfact/public_html/cloud/updater/src/Controller/IndexController.php:88
 Symfony\Component\Console\Application->run() at /home/techfact/public_html/cloud/updater/src/Controller/IndexController.php:150
 Owncloud\Updater\Console\Application->doRun() at /home/techfact/public_html/cloud/updater/vendor/symfony/console/Application.php:120
 Owncloud\Updater\Utils\ConfigReader->init() at /home/techfact/public_html/cloud/updater/src/Console/Application.php:154
 Owncloud\Updater\Utils\ConfigReader->load() at /home/techfact/public_html/cloud/updater/src/Utils/ConfigReader.php:50
 Owncloud\Updater\Utils\OccRunner->runJson() at /home/techfact/public_html/cloud/updater/src/Utils/ConfigReader.php:106
 Owncloud\Updater\Utils\OccRunner->run() at /home/techfact/public_html/cloud/updater/src/Utils/OccRunner.php:77
 Owncloud\Updater\Utils\OccRunner->runAsRequest() at /home/techfact/public_html/cloud/updater/src/Utils/OccRunner.php:70
 GuzzleHttp\Client->send() at /home/techfact/public_html/cloud/updater/src/Utils/OccRunner.php:103
 GuzzleHttp\RequestFsm->__invoke() at /home/techfact/public_html/cloud/updater/vendor/guzzlehttp/guzzle/src/Client.php:165
 GuzzleHttp\Message\FutureResponse::proxy() at /home/techfact/public_html/cloud/updater/vendor/guzzlehttp/guzzle/src/RequestFsm.php:135
 GuzzleHttp\Ring\Future\CompletedFutureValue->then() at /home/techfact/public_html/cloud/updater/vendor/guzzlehttp/guzzle/src/Message/FutureResponse.php:43
 React\Promise\FulfilledPromise->then() at /home/techfact/public_html/cloud/updater/vendor/guzzlehttp/ringphp/src/Future/CompletedFutureValue.php:55
 GuzzleHttp\RequestFsm->GuzzleHttp\{closure}() at /home/techfact/public_html/cloud/updater/vendor/react/promise/src/FulfilledPromise.php:25
 GuzzleHttp\RequestFsm->__invoke() at /home/techfact/public_html/cloud/updater/vendor/guzzlehttp/guzzle/src/RequestFsm.php:132
 GuzzleHttp\Exception\RequestException::wrapException() at /home/techfact/public_html/cloud/updater/vendor/guzzlehttp/guzzle/src/RequestFsm.php:104
 () at /home/techfact/public_html/cloud/updater/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:51
 Owncloud\Updater\Controller\IndexController->dispatch() at /home/techfact/public_html/cloud/updater/index.php:29
 Owncloud\Updater\Controller\IndexController->ajaxAction() at /home/techfact/public_html/cloud/updater/src/Controller/IndexController.php:88
 Symfony\Component\Console\Application->run() at /home/techfact/public_html/cloud/updater/src/Controller/IndexController.php:150
 Owncloud\Updater\Console\Application->doRun() at /home/techfact/public_html/cloud/updater/vendor/symfony/console/Application.php:120
 Owncloud\Updater\Utils\ConfigReader->init() at /home/techfact/public_html/cloud/updater/src/Console/Application.php:154
 Owncloud\Updater\Utils\ConfigReader->load() at /home/techfact/public_html/cloud/updater/src/Utils/ConfigReader.php:50
 Owncloud\Updater\Utils\OccRunner->runJson() at /home/techfact/public_html/cloud/updater/src/Utils/ConfigReader.php:106
 Owncloud\Updater\Utils\OccRunner->run() at /home/techfact/public_html/cloud/updater/src/Utils/OccRunner.php:77
 Owncloud\Updater\Utils\OccRunner->runAsRequest() at /home/techfact/public_html/cloud/updater/src/Utils/OccRunner.php:70
 GuzzleHttp\Client->send() at /home/techfact/public_html/cloud/updater/src/Utils/OccRunner.php:103
 GuzzleHttp\RequestFsm->__invoke() at /home/techfact/public_html/cloud/updater/vendor/guzzlehttp/guzzle/src/Client.php:165
 GuzzleHttp\Ring\Client\Middleware::GuzzleHttp\Ring\Client\{closure}() at /home/techfact/public_html/cloud/updater/vendor/guzzlehttp/guzzle/src/RequestFsm.php:129
 GuzzleHttp\Ring\Client\Middleware::GuzzleHttp\Ring\Client\{closure}() at /home/techfact/public_html/cloud/updater/vendor/guzzlehttp/ringphp/src/Client/Middleware.php:30
 GuzzleHttp\Ring\Client\CurlHandler->__invoke() at /home/techfact/public_html/cloud/updater/vendor/guzzlehttp/ringphp/src/Client/Middleware.php:54
 GuzzleHttp\Ring\Client\CurlHandler->_invokeAsArray() at /home/techfact/public_html/cloud/updater/vendor/guzzlehttp/ringphp/src/Client/CurlHandler.php:68
 GuzzleHttp\Ring\Client\CurlFactory::createResponse() at /home/techfact/public_html/cloud/updater/vendor/guzzlehttp/ringphp/src/Client/CurlHandler.php:96
 GuzzleHttp\Ring\Client\CurlFactory::createErrorResponse() at /home/techfact/public_html/cloud/updater/vendor/guzzlehttp/ringphp/src/Client/CurlFactory.php:91
 () at /home/techfact/public_html/cloud/updater/vendor/guzzlehttp/ringphp/src/Client/CurlFactory.php:127
 Owncloud\Updater\Controller\IndexController->dispatch() at /home/techfact/public_html/cloud/updater/index.php:29
 Owncloud\Updater\Controller\IndexController->ajaxAction() at /home/techfact/public_html/cloud/updater/src/Controller/IndexController.php:88
 Symfony\Component\Console\Application->run() at /home/techfact/public_html/cloud/updater/src/Controller/IndexController.php:150
 Owncloud\Updater\Console\Application->doRun() at /home/techfact/public_html/cloud/updater/vendor/symfony/console/Application.php:120
 Owncloud\Updater\Utils\ConfigReader->init() at /home/techfact/public_html/cloud/updater/src/Console/Application.php:154
 Owncloud\Updater\Utils\ConfigReader->load() at /home/techfact/public_html/cloud/updater/src/Utils/ConfigReader.php:50
 Owncloud\Updater\Utils\OccRunner->runJson() at /home/techfact/public_html/cloud/updater/src/Utils/ConfigReader.php:106
 Owncloud\Updater\Utils\OccRunner->run() at /home/techfact/public_html/cloud/updater/src/Utils/OccRunner.php:77
 Owncloud\Updater\Utils\OccRunner->runAsRequest() at /home/techfact/public_html/cloud/updater/src/Utils/OccRunner.php:70
 GuzzleHttp\Client->send() at /home/techfact/public_html/cloud/updater/src/Utils/OccRunner.php:103
 GuzzleHttp\RequestFsm->__invoke() at /home/techfact/public_html/cloud/updater/vendor/guzzlehttp/guzzle/src/Client.php:165
 GuzzleHttp\Message\FutureResponse::proxy() at /home/techfact/public_html/cloud/updater/vendor/guzzlehttp/guzzle/src/RequestFsm.php:135
 GuzzleHttp\Ring\Future\CompletedFutureValue->then() at /home/techfact/public_html/cloud/updater/vendor/guzzlehttp/guzzle/src/Message/FutureResponse.php:43
 React\Promise\FulfilledPromise->then() at /home/techfact/public_html/cloud/updater/vendor/guzzlehttp/ringphp/src/Future/CompletedFutureValue.php:55
 GuzzleHttp\RequestFsm->GuzzleHttp\{closure}() at /home/techfact/public_html/cloud/updater/vendor/react/promise/src/FulfilledPromise.php:25
 GuzzleHttp\RequestFsm->__invoke() at /home/techfact/public_html/cloud/updater/vendor/guzzlehttp/guzzle/src/RequestFsm.php:132
 GuzzleHttp\Exception\RequestException::wrapException() at /home/techfact/public_html/cloud/updater/vendor/guzzlehttp/guzzle/src/RequestFsm.php:104
 () at /home/techfact/public_html/cloud/updater/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:51
[Wed Dec 28 22:34:46.995317 2016] [core:crit] [pid 467278:tid 140353866786560] (13)Permission denied: [client 192.240.127.83:39719] AH00529: /home/techfact/public_html/cloud/data/.htaccess pcfg_openfile: unable to check htaccess file, ensure it is readable and that '/home/techfact/public_html/cloud/data/' is executable
[Wed Dec 28 22:05:18.152750 2016] [core:crit] [pid 467278:tid 140353961195264] (13)Permission denied: [client 192.240.127.83:36403] AH00529: /home/techfact/public_html/cloud/data/.htaccess pcfg_openfile: unable to check htaccess file, ensure it is readable and that '/home/techfact/public_html/cloud/data/' is executable
[Wed Dec 28 21:54:38.397394 2016] [core:crit] [pid 467307:tid 140353919235840] (13)Permission denied: [client 192.240.127.83:20388] AH00529: /home/techfact/public_html/cloud/data/.htaccess pcfg_openfile: unable to check htaccess file, ensure it is readable and that '/home/techfact/public_html/cloud/data/' is executable
```

#### ownCloud log (data/owncloud.log)
```

Debug	webdav	Exception: {"Message":"HTTP\/1.1 401 No 'Authorization: Basic' header found. Either the client didn't send one, or the server is mis-configured","Exception":"Sabre\\DAV\\Exception\\NotAuthenticated","Code":0,"Trace":"#0 [internal function]: Sabre\\DAV\\Auth\\Plugin->beforeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#1 \/home\/techfact\/public_html\/cloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#2 \/home\/techfact\/public_html\/cloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(446): Sabre\\Event\\EventEmitter->emit('beforeMethod', Array)\n#3 \/home\/techfact\/public_html\/cloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(248): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#4 \/home\/techfact\/public_html\/cloud\/apps\/dav\/appinfo\/v1\/webdav.php(56): Sabre\\DAV\\Server->exec()\n#5 \/home\/techfact\/public_html\/cloud\/remote.php(164): require_once('\/home\/techfact\/...')\n#6 {main}","File":"\/home\/techfact\/public_html\/cloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Auth\/Plugin.php","Line":188,"User":false}	2016-12-29T04:50:03+00:00
```

**Comment by MrKoopie** [comment]
@geligelu This should resolve it: https://github.com/owncloud/core/pull/26885

**Comment by geligelu** [comment]
@MrKoopie  - should I just put this in the .htaccess file at the root of my owncloud install?

**Comment by geligelu** [comment]
@MrKoopie  - added changed code to my .htaccess file and still get the same error, so don't know if the two errors were related...

**Comment by geligelu** [comment]
Still the same error:

```
Exception: {"Message":"HTTP\/1.1 401 No 'Authorization: Basic' header found. Either the client didn't send one, or the server is mis-configured","Exception":"Sabre\\DAV\\Exception\\NotAuthenticated","Code":0,"Trace":"#0 [internal function]: Sabre\\DAV\\Auth\\Plugin->beforeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#1 \/home\/techfact\/public_html\/cloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#2 \/home\/techfact\/public_html\/cloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(446): Sabre\\Event\\EventEmitter->emit('beforeMethod', Array)\n#3 \/home\/techfact\/public_html\/cloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(248): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#4 \/home\/techfact\/public_html\/cloud\/apps\/dav\/appinfo\/v1\/webdav.php(56): Sabre\\DAV\\Server->exec()\n#5 \/home\/techfact\/public_html\/cloud\/remote.php(164): require_once('\/home\/techfact\/...')\n#6 {main}","File":"\/home\/techfact\/public_html\/cloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Auth\/Plugin.php","Line":188,"User":false}
```

**Comment by MrKoopie** [comment]
@geligelu Can you confirm if you are using lsphp in CloudLinux?

**Comment by geligelu** [comment]
@MrKoopie - I'm using cloudlinux (or better still, my hosting provider is), but lsphp is not in my cpanel config. I've found other issues with a similar error suggesting this may have something to do with mod_php vs. FastCGI, but I've confirmed with them that their server has been using FastCGI for years. However, they recently upgraded my cPanel to EasyApache 4 from 3, and that has coincided with the loss of service. The trouble is, the logs are not helpful AT ALL.

**Comment by geligelu** [comment]
OK, so I've managed to fix this - it's something to do with my host. They recently upgraded the version of cPanel + apache and this changed the PHP handler from suPHP to some other CGI. This meant that PHP was being executed as 'nobody' rather than the user of the web server. Any chance that you can implement better error reporting for this kind of thing? It was pretty difficult to track down. (or at least put it in the system requirements.)

**Comment by PVince81** [comment]
solved with https://github.com/owncloud/core/pull/26885
