### ISSUE TITLE
misleading trusted domains error

### ISSUE THREAD

**Issue by jnweiger** [owncloud/core#29243]
https://demo.owncloud.com//status.php

![err1](https://user-images.githubusercontent.com/1108546/31546955-cc78d88c-b025-11e7-96f2-a4a038546d5c.png)

This should be a more generic url error, maybe handled by a redirect to the login page, as many other misspelled urls already do.

I don't see why the domain should be considered not trusted in this case. The extra slash is an error with the path, not with the domain.

**Comment by jnweiger** [comment]
Also, the button [Add "demo.owncloud.com" as trusted domain] is wrong:
* demo.owncloud.com is already a trusted domain here. 
* A click on the button sends you to https://status.php/settings/admin?trustDomain=demo.owncloud.com - which is a non-existant domain.

(technically a different issue ...)

**Comment by kdslkdsaldsal** [comment]
@jnweiger At least the "add xyz" button is gone in 10.0.3 https://github.com/owncloud/core/pull/28421 where demo.owncloud.org is still on 10.0.2. Maybe the doubled slash is also fixed in 10.0.3?

**Comment by PVince81** [comment]
The doubled slash is likely not fixed, it's an old hard to fix routing bug (from what I heard): https://github.com/owncloud/core/issues/17384
