### ISSUE TITLE
[QA] openIdConnect error on macOS Mojave 10.14.6

### ISSUE THREAD

**Issue by gabi18** [owncloud/core#38519]
Tested on: macOS 10.14.6
Safari version:  12.1.2

Server version: 10.7.0 beta2
 
Steps to reproduce:
- sign in on aad.portal.azure.com
- remove all browser cookies
- try to login in on 'oc-10-7-0-beta2...'

Result: 
Browser shows "Error in OpenIdConnect:Unable to determine state"

![Azure_Error_Safari_12-1](https://user-images.githubusercontent.com/75983861/111168969-da623f00-85a2-11eb-997b-0cae41de9868.png)

**Comment by gabi18** [comment]
Works as expected on macOS BigSur 11.1 / 11.2.3.

**Comment by micbar** [comment]
@gabi18 should be fixed in 10.7.0RC1

**Comment by gabi18** [comment]
The error is still reproducible on macOS 10.14.6 with 10.7.0RC1.

![Bildschirmfoto 2021-03-17 um 07 45 29](https://user-images.githubusercontent.com/75983861/111427831-faa31280-86f6-11eb-8c86-fa59a45a126d.png)

**Comment by micbar** [comment]
@jw has the server configured the same-site none policy?

**Comment by micbar** [comment]
https://github.com/owncloud/docs/pull/3360/files

**Comment by jnweiger** [comment]
I have this in my config.php
![image](https://user-images.githubusercontent.com/1108546/111452568-f2f16700-8712-11eb-86f1-cca758f86b43.png)

**Comment by gabi18** [comment]
![Azure_Client_Mac_Mojave](https://user-images.githubusercontent.com/75983861/111455281-e4587f00-8715-11eb-9740-50681c090c0c.png)

**Comment by gabi18** [comment]
FabLab Client login is successful when logging in the first time.

After 'Account' 'Log out' and 'Login in' again the error from above in shown.

**Comment by gabi18** [comment]
The error also persists on a freshly installed macOS Mojave virtual machine without having logged in to azure portal once before trying to login to https://oc-10-7-0-rc1-oidc-2-0-0-20210316.jw-qa.owncloud.works.

**Comment by micbar** [comment]
according to @hodyroff we can only support the latest browser.

So Safari on Mojave is officially no supported.

@jnweiger @pmaier1

**Comment by jnweiger** [comment]
Okay. Käs closed.
