### ISSUE TITLE
Core CI start failing in apiTranslation suite

### ISSUE THREAD

**Issue by amrita-shrestha** [owncloud/core#39931]
Core CI start failing in apTranslation suite (translation.feature file) 

- features/apiTranslation/translation.feature:24
- features/apiTranslation/translation.feature:28

https://drone.owncloud.com/owncloud/core/35125/82/13
```    Unexpected OCS status message:"Wrong share ID, share doesn't exist" in response
        Failed asserting that two strings are equal.
        --- Expected
        +++ Actual
        @@ @@
        -'Mauvais ID de partage, le partage n'existe pas'
        +'Wrong share ID, share doesn't exist'
```
From  **`git bisect`** it found that 848088e781ece6cb8f59f2dfd162ce9469bc41fe **`is the first bad commit`**

**Comment by saw-jan** [comment]
Test failed for `fr_FR` language.
```bash
      | new         | fr-FR    |
        Unexpected OCS status message :"Wrong share ID, share doesn't exist" in response
        Failed asserting that two strings are equal.
        --- Expected
        +++ Actual
        @@ @@
        -'Mauvais ID de partage, le partage n'existe pas'
        +'Wrong share ID, share doesn't exist'
```

**Comment by saw-jan** [comment]
Fixed by new transifex commit?

**Comment by kiranparajuli589** [comment]
acceptance tests only run for PRs and tags.
```
"trigger": {
    "ref": [
        "refs/pull/**",
        "refs/tags/**",
    ],
},
```
running ci for commits like `[tx] updated from transifex` will not restrict the merge but still, we can know about the failure on the ci run for that same commit.

**Comment by kiranparajuli589** [comment]
> Fixed by new transifex commit?
still the same case https://github.com/owncloud/core/pull/39933#issuecomment-1082610197

**Comment by phil-davis** [comment]
See my comment https://github.com/owncloud/core/pull/39934#issuecomment-1082668067

It needs to be sorted out on Transifex.

**Comment by kiranparajuli589** [comment]
Related tests are now skipped for oCV10 in #39934

**Comment by kulmann** [comment]
`fr_FR` just recently appeared in transifex and has far less translation percentage than `fr`, see screenshot:

<img width="963" alt="Screenshot 2022-04-01 at 09 03 57" src="https://user-images.githubusercontent.com/3532843/161216025-1ce64de7-69d0-46c4-989c-395c49f92a3c.png">

We could define a minimum percentage for languages to be fetched from transifex at all. Config happens in https://github.com/owncloud/core/blob/master/l10n/.tx/config
That would also mean that translations are not available for certain apps anymore that have a good translation coverage. So probably not a good option. Deleting the language in transifex would have an even worse effect and (as @DeepDiver1975 pointed out in chat) would probably be recreated by transifex automatically.

**Comment by DeepDiver1975** [comment]
Following options do exist:
- explicit remove fr_FR after pulling from transifex
- got with a minimum-perc of 50% - this will filter out quite a lot of half-hearted translations (but also some languages will miss parts - e.g. fedsharing, files-external and files-sharing on Ukrainian)
- compile (and maintain) a list of languages we want to pull it - full control - but effort

**Comment by kulmann** [comment]
> * compile (and maintain) a list of languages we want to pull it - full control - but effort

For reference, this option is what was done in oC Web, see https://github.com/owncloud/web/blob/320e06920cbee501f868a91dcff28b67abf72cd5/packages/web-runtime/l10n/Makefile#L23

**Comment by DeepDiver1975** [comment]
> > * compile (and maintain) a list of languages we want to pull it - full control - but effort
> 
> For reference, this option is what was done in oC Web, see https://github.com/owncloud/web/blob/320e06920cbee501f868a91dcff28b67abf72cd5/packages/web-runtime/l10n/Makefile#L23

yep - we learned from past misstakes when moving on .... ;-)

**Comment by phil-davis** [comment]
I will make a PR to cleanup the `fr_FR` files.

**Comment by jnweiger** [comment]
Confirmed fixed in 10.10.0 RC1

/lib/l10n/fr_FR* not present.
